### ISSUE TITLE
Exception: input[_394] of node[_413] does not exist in node_map

### ISSUE THREAD

**Issue by chenjun2hao** [PaddlePaddle/X2Paddle#103]
I have successfully transferred the pytorch model to onnx and the report for onnx transfer paddle is as follows
`Exception: input[_394] of node[_413] does not exist in node_map`

**Comment by chenjun2hao** [comment]
the whole error:
`
rmer.onnx --save_dir=./
Now translating model from onnx to paddle.
model ir_version: 4, op version: 9
your model have dynamic graph, torch==1.1.0 is required
Traceback (most recent call last):
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/bin/x2paddle", line 10, in <module>
    sys.exit(main())
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/x2paddle/convert.py", line 202, in main
    onnx2paddle(args.model, args.save_dir)
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/x2paddle/convert.py", line 148, in onnx2paddle
    model = ONNXDecoder(model_path)
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py", line 339, in __init__
    self.onnx_graph.build()
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py", line 207, in build
    format(in_node, layer_name))
Exception: input[_35] of node[_54] does not exist in node_map
`

**Comment by jiangjiajun** [comment]
Hello, could you provide us your onnx model or pytorch code for analysis?

**Comment by Channingss** [comment]
收到




| |
chen_lingchi
|
|
邮箱：chen_lingchi@163.com
|

Signature is customized by Netease Mail Master

On 09/02/2019 16:33, Jason wrote:

Hello, could you provide us your onnx model or pytorch code for analysis?

**Comment by chenjun2hao** [comment]
this is my pytorch code. i use pytorch=1.2.0.
```python
import torch
import torch.onnx
import torch.nn as nn

net = torch.nn.TransformerDecoderLayer(512, 8)

if __name__ == '__main__':

    tgt = torch.randn(55, 4, 512)
    memory = torch.randn(200, 4, 512)

    output = net(tgt, memory)
    print(output.shape)

    torch.onnx.export(net, (tgt, memory), 'tranformer.onnx', verbose=True, input_names=['input1', 'input2'])
```
the onnx model which i push [there](https://pan.baidu.com/s/1odL16-XCPexHo6X5DK_buw) 提取码: qvf5
thanks for your reply!

**Comment by MacroBull** [comment]
@chenjun2hao You should constify these dims in PyTorch when exporting to ONNX:
![image](https://user-images.githubusercontent.com/2204917/64144283-5b853580-ce46-11e9-8bc3-875b0aa9787a.png)

do use:
>  *_, c, h, w = x.shape
>  c, h, w = int(c), int(h), int(w)
>  y = x.view(-1, 1, c, h * w)

instead of:
>  *_, c, h, w = x.shape
>  y = x.view(-1, 1, c, h * w)

**Comment by chenjun2hao** [comment]
i have changed the code like this:
original:
```
tgt_len, bsz, embed_dim = query.size()
```
changed:
```
    tgt_len, bsz, embed_dim = query.size()
    tgt_len, bsz, embed_dim = int(tgt_len), int(bsz), int(embed_dim)
```
but still have the similar error.
error:
```
Traceback (most recent call last):
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/bin/x2paddle", line 10, in <module>
    sys.exit(main())
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/x2paddle/convert.py", line 211, in main
    onnx2paddle(args.model, args.save_dir)
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/x2paddle/convert.py", line 154, in onnx2paddle
    model = ONNXDecoder(model_path)
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py", line 339, in __init__
    self.onnx_graph.build()
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py", line 207, in build
    format(in_node, layer_name))
Exception: input[_24] of node[_32] does not exist in node_map

```

**Comment by Channingss** [comment]
Hello,  I try to x2paddle with your old model ,  it report dimension mismatch Error. could you provide us latest  onnx model for analysis?

**Comment by chenjun2hao** [comment]
this the link for latest model:[link](https://pan.baidu.com/s/1Of-v0T8ZOlVyYG7w8qkkMA) 提取码: mam8
the error:
```
Traceback (most recent call last):
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/bin/x2paddle", line 10, in <module>
    sys.exit(main())
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/x2paddle/convert.py", line 211, in main
    onnx2paddle(args.model, args.save_dir)
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/x2paddle/convert.py", line 154, in onnx2paddle
    model = ONNXDecoder(model_path)
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py", line 339, in __init__
    self.onnx_graph.build()
  File "/home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py", line 207, in build
    format(in_node, layer_name))
Exception: input[_24] of node[_32] does not exist in node_map
```
besides, when I converted to onnx, it looked like there was 24 missing. I don't know if that was the problem here.
the part detail printed when converted to onnx.
```
graph(%query.1 : Float(55, 4, 512),
      %key : Float(200, 4, 512),
      %self_attn.in_proj_weight : Float(1536, 512),
      %self_attn.in_proj_bias : Float(1536),
      %self_attn.out_proj.weight : Float(512, 512),
      %self_attn.out_proj.bias : Float(512),
      %multihead_attn.in_proj_weight : Float(1536, 512),
      %multihead_attn.in_proj_bias : Float(1536),
      %multihead_attn.out_proj.weight : Float(512, 512),
      %multihead_attn.out_proj.bias : Float(512),
      %linear1.weight : Float(2048, 512),
      %linear1.bias : Float(2048),
      %linear2.weight : Float(512, 2048),
      %linear2.bias : Float(512),
      %norm1.weight : Float(512),
      %norm1.bias : Float(512),
      %norm2.weight : Float(512),
      %norm2.bias : Float(512),
      %norm3.weight : Float(512),
      %norm3.bias : Float(512)):
  %20 : Float(512!, 1536!) = onnx::Transpose[perm=[1, 0]](%self_attn.in_proj_weight), scope: TransformerDecoderLayer/MultiheadAttention[self_attn] # /home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py:1371:0
  %21 : Float(55, 4, 1536) = onnx::MatMul(%query.1, %20), scope: TransformerDecoderLayer/MultiheadAttention[self_attn] # /home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py:1371:0
  %22 : Float(55, 4, 1536) = onnx::Add(%21, %self_attn.in_proj_bias), scope: TransformerDecoderLayer/MultiheadAttention[self_attn] # /home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py:1373:0
  %23 : Float(55, 4!, 512), %24 : Float(55, 4, 512), %25 : Float(55, 4, 512) = onnx::Split[axis=-1, split=[512, 512, 512]](%22), scope: TransformerDecoderLayer/MultiheadAttention[self_attn] # /home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py:3219:0
  %26 : Tensor = onnx::Constant[value={0.125}]()
  %27 : Float(55, 4, 512) = onnx::Mul(%23, %26), scope: TransformerDecoderLayer/MultiheadAttention[self_attn] # /home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py:3214:0
  %28 : Tensor = onnx::Constant[value= 55  32  64 [ Variable[CPULongType]{3} ]](), scope: TransformerDecoderLayer/MultiheadAttention[self_attn]
  %29 : Float(55, 32, 64) = onnx::Reshape(%27, %28), scope: TransformerDecoderLayer/MultiheadAttention[self_attn] # /home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py:3214:0
  %30 : Float(32!, 55!, 64) = onnx::Transpose[perm=[1, 0, 2]](%29), scope: TransformerDecoderLayer/MultiheadAttention[self_attn] # /home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py:3214:0
  %31 : Tensor = onnx::Constant[value= -1  32  64 [ Variable[CPULongType]{3} ]](), scope: TransformerDecoderLayer/MultiheadAttention[self_attn]
  %32 : Float(55, 32, 64) = onnx::Reshape(%24, %31), scope: TransformerDecoderLayer/MultiheadAttention[self_attn] # /home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py:3217:0
  %33 : Tensor = onnx::Constant[value= -1  32  64 [ Variable[CPULongType]{3} ]](), scope: TransformerDecoderLayer/MultiheadAttention[self_attn]
  %34 : Float(55, 32, 64) = onnx::Reshape(%25, %33), scope: TransformerDecoderLayer/MultiheadAttention[self_attn] # /home/yangna/yangna/tool/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py:3219:0
```

**Comment by Channingss** [comment]
we update onnx2paddle,  you can try the latest code

**Comment by chenjun2hao** [comment]
@Channingss , thanks, i will have a try.

**Comment by chenjun2hao** [comment]
@Channingss , May I ask if you have updated the PIP source? It passed the test two days ago and failed today.

**Comment by jiangjiajun** [comment]
> @Channingss , May I ask if you have updated the PIP source? It passed the test two days ago and failed today.
> must install x2paddle with method 3.
pip source will be updated in this week.
