### ISSUE TITLE
FlagEmbedding模型onnx转paddle成功但是转换后模型无法加载

### ISSUE THREAD

**Issue by czx97** [PaddlePaddle/X2Paddle#1053]
## 问题描述
onnx转paddle成功但是转换后模型无法加载
- 错误信息
Traceback (most recent call last):
  File "paddle_infer.py", line 7, in <module>
    model = paddle.jit.load(paddle_path)
  File "/opt/conda/envs/paddle2.5.1_cuda11.2/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/conda/envs/paddle2.5.1_cuda11.2/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/paddle2.5.1_cuda11.2/lib/python3.8/site-packages/paddle/fluid/framework.py", line 449, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/paddle2.5.1_cuda11.2/lib/python3.8/site-packages/paddle/jit/api.py", line 1500, in load
    return TranslatedLayer._construct(model_path, config)
  File "/opt/conda/envs/paddle2.5.1_cuda11.2/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/conda/envs/paddle2.5.1_cuda11.2/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/paddle2.5.1_cuda11.2/lib/python3.8/site-packages/paddle/fluid/framework.py", line 449, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/paddle2.5.1_cuda11.2/lib/python3.8/site-packages/paddle/jit/translated_layer.py", line 1455, in _construct
    programs = _construct_program_holders(model_path, model_filename)
  File "/opt/conda/envs/paddle2.5.1_cuda11.2/lib/python3.8/site-packages/paddle/jit/translated_layer.py", line 842, in _construct_program_holders
    _load_program_desc(model_file_path)
  File "/opt/conda/envs/paddle2.5.1_cuda11.2/lib/python3.8/site-packages/paddle/jit/translated_layer.py", line 51, in _load_program_desc
    program_desc = core.ProgramDesc(program_desc_str)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at ../paddle/fluid/framework/program_desc.cc:150)

- 错误截图
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/47a097fc-91a5-4543-aa70-72c49cd622b2">

## 具体信息

- 转换模型后用处
    - [ ] 使用 Paddle 框架/ PaddleInference 推理预测

- 模型来源
https://huggingface.co/BAAI/bge-reranker-base

- 应用场景
文本检索

- 版本信息
PaddlePaddle =>2.5.1
X2Paddle => 1.4.1

**Comment by czx97** [comment]
<img width="974" alt="image" src="https://github.com/user-attachments/assets/c87c0714-a713-4212-8852-e1626bd084e9">
转换后的文件目录结构

**Comment by luotao1** [comment]
从报错信息里看，你使用的是paddle2.5.1，目前x2paddle只适配到paddle2.4.2，可以降低下Paddle版本。
具体可参考 https://github.com/PaddlePaddle/X2Paddle/blob/develop/test_benchmark/ONNX/FaceNet/pd_infer.py 的例子。

**Comment by czx97** [comment]
参考单测的写法模型加载成功啦，结果和onnx版一致，感谢~~
<img width="643" alt="image" src="https://github.com/user-attachments/assets/897a488d-8243-40d6-9243-e91b064160c3">
