### ISSUE TITLE
Exception: Model is not supported yet.

### ISSUE THREAD

**Issue by ChristoCai** [PaddlePaddle/X2Paddle#1094]
## 问题描述
Traceback (most recent call last):
  File "/home/pc/anaconda3/envs/x2paddle/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.4.1', 'console_scripts', 'x2paddle')())
  File "/home/pc/anaconda3/envs/x2paddle/lib/python3.9/site-packages/x2paddle/convert.py", line 501, in main
    onnx2paddle(args.model,
  File "/home/pc/anaconda3/envs/x2paddle/lib/python3.9/site-packages/x2paddle/convert.py", line 316, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "/home/pc/anaconda3/envs/x2paddle/lib/python3.9/site-packages/x2paddle/op_mapper/onnx2paddle/onnx_op_mapper.py", line 39, in __init__
    raise Exception("Model is not supported yet.")
Exception: Model is not supported yet.
- 错误信息
- 错误截图
![image](https://github.com/user-attachments/assets/b29c7620-87c2-4362-8e1b-fb919581e955)

## 具体信息

- 转换模型后用处
    - [x] 使用 Paddle-Lite 做移动端推理
    - [ ] 转换预训练参数，再使用 Paddle 进行模型开发
- 模型来源
[YOLOX：https://github.com/Megvii-BaseDetection/YOLOX](https://github.com/magicleap/SuperGluePretrainedNetwork)
- 应用场景
用于移动端业务下的检测业务

**Comment by megemini** [comment]
报的错误是缺少 onnx 算子 ～ 目前支持的算子可以参考 https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/inference_model_convertor/op_list.md

这里缺少的算子只能看看后续有没有维护计划，或者自己尝试添加一下算子的实现了 ～
