### ISSUE TITLE
Exception: Paddle>=2.0.0 is required, Please update version!

### ISSUE THREAD

**Issue by zxj329** [PaddlePaddle/X2Paddle#1100]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
x2paddle --framework onnx --model /home/zhengxinjiang/code/DeepFilterNet-main/torchDF/denoiser_model.onnx -save_dir pd_model
转模型的时候发生version报错

**更多信息 :**

**报错截图**
Traceback (most recent call last):
  File "/home/zhengxinjiang/anaconda3/envs/py3.8/bin/x2paddle", line 5, in <module>
    from x2paddle.convert import main
  File "/home/zhengxinjiang/anaconda3/envs/py3.8/lib/python3.8/site-packages/x2paddle/convert.py", line 17, in <module>
    from x2paddle.utils import ConverterCheck
  File "/home/zhengxinjiang/anaconda3/envs/py3.8/lib/python3.8/site-packages/x2paddle/utils.py", line 112, in <module>
    paddle_dtypes = PaddleDtypes(is_new_version)
  File "/home/zhengxinjiang/anaconda3/envs/py3.8/lib/python3.8/site-packages/x2paddle/utils.py", line 108, in __init__
    raise Exception("Paddle>=2.0.0 is required, Please update version!")
Exception: Paddle>=2.0.0 is required, Please update version!

**其他信息**
Package                  Version
------------------------ --------------
absl-py                  1.4.0
aiofiles                 23.1.0
aiohttp                  3.8.4
aiosignal                1.3.1
altair                   4.2.2
anyio                    3.6.2
appdirs                  1.4.4
astor                    0.8.1
async-timeout            4.0.2
attrs                    22.2.0
audioread                3.0.0
cachetools               5.3.0
certifi                  2022.12.7
cffi                     1.15.1
chardet                  5.1.0
charset-normalizer       3.0.1
click                    8.1.3
cloudpickle              2.2.1
cmake                    3.26.3
colorama                 0.4.6
contextlib2              21.6.0
contourpy                1.0.7
cycler                   0.11.0
decorator                5.1.1
dnspython                2.3.0
einops                   0.6.0
entrypoints              0.4
fastapi                  0.95.0
ffmpy                    0.3.0
filelock                 3.10.0
fonttools                4.38.0
frozenlist               1.3.3
fsspec                   2023.3.0
ftfy                     6.1.1
future                   0.18.3
google-auth              2.16.1
google-auth-oauthlib     0.4.6
gradio                   3.25.0
gradio_client            0.1.0
grpcio                   1.51.3
h11                      0.14.0
httpcore                 0.17.0
httpx                    0.24.0
huggingface-hub          0.13.4
hyperopt                 0.1.2
idna                     3.4
importlib-metadata       6.0.0
importlib-resources      5.12.0
Jinja2                   3.1.2
joblib                   1.2.0
json-tricks              3.16.1
jsonschema               4.17.3
kiwisolver               1.4.4
librosa                  0.9.2
linkify-it-py            2.0.0
lit                      16.0.1
llvmlite                 0.39.1
Markdown                 3.4.1
markdown-it-py           2.2.0
MarkupSafe               2.1.2
matplotlib               3.7.0
mdit-py-plugins          0.3.3
mdurl                    0.1.2
mpmath                   1.3.0
msgpack                  1.0.4
multidict                6.0.4
networkx                 3.0
nni                      2.10
numba                    0.56.4
numpy                    1.23.5
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
oauthlib                 3.2.2
olefile                  0.46
opt-einsum               3.3.0
orjson                   3.8.10
packaging                23.0
paddlepaddle             3.0.0b1
pandas                   1.5.3
Pillow                   9.4.0
pip                      22.3.1
pkgutil_resolve_name     1.3.10
pooch                    1.6.0
prettytable              3.6.0
progressbar              2.5
protobuf                 4.22.0
psutil                   5.9.4
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycparser                2.21
pydantic                 1.10.7
pydub                    0.25.1
pymongo                  4.3.3
pyparsing                3.0.9
pyrsistent               0.19.3
python-dateutil          2.8.2
python-multipart         0.0.6
PythonWebHDFS            0.2.3
pytorch-lightning        1.2.0
pytz                     2022.7.1
PyYAML                   6.0
regex                    2023.3.23
requests                 2.28.2
requests-oauthlib        1.3.1
resampy                  0.4.2
responses                0.23.1
rsa                      4.9
schema                   0.7.5
scikit-learn             1.2.1
scipy                    1.10.1
semantic-version         2.10.0
setuptools               65.6.3
simplejson               3.18.4
six                      1.16.0
sniffio                  1.3.0
soundfile                0.12.1
starlette                0.26.1
sympy                    1.11.1
tensorboard              2.12.0
tensorboard-data-server  0.7.0
tensorboard-plugin-wit   1.8.1
threadpoolctl            3.1.0
tokenizers               0.13.3
toolz                    0.12.0
torch                    1.10.0+cu111
torchaudio               0.10.0+rocm4.1
torchlibrosa             0.0.9
torchvision              0.11.0+cu111
tqdm                     4.64.1
transformers             4.27.4
triton                   2.0.0
typeguard                2.13.3
types-PyYAML             6.0.12.8
typing_extensions        4.5.0
uc-micro-py              1.0.1
urllib3                  1.26.14
uvicorn                  0.21.1
wcwidth                  0.2.6
websockets               10.4
Werkzeug                 2.2.3
wheel                    0.38.4
x2paddle                 1.5.0
yarl                     1.8.2
zipp                     3.14.0

**Comment by Zheng-Bicheng** [comment]
这个应该不属于 Paddle2ONNX 负责？

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/X2Paddle

**Comment by megemini** [comment]
这里是判断 paddle 版本时出错了，可以试试拉取最新版本的 x2paddle ～ 也就是 github 上的 dev 版本进行转换 ～

**Comment by luotao1** [comment]
已发布 V1.6.0 版本，支持 Paddle 3.0 beta 版，可以试下。
