### ISSUE TITLE
 aten::tril_ ｜ PyTorchOpMapper ｜Model is not supported yet.

### ISSUE THREAD

**Issue by dimensionplane** [PaddlePaddle/X2Paddle#1106]
感谢您参与 X2Paddle 社区！ 问题模版为了 X2Paddle 能更好的迭代，例如新功能发布、 RoadMaps 和错误跟踪. :smile_cat:

## 问题描述

 to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  if len(presents) == 0:

========= 1 OPs are not supported yet ===========
========== aten::tril_ ============
Traceback (most recent call last):
  File "/jfs/wangxueyang/codegeex4/git_paddle_run.py", line 18, in <module>
    pytorch2paddle(pt_model, save_dir , jit_type, [inputs["input_ids"], inputs["attention_mask"],inputs["position_ids"]])
  File "/jfs/wangxueyang/conda/codegeex_9b_b/lib/python3.10/site-packages/x2paddle/convert.py", line 399, in pytorch2paddle
    mapper = PyTorchOpMapper(model)
  File "/jfs/wangxueyang/conda/codegeex_9b_b/lib/python3.10/site-packages/x2paddle/op_mapper/pytorch2paddle/pytorch_op_mapper.py", line 44, in __init__
    raise Exception("Model is not supported yet.")
Exception: Model is not supported yet.

## 具体信息

- 转换模型后用处
    - [ ] 使用 Paddle 框架/ PaddleInference 推理预测
    - [ ] 使用 Paddle-Lite 做移动端推理
    - [ ] 转换预训练参数，再使用 Paddle 进行模型开发
- 模型来源
codegeex4-all-9b：https://hf-mirror.com/THUDM/codegeex4-all-9b/tree/main
- 应用场景
用于移动端业务下的检测业务
- 版本信息
PaddlePaddle => :3.0.0b1:
X2Paddle => :1.6.0:
来源框架版本PyTorch=> :2.3.1:
- 您的联系方式(邮箱/微信/电话)

**Comment by megemini** [comment]
这个算子木有做映射 ～ docs/inference_model_convertor/op_list.md 这里面是目前支持的算子 ～

可以在 x2paddle/op_mapper/pytorch2paddle/aten.py 里面先尝试一下实现这个算子 ～
