### ISSUE TITLE
don't support torch.tensor.expand?

### ISSUE THREAD

**Issue by chenjun2hao** [PaddlePaddle/X2Paddle#143]
when i use pytorch torch.tensor.expand, the error
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch120/bin/onnx_infer", line 11, in <module>
    load_entry_point('x2paddle==0.5.0', 'console_scripts', 'onnx_infer')()
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/x2paddle-0.5.0-py3.6.egg/x2paddle/onnx_infer.py", line 48, in main
    res = sess.run(None, input_feed=inputs_dict)
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 72, in run
    return self._sess.run(output_names, input_feed, run_options)
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:341 void onnxruntime::BroadcastIterator::Init(int64_t, int64_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. -1 by 264
Stacktrace:

There are 1 ops not supported yet, list as below
Expand
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch120/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==0.5.0', 'console_scripts', 'x2paddle')()
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/x2paddle-0.5.0-py3.6.egg/x2paddle/convert.py", line 211, in main
    onnx2paddle(args.model, args.save_dir)
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/x2paddle-0.5.0-py3.6.egg/x2paddle/convert.py", line 157, in onnx2paddle
    mapper = ONNXOpMapper(model, save_dir)
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/x2paddle-0.5.0-py3.6.egg/x2paddle/op_mapper/onnx_op_mapper.py", line 68, in __init__
    raise Exception("Model are not supported yet.")
Exception: Model are not supported yet.
```
it seems don't support expand?

**Comment by Channingss** [comment]
Currently we don't support Expand related operators,  Can you provide code or onnx model?

**Comment by Channingss** [comment]
I think you can try like this:
`_X = fluid.layers.data(shape=[3, 1], name='_X', dtype='float32', append_batch_size=False)
_Z_ones = fluid.layers.ones(shape=[3, 6], dtype='float32')
_Z = fluid.layers.elementwise_mul(x=_Z_ones, y=_X, name='_Z')`

**Comment by chenjun2hao** [comment]
@Channingss , now i have successfully conveted to onnx, when convert to paddle it seems the dims is not  right. and i don't have the broadcast operater.could give some advice?
the error:
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch120/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==0.5.0', 'console_scripts', 'x2paddle')()
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/x2paddle-0.5.0-py3.6.egg/x2paddle/convert.py", line 214, in main
    onnx2paddle(args.model, args.save_dir)
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/x2paddle-0.5.0-py3.6.egg/x2paddle/convert.py", line 160, in onnx2paddle
    mapper = ONNXOpMapper(model, save_dir)
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/x2paddle-0.5.0-py3.6.egg/x2paddle/op_mapper/onnx_op_mapper.py", line 73, in __init__
    self.get_output_shapes()
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/x2paddle-0.5.0-py3.6.egg/x2paddle/op_mapper/onnx_op_mapper.py", line 169, in get_output_shapes
    self.decoder.onnx_graph.place_holder_nodes)
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/x2paddle-0.5.0-py3.6.egg/x2paddle/op_mapper/onnx_op_mapper.py", line 137, in get_results_of_inference
    np.save(os.path.join(self.tmp_data_dir, 'input_data.npy'), inputs)
  File "<__array_function__ internals>", line 6, in save
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/numpy/lib/npyio.py", line 540, in save
    arr = np.asanyarray(arr)
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/numpy/core/_asarray.py", line 138, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
ValueError: could not broadcast input array from shape (4,1,70,256) into shape (4)
```
my onnx model:链接: https://pan.baidu.com/s/1nr9dS1sJNa_9PagX1n3v6g 提取码: hy8x

**Comment by Channingss** [comment]
@chenjun2hao  onnx::expand is supported, If you has no problem, we will close the issue. If there are any other questions, we can open later.
