### ISSUE TITLE
don't support onnx::equal and onnx::where?

### ISSUE THREAD

**Issue by chenjun2hao** [PaddlePaddle/X2Paddle#154]
it seems don't support equal and where operater
the error:
```
There are 2 ops not supported yet, list as below
Where
Equal
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch120/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==0.5.0', 'console_scripts', 'x2paddle')()
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/x2paddle-0.5.0-py3.6.egg/x2paddle/convert.py", line 215, in main
    onnx2paddle(args.model, args.save_dir)
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/x2paddle-0.5.0-py3.6.egg/x2paddle/convert.py", line 161, in onnx2paddle
    mapper = ONNXOpMapper(model, save_dir)
  File "/root/miniconda3/envs/torch120/lib/python3.6/site-packages/x2paddle-0.5.0-py3.6.egg/x2paddle/op_mapper/onnx_op_mapper.py", line 76, in __init__
    raise Exception("Model are not supported yet.")
Exception: Model are not supported yet.

```

**Comment by Channingss** [comment]
onnx::equal and onnx::where  is under development, we will tell you the first time.

**Comment by chenjun2hao** [comment]
@Channingss ,For a more complete project, you can also add the following actions：
```
There are 5 ops not supported yet, list as below
Not
Tile
Where
Greater
Equal
```

**Comment by Channingss** [comment]
@chenjun2hao thanks for your feedback, we will  add these OP to our development task.
