### ISSUE TITLE
Op registered

### ISSUE THREAD

**Issue by jessionlin** [PaddlePaddle/X2Paddle#258]
when I run x2paddle , I got the following error: 
Traceback (most recent call last):
  File "/home/jxlin/anaconda3/envs/onnx2paddle/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==0.7.1', 'console_scripts', 'x2paddle')()
  File "/home/jxlin/anaconda3/envs/onnx2paddle/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/convert.py", line 251, in main
    onnx2paddle(args.model, args.save_dir, params_merge)
  File "/home/jxlin/anaconda3/envs/onnx2paddle/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/convert.py", line 172, in onnx2paddle
    model = ONNXDecoder(model_path)
  File "/home/jxlin/anaconda3/envs/onnx2paddle/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/decoder/onnx_decoder.py", line 324, in __init__
    check_model(model)
  File "/home/jxlin/anaconda3/envs/onnx2paddle/lib/python3.6/site-packages/onnx/checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for Einsum with domain_version of 12

==> Context: Bad node spec: input: "177" input: "181" output: "183" name: "Einsum_148" op_type: "Einsum" attribute { name: "equation" s: "bfnd,ndh->bfh" type: STRING }

environment :
python: 3.6 
torch             1.5.0+cu92
torchvision       0.6.0+cu92
paddlepaddle      1.8.1
onnx              1.6.0
onnxruntime       1.0.0
opset_version 12

**Comment by Channingss** [comment]
@jessionlin x2paddle目前支持onnx的模型opset_version==9，如果是从torch导出来的onnx，可以指定一下opset_version

**Comment by jiangjiajun** [comment]
此issue长时间未更新，将被关闭，如有需求，可随时再重新打开。
