### ISSUE TITLE
The count of Concat node\'s input is not more than 1.

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/X2Paddle#263]
用最新版转换遇到一个问题，请问怎么调试？
```
paddle.__version__ = 1.8.1
Now translating model from caffe to paddle.
Total nodes: 208
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==0.7.1', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/convert.py", line 245, in main
    args.caffe_proto, params_merge)
  File "/usr/local/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/convert.py", line 148, in caffe2paddle
    mapper = CaffeOpMapper(model)
  File "/usr/local/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/op_mapper/caffe_op_mapper.py", line 48, in __init__
    func(node)
  File "/usr/local/lib/python3.6/site-packages/x2paddle-0.7.1-py3.6.egg/x2paddle/op_mapper/caffe_op_mapper.py", line 470, in Concat
    ) > 1, 'The count of Concat node\'s input is not more than 1.'
AssertionError: The count of Concat node's input is not more than 1.
```

**Comment by SunAhong1993** [comment]
> ```
> AssertionError: The count of Concat node's input is not more than 1.
> ```

你好，这边可以确认下caffe中的Concat是否有2个或以上的输入（bottom），当输入只有一个是无法转换的。

**Comment by imistyrain** [comment]
the assert in [caffe_op_mapper.py](https://github.com/PaddlePaddle/X2Paddle/blob/5480c7dc24344ff5eea17b8e764c9d2f5011ac2d/x2paddle/op_mapper/caffe_op_mapper.py#L470) should be changed to :
\>=1
