### ISSUE TITLE
instance normalization转换出错

### ISSUE THREAD

**Issue by mensaochun** [PaddlePaddle/X2Paddle#266]
错误日志：
Traceback (most recent call last):
  File "/home/yourenchun/.conda/envs/torch10py36/lib/python3.6/site-packages/x2paddle/core/op_mapper.py", line 123, in save_inference_model
    inputs, outputs = model.x2paddle_net()
  File "/data/projects/iqy_cartoon/reid-strong-baseline-data/trans_models/reid-strong-baseline-data/trans_models/resnet50_ibn_a/model_with_code/model.py", line 72, in x2paddle_net
    x2paddle_361 = InstanceNormalization_layer([x2paddle_359, x2paddle_base_layer1_0_bn1_IN_weight, x2paddle_base_layer1_0_bn1_IN_bias], name='x2paddle_361')
  File "/data/projects/iqy_cartoon/reid-strong-baseline-data/trans_models/reid-strong-baseline-data/trans_models/resnet50_ibn_a/model_with_code/model.py", line 9, in InstanceNormalization_layer
    mean = fluid.layers.reduce_mean(input_, dim=[2, 3], keep_dim=True)
  File "/home/yourenchun/.conda/envs/torch10py36/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 6345, in reduce_mean
    % (type(input)))
TypeError: The type of 'input' in reduce_mean must be Variable, but received <class 'list'>

**Comment by Channingss** [comment]
@mensaochun 
https://github.com/PaddlePaddle/X2Paddle/blob/57c4e41d73f52febb9db9c01a80b0f4995a04e46/x2paddle/op_mapper/onnx_custom_layer/InstanceNormalization.py#L25
change this line  to : input_ = inputs[0][0] will fix this bug, we will fix this bug of InstanceNormalization after we upgrade onnx2paddle support paddle1.8.
