### ISSUE TITLE
Paddle模型转Onnx模型时错误

### ISSUE THREAD

**Issue by liangruofei** [PaddlePaddle/X2Paddle#282]
环境：paddlepaddle==1.8.0   tensorflow==1.15.0
onnx == 1.6.0
onnxruntime == 1.0.0

aistudio@jupyter-282556-554530:~$ x2paddle --framework=paddle2onnx --model=paddle2oxnn --save_dir=onnx_model
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
paddle.__version__ = 1.8.0
Translating PaddlePaddle to ONNX...

Total:73, Current:36 : bilinear_interp                   Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/x2paddle", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/convert.py", line 272, in main
    paddle2onnx(args.model, args.save_dir)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/convert.py", line 194, in paddle2onnx
    mapper.convert(model.program, save_dir)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/op_mapper/paddle_op_mapper.py", line 790, in convert
    node = getattr(self, op.type)(op, block)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/op_mapper/paddle_op_mapper.py", line 580, in bilinear_interp
    raise Exception("Unexpected situation happend")
Exception: Unexpected situation happend

**Comment by Channingss** [comment]
模型是在paddle1.8的基础上开发的吗？麻烦列一下Paddle网络结构里面，使用到resize_bilinear这个op的代码部分，以及相关的输入参数是tensor还是常量

**Comment by jiangjiajun** [comment]
此issue常期未更新，将被关闭，如有需求，可随时再打开。
