### ISSUE TITLE
ValueError: Data Type mismatch: 2 to 3

### ISSUE THREAD

**Issue by dubhex** [PaddlePaddle/X2Paddle#287]
paddlepaddle==1.8.2
x2paddle==0.7.4

错误信息：
paddle.__version__ = 1.8.2
Now translating model from onnx to paddle.
model ir_version: 6, op version: 9
2020-06-29 17:41:53,907-WARNING: During conversion of your  model, some operators will be assignd node.out_shape==None, refer to https://github.com/onnx/onnx/blob/master/docs/ShapeInference.md
Total nodes: 158
Traceback (most recent call last):
  File "/Users/hello/Softwares/anaconda3/lib/python3.7/site-packages/x2paddle-0.7.4-py3.7.egg/x2paddle/core/op_mapper.py", line 123, in save_inference_model
    inputs, outputs = model.x2paddle_net()
  File "mv3_occlu_0629_tmp/mv3_gp_small_pose_visible_s_Paddle/model_with_code/model.py", line 167, in x2paddle_net
    x2paddle_470 = fluid.layers.concat([x2paddle_468, x2paddle_475], axis=0)
  File "/Users/hello/Softwares/anaconda3/lib/python3.7/site-packages/paddle/fluid/layers/tensor.py", line 352, in concat
    out = helper.create_variable_for_type_inference(dtype=helper.input_dtype())
  File "/Users/hello/Softwares/anaconda3/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 98, in input_dtype
    (dtype, each.dtype))
ValueError: Data Type mismatch: 2 to 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hello/Softwares/anaconda3/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==0.7.4', 'console_scripts', 'x2paddle')()
  File "/Users/hello/Softwares/anaconda3/lib/python3.7/site-packages/x2paddle-0.7.4-py3.7.egg/x2paddle/convert.py", line 268, in main
    onnx2paddle(args.model, args.save_dir, params_merge)
  File "/Users/hello/Softwares/anaconda3/lib/python3.7/site-packages/x2paddle-0.7.4-py3.7.egg/x2paddle/convert.py", line 186, in onnx2paddle
    mapper.save_inference_model(save_dir, params_merge)
  File "/Users/hello/Softwares/anaconda3/lib/python3.7/site-packages/x2paddle-0.7.4-py3.7.egg/x2paddle/core/op_mapper.py", line 159, in save_inference_model
    .format(py_code_dir))
Exception: Paddle code was saved in mv3_occlu_0629_tmp/mv3_gp_small_pose_visible_s_Paddle/model_with_code/model.py, but seems there's wrong exist, please check model.py manually.

辛苦帮忙看看什么问题，多谢啦！

**Comment by Channingss** [comment]
@dubhex 目前最新的develop版本已解决该问题。
