### ISSUE TITLE
转换带有prelu的模型会失败

### ISSUE THREAD

**Issue by Y-Rony** [PaddlePaddle/X2Paddle#298]
onnx版本： 1.6.0
onnxruntime版本： 1.0.0
python： 3.6
OS：win10
命令:
x2paddle --framework=onnx --model=E:/project/pytorch/onnx/my_checkpoint.onnx --save_dir=E:/project/paddle/models/

error如下：

initializer 'layer4.2.bn1.num_batches_tracked'. It is not used by any node and should be removed from the model.
Total nodes: 149
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\x2paddle.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\x2paddle\convert.py", line 268, in main
    onnx2paddle(args.model, args.save_dir, params_merge)
  File "c:\programdata\anaconda3\lib\site-packages\x2paddle\convert.py", line 182, in onnx2paddle
    mapper = ONNXOpMapper(model, save_dir)
  File "c:\programdata\anaconda3\lib\site-packages\x2paddle\op_mapper\onnx_op_mapper.py", line 91, in __init__
    func(node)
  File "c:\programdata\anaconda3\lib\site-packages\x2paddle\op_mapper\onnx_op_mapper.py", line 1027, in PRelu
    if len(shape_slope) == 1:
TypeError: object of type 'NoneType' has no len()

**Comment by Channingss** [comment]
请问使用的是pip install，还是：https://github.com/PaddlePaddle/X2Paddle#%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F%E4%B8%80%E6%8E%A8%E8%8D%90
如果是pip install，请使用链接里面提到的安装方式尝试一下。
```
pip uninstall x2paddle
git clone https://github.com/PaddlePaddle/X2Paddle.git
cd X2Paddle
git checkout develop
python setup.py install
```

**Comment by jiangjiajun** [comment]
由于长时间未更新，此issue将被关闭，如有需求，可随时再打开
