### ISSUE TITLE
matrix_nms not supported

### ISSUE THREAD

**Issue by Tim4AI** [PaddlePaddle/X2Paddle#348]
1.想使用x2paddle转换一下，ppyolo试一下，说不支持matrix_nms
x2paddle --framework=paddle2onnx --model=output/ppyolo_tiny/ --save_dir=output/ppyolo_tiny

paddle.__version__ = 0.0.0
[WARNING] You are use develop version of paddlepaddle
Translating PaddlePaddle to ONNX...

Total:109, Current:109 : fetch
There's 1 ops are not supported yet
=========== matrix_nms ===========
2.对于以上类似的不支持的层，我有没有办法去除这个层，然后让转换通过，我自己去实现不支持的层

**Comment by Channingss** [comment]
@Tim5Tang 
1. 这边目前还不支持matrix_nms，我们评估一下后会及时反馈
2. 第二个问题可以到PaddleDetection那边提一下Issue，在导出模型的时候应该可以改下代码来实现。

**Comment by Tim5Tang** [comment]
好的谢谢

**Comment by Tim5Tang** [comment]
我删了paddledetection中的部分代码

**Comment by Tim4AI** [comment]
好的谢谢，我删了paddledetection 中的部分代码，然后没有报错matrix_nms了，但是说我们onnx版本不对，这个版本我可以怎么控制，还是与我安装的onnx有关系
paddle.__version__ = 0.0.0
[WARNING] You are use develop version of paddlepaddle
Now, onnx2paddle support convert onnx model opset_verison [9, 10, 11],opset_verison of your onnx model is 10, automatically treated as op_set: 10.
Translating PaddlePaddle to ONNX...

Total:110, Current:1 : feed im_size
Total:110, Current:2 : feed image
Total:110, Current:91 : nearest_interp Traceback (most recent call last):
  File "/home/tangzixing/anaconda3/envs/paddle/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==0.8.1', 'console_scripts', 'x2paddle')()
  File "/home/tangzixing/anaconda3/envs/paddle/lib/python3.6/site-packages/x2paddle-0.8.1-py3.6.egg/x2paddle/convert.py", line 272, in main
    paddle2onnx(args.model, args.save_dir, opset_version=args.onnx_opset)
  File "/home/tangzixing/anaconda3/envs/paddle/lib/python3.6/site-packages/x2paddle-0.8.1-py3.6.egg/x2paddle/convert.py", line 205, in paddle2onnx
    opset_version=opset_version)
  File "/home/tangzixing/anaconda3/envs/paddle/lib/python3.6/site-packages/x2paddle-0.8.1-py3.6.egg/x2paddle/op_mapper/paddle2onnx/paddle_op_mapper.py", line 55, in convert
    node = getattr(self.op_set, op.type)(op, block)
  File "/home/tangzixing/anaconda3/envs/paddle/lib/python3.6/site-packages/x2paddle-0.8.1-py3.6.egg/x2paddle/op_mapper/paddle2onnx/opset9/opset.py", line 674, in nearest_interp
    "Resize in onnx(opset<=10) only support coordinate_transformation_mode: 'asymmetric', Try converting with --onnx_opest 11"
Exception: Resize in onnx(opset<=10) only support coordinate_transformation_mode: 'asymmetric', Try converting with --onnx_opest 11

**Comment by Channingss** [comment]
x2paddle 转换的时候 指定： --onnx_opest 11

**Comment by Tim4AI** [comment]
嗯解决了谢谢，这个命令参数要放前面，尴尬我放后面说不能识别
