### ISSUE TITLE
转eco的onnx报错

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/X2Paddle#375]
ONNX模型： ECO 视频分类
报错信息：
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
paddle.__version__ = 1.8.0
Now translating model from onnx to paddle.
model ir_version: 4, op version: 9
shape inferencing ...
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 9, automatically treated as op_set: 9.
Total nodes: 138
Nodes converting ...
convert failed node:355, op_type is Pad
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/x2paddle", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/convert.py", line 269, in main
    onnx2paddle(args.model, args.save_dir, params_merge)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/convert.py", line 185, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/onnx_op_mapper.py", line 42, in __init__
    func(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 73, in run_mapping
    res = func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 437, in Pad
    attr['paddings'] = paddings
UnboundLocalError: local variable 'paddings' referenced before assignment

**Comment by jiangjiajun** [comment]
> ONNX模型： ECO 视频分类
> 报错信息：
> /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
> import imp
> paddle.**version** = 1.8.0
> Now translating model from onnx to paddle.
> model ir_version: 4, op version: 9
> shape inferencing ...
> shape inferenced.
> Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 9, automatically treated as op_set: 9.
> Total nodes: 138
> Nodes converting ...
> convert failed node:355, op_type is Pad
> Traceback (most recent call last):
> File "/opt/conda/envs/python35-paddle120-env/bin/x2paddle", line 10, in
> sys.exit(main())
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/convert.py", line 269, in main
> onnx2paddle(args.model, args.save_dir, params_merge)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/convert.py", line 185, in onnx2paddle
> mapper = ONNXOpMapper(model)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/onnx_op_mapper.py", line 42, in **init**
> func(node)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 73, in run_mapping
> res = func(*args, **kwargs)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 437, in Pad
> attr['paddings'] = paddings
> UnboundLocalError: local variable 'paddings' referenced before assignment

方便的话分享一下你的模型文件，以便于我们进行debug。

**Comment by Channingss** [comment]
@thunder95 试试拉取最新的develop分支代码，然后重新安装一下。

**Comment by thunder95** [comment]
已试过最新的develop代码，也不行, 

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle', 'console_scripts', 'x2paddle')()
  File "/home/aistudio/work/ECO-paddle/onnx/X2Paddle/x2paddle/convert.py", line 269, in main
    onnx2paddle(args.model, args.save_dir, params_merge)
  File "/home/aistudio/work/ECO-paddle/onnx/X2Paddle/x2paddle/convert.py", line 185, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "/home/aistudio/work/ECO-paddle/onnx/X2Paddle/x2paddle/op_mapper/onnx2paddle/onnx_op_mapper.py", line 42, in __init__
    func(node)
  File "/home/aistudio/work/ECO-paddle/onnx/X2Paddle/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 73, in run_mapping
    res = func(*args, **kwargs)
  File "/home/aistudio/work/ECO-paddle/onnx/X2Paddle/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 437, in Pad
    attr['paddings'] = paddings
UnboundLocalError: local variable 'paddings' referenced before assignment
aistudio@jupyter-89442-711729:~/work/ECO-paddle/onnx/X2Paddle$ git branch
* develop

**Comment by thunder95** [comment]
@jiangjiajun @Channingss  不清楚onnx文件怎么传  有点大 100多mb

目前直接手动搭好了网络，还是无法通过x2paddle直接转。
