### ISSUE TITLE
ultralytics的pytorch版本的yolov5项目的yolov5s.pt--onnx--paddle，在onnx2paddle时出现Inferred shape and existing shape differ in dimension 2: (416) vs (208)的错误

### ISSUE THREAD

**Issue by Alex-1997-Wzx** [PaddlePaddle/X2Paddle#381]
我的模型源文件是yolov5s.pt，使用的是github上的pytorch版本的yolov5的项目，链接附上：https://github.com/ultralytics/yolov5

我在进行pytorch转onnx的时候，是没有问题的，onnx使用的1.6.0，opset版本是11，最终成功生成onnx。使用的转换程序，是该项目提供的export.py，在models文件夹下。

但是在我使用x2paddle转换onnx 的时候，出现了错误，我的paddle版本是1.8，采用github上推荐的第一种方式安装的x2paddle。报错如下：初步看，好像是和shape相关的错误，我设置的模型输入是1*3*416*416，但是我不明白错误中提到的208是什么意思。而且当我在将pytorch转换成onnx的时候，如果将输入尺寸设置成1*3*640*640，那么错误中就会出现320，都刚好是416或者640的1/2。

希望各位帮我看一下这个应该怎么解决，谢谢啦！！！！！

E:\Python37\Scripts>x2paddle --framework=onnx --model=C:\Users\Alex\Desktop\ultralytics_yolov5_pytorch\models\yolov5s.onnx --save_dir=C:\Users\Alex\Desktop\ultralytics_yolov5_pytorch\models\ --onnx_opset=11
paddle.__version__ = 1.8.3
Now translating model from onnx to paddle.
model ir_version: 6, op version: 11
shape inferencing ...
Stopping at incomplete shape inference
(op_type:Slice, name:x2paddle_171): Inferred shape and existing shape differ in dimension 2: (416) vs (208)
Traceback (most recent call last):
  File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\decoder\onnx_shape_inference.py", line 1585, in infer_shapes
    in_mp)
  File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\decoder\onnx_shape_inference.py", line 1418, in _infer_impl
    self.dispatcher_[node.op_type](node)
  File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\decoder\onnx_shape_inference.py", line 1130, in _infer_Resize
    assert len(roi) == 2 * rank
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python37\Scripts\x2paddle-script.py", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==0.8.1', 'console_scripts', 'x2paddle')())
  File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\convert.py", line 269, in main
    onnx2paddle(args.model, args.save_dir, params_merge)
  File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\convert.py", line 184, in onnx2paddle
    model = ONNXDecoder(model_path)
  File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\decoder\onnx_decoder.py", line 367, in __init__
    self.graph = ONNXGraph(onnx_model)
  File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\decoder\onnx_decoder.py", line 143, in __init__
    onnx_model, fixed_input_shape=self.fixed_input_shape)
  File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\decoder\onnx_shape_inference.py", line 1595, in infer_shapes
    symbolic_shape_inference.out_mp_)
  File "E:\Python37\lib\site-packages\onnx\shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str)
RuntimeError: Inferred shape and existing shape differ in dimension 2: (416) vs (208)

**Comment by Channingss** [comment]
@Alex-1997-Wzx 这个报错是提示关于ONNX模型本身的问题，看上去是torch2onnx时shape指定不对。你需要在torch2onnx之前，确认下这个模型的输入shape是多少。导出后也可以用onnxruntime推理下该模型看是否可以成功run，来check下模型时候正确。

**Comment by Alex-1997-Wzx** [comment]
> @Alex-1997-Wzx 这个报错是提示关于ONNX模型本身的问题，看上去是torch2onnx时shape指定不对。你需要在torch2onnx之前，确认下这个模型的输入shape是多少。导出后也可以用onnxruntime推理下该模型看是否可以成功run，来check下模型时候正确。

我在onnxruntime上运行是没有问题的，而且该项目官方给的torch2onnx使用的shape也是1x3x416x416，所以我也不知道哪出了问题.

**Comment by Alex-1997-Wzx** [comment]
> @Alex-1997-Wzx 这个报错是提示关于ONNX模型本身的问题，看上去是torch2onnx时shape指定不对。你需要在torch2onnx之前，确认下这个模型的输入shape是多少。导出后也可以用onnxruntime推理下该模型看是否可以成功run，来check下模型时候正确。

我在torch2onnx时，可能由于某些算子的原因，必须得使用onnx-optset=11才能完全没有警告的通过，所以我选择的是11。但是在onnx2paddle的时候，x2paddle显示的是目前支持onnx-optset=9，并且报了错，所以是不是和支持的版本有关系，就不能用了。于是我在torch2onnx时，选择optset=9，在有警告的情况下生成onnx，此时进行onnx2paddle就不会报错。也就是我在torch2onnx的时候必须选择optset=9。。


E:\Python37\Scripts>x2paddle --framework=onnx --model=C:\Users\Alex\Desktop\ultralytics_yolov3_pytorch\yolov3-tiny.onnx --save_dir=C:\Users\Alex\Desktop\ultralytics_yolov3_pytorch\
paddle.__version__ = 1.8.3
Now translating model from onnx to paddle.
model ir_version: 6, op version: 11
shape inferencing ...
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 11, automatically treated as op_set: 9.
Total nodes: 77
Nodes converting ...
convert failed node:61, op_type is Slice
Traceback (most recent call last):
  File "E:\Python37\Scripts\x2paddle-script.py", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==0.8.1', 'console_scripts', 'x2paddle')())
  File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\convert.py", line 269, in main
    onnx2paddle(args.model, args.save_dir, params_merge)
  File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\convert.py", line 185, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\op_mapper\onnx2paddle\onnx_op_mapper.py", line 42, in __init__
    func(node)
  File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\op_mapper\onnx2paddle\opset9\opset.py", line 73, in run_mapping
    res = func(*args, **kwargs)
  File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\op_mapper\onnx2paddle\opset9\opset.py", line 841, in Slice
    assert steps == 1, "Only support convert op:Slice, which attribute:steps == 1"
AssertionError: Only support convert op:Slice, which attribute:steps == 1

**Comment by Channingss** [comment]
> > @Alex-1997-Wzx 这个报错是提示关于ONNX模型本身的问题，看上去是torch2onnx时shape指定不对。你需要在torch2onnx之前，确认下这个模型的输入shape是多少。导出后也可以用onnxruntime推理下该模型看是否可以成功run，来check下模型时候正确。
> 
> 我在torch2onnx时，可能由于某些算子的原因，必须得使用onnx-optset=11才能完全没有警告的通过，所以我选择的是11。但是在onnx2paddle的时候，x2paddle显示的是目前支持onnx-optset=9，并且报了错，所以是不是和支持的版本有关系，就不能用了。于是我在torch2onnx时，选择optset=9，在有警告的情况下生成onnx，此时进行onnx2paddle就不会报错。也就是我在torch2onnx的时候必须选择optset=9。。
> 
> E:\Python37\Scripts>x2paddle --framework=onnx --model=C:\Users\Alex\Desktop\ultralytics_yolov3_pytorch\yolov3-tiny.onnx --save_dir=C:\Users\Alex\Desktop\ultralytics_yolov3_pytorch
> paddle.**version** = 1.8.3
> Now translating model from onnx to paddle.
> model ir_version: 6, op version: 11
> shape inferencing ...
> shape inferenced.
> Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 11, automatically treated as op_set: 9.
> Total nodes: 77
> Nodes converting ...
> convert failed node:61, op_type is Slice
> Traceback (most recent call last):
> File "E:\Python37\Scripts\x2paddle-script.py", line 33, in
> sys.exit(load_entry_point('x2paddle==0.8.1', 'console_scripts', 'x2paddle')())
> File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\convert.py", line 269, in main
> onnx2paddle(args.model, args.save_dir, params_merge)
> File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\convert.py", line 185, in onnx2paddle
> mapper = ONNXOpMapper(model)
> File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\op_mapper\onnx2paddle\onnx_op_mapper.py", line 42, in **init**
> func(node)
> File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\op_mapper\onnx2paddle\opset9\opset.py", line 73, in run_mapping
> res = func(*args, **kwargs)
> File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\op_mapper\onnx2paddle\opset9\opset.py", line 841, in Slice
> assert steps == 1, "Only support convert op:Slice, which attribute:steps == 1"
> AssertionError: Only support convert op:Slice, which attribute:steps == 1

@Alex-1997-Wzx 您好，这边Slice的转换目前只支持steps为1，方便的话麻烦可以提供ONNX模型

**Comment by Alex-1997-Wzx** [comment]
好的，我把onnx模型发给你。我刚才发附件的时候，发送失败，说您那边有文件大小限制，我的onnx模型是28.5M，所以我应该通过什么方式发给你。




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "PaddlePaddle/X2Paddle"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 上午10:23
收件人:&nbsp;"PaddlePaddle/X2Paddle"<X2Paddle@noreply.github.com&gt;;
抄送:&nbsp;"王宗轩"<308117406@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [PaddlePaddle/X2Paddle] ultralytics的pytorch版本的yolov5项目的yolov5s.pt--onnx--paddle，在onnx2paddle时出现Inferred shape and existing shape differ in dimension 2: (416) vs (208)的错误 (#381)





   
@Alex-1997-Wzx 这个报错是提示关于ONNX模型本身的问题，看上去是torch2onnx时shape指定不对。你需要在torch2onnx之前，确认下这个模型的输入shape是多少。导出后也可以用onnxruntime推理下该模型看是否可以成功run，来check下模型时候正确。
  
我在torch2onnx时，可能由于某些算子的原因，必须得使用onnx-optset=11才能完全没有警告的通过，所以我选择的是11。但是在onnx2paddle的时候，x2paddle显示的是目前支持onnx-optset=9，并且报了错，所以是不是和支持的版本有关系，就不能用了。于是我在torch2onnx时，选择optset=9，在有警告的情况下生成onnx，此时进行onnx2paddle就不会报错。也就是我在torch2onnx的时候必须选择optset=9。。
 
E:\Python37\Scripts&gt;x2paddle --framework=onnx --model=C:\Users\Alex\Desktop\ultralytics_yolov3_pytorch\yolov3-tiny.onnx --save_dir=C:\Users\Alex\Desktop\ultralytics_yolov3_pytorch
 paddle.version = 1.8.3
 Now translating model from onnx to paddle.
 model ir_version: 6, op version: 11
 shape inferencing ...
 shape inferenced.
 Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 11, automatically treated as op_set: 9.
 Total nodes: 77
 Nodes converting ...
 convert failed node:61, op_type is Slice
 Traceback (most recent call last):
 File "E:\Python37\Scripts\x2paddle-script.py", line 33, in
 sys.exit(load_entry_point('x2paddle==0.8.1', 'console_scripts', 'x2paddle')())
 File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\convert.py", line 269, in main
 onnx2paddle(args.model, args.save_dir, params_merge)
 File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\convert.py", line 185, in onnx2paddle
 mapper = ONNXOpMapper(model)
 File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\op_mapper\onnx2paddle\onnx_op_mapper.py", line 42, in init
 func(node)
 File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\op_mapper\onnx2paddle\opset9\opset.py", line 73, in run_mapping
 res = func(*args, **kwargs)
 File "E:\Python37\lib\site-packages\x2paddle-0.8.1-py3.7.egg\x2paddle\op_mapper\onnx2paddle\opset9\opset.py", line 841, in Slice
 assert steps == 1, "Only support convert op:Slice, which attribute:steps == 1"
 AssertionError: Only support convert op:Slice, which attribute:steps == 1
  
@Alex-1997-Wzx 您好，这边Slice的转换目前只支持steps为1，方便的话麻烦可以提供ONNX模型

**Comment by Channingss** [comment]
@Alex-1997-Wzx 发我的个人邮箱：chen_lingchi@163.com不可以吗？或者百度网盘吧

**Comment by Channingss** [comment]
@Alex-1997-Wzx 我这边报错了好像是模型有点问题，请问模型md5是这个吗？
![image](https://user-images.githubusercontent.com/12471701/91303676-ed661b00-e7da-11ea-8bff-5e61c4f3a595.png)

**Comment by Alex-1997-Wzx** [comment]
> @Alex-1997-Wzx 我这边报错了好像是模型有点问题，请问模型md5是这个吗？
> ![image](https://user-images.githubusercontent.com/12471701/91303676-ed661b00-e7da-11ea-8bff-5e61c4f3a595.png)

![image](https://user-images.githubusercontent.com/54297321/91580511-ceed5480-e97f-11ea-838f-abc6f8e85dbf.png)
是的，md5就是这个

**Comment by Alex-1997-Wzx** [comment]
> > @Alex-1997-Wzx 我这边报错了好像是模型有点问题，请问模型md5是这个吗？
> > ![image](https://user-images.githubusercontent.com/12471701/91303676-ed661b00-e7da-11ea-8bff-5e61c4f3a595.png)
> 
> ![image](https://user-images.githubusercontent.com/54297321/91580511-ceed5480-e97f-11ea-838f-abc6f8e85dbf.png)
> 是的，md5就是这个

我已经对比过了，6449dee1537c2c0851316541f533ed74   md5就是这个

**Comment by Channingss** [comment]
@Alex-1997-Wzx 不好意思，问题解决有点晚了，这个提交https://github.com/PaddlePaddle/X2Paddle/pull/403 ，应该能解决您的需求，提示输入shape的时候，输入N跳过，
