### ISSUE TITLE
caffe->paddle报错

### ISSUE THREAD

**Issue by zhuguiqian** [PaddlePaddle/X2Paddle#424]
自己训练的两个网络转paddle报错，转onnx都是正常的。
下面是两个报错的信息
 error 信息1：
(paddle) zgq@ubuntu:~/paddle$ sh x2paddle.sh 
paddle.__version__ = 1.8.5
Now translating model from caffe to paddle.
Ignoring parameters for non-existent layer: snpc_conv
Total nodes: 66
Traceback (most recent call last):
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/x2paddle/core/op_mapper.py", line 142, in save_inference_model
    inputs, outputs = model.x2paddle_net()
  File "pd_feature_model/model_with_code/model.py", line 7, in x2paddle_net
    conv1_1_relu = fluid.layers.conv2d(data[0], filter_size=[3, 3], num_filters=16, stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, name='conv1_1', param_attr='conv1_1_weights', bias_attr='conv1_1_bias', act='relu')
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 2938, in conv2d
    "data_format": data_format,
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1971, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::ConvOp::ComputeOutputShape(paddle::framework::InferShapeContext*) const
3   paddle::operators::ConvOp::InferShape(paddle::framework::InferShapeContext*) const
4   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 2938, in conv2d
    "data_format": data_format,
  File "pd_feature_model/model_with_code/model.py", line 7, in x2paddle_net
    conv1_1_relu = fluid.layers.conv2d(data[0], filter_size=[3, 3], num_filters=16, stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, name='conv1_1', param_attr='conv1_1_weights', bias_attr='conv1_1_bias', act='relu')
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/x2paddle/core/op_mapper.py", line 142, in save_inference_model
    inputs, outputs = model.x2paddle_net()
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/x2paddle/convert.py", line 157, in caffe2paddle
    mapper.save_inference_model(save_dir, params_merge)
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/x2paddle/convert.py", line 299, in main
    args.caffe_proto, params_merge)
  File "/home/zgq/anaconda3/envs/paddle/bin/x2paddle", line 8, in <module>
    sys.exit(main())

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The input of Op(Conv) should be a 4-D or 5-D Tensor. But received: input's dimension is 3, input's shape is [1, 128, 128].
  [Hint: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.] at (/paddle/paddle/fluid/operators/conv_op.cc:59)
  [operator < conv2d > error]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zgq/anaconda3/envs/paddle/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/x2paddle/convert.py", line 299, in main
    args.caffe_proto, params_merge)
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/x2paddle/convert.py", line 157, in caffe2paddle
    mapper.save_inference_model(save_dir, params_merge)
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/x2paddle/core/op_mapper.py", line 197, in save_inference_model
    .format(py_code_dir))
Exception: Paddle code was saved in pd_feature_model/model_with_code/model.py, but seems there's wrong exist, please check model.py manually.

error信息2：
paddle.__version__ = 1.8.5
Now translating model from caffe to paddle.
Traceback (most recent call last):
  File "/home/zgq/anaconda3/envs/paddle/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/x2paddle/convert.py", line 299, in main
    args.caffe_proto, params_merge)
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/x2paddle/convert.py", line 152, in caffe2paddle
    model = CaffeDecoder(proto, weight, caffe_proto)
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/x2paddle/decoder/caffe_decoder.py", line 250, in __init__
    self.caffe_graph.build()
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/x2paddle/decoder/caffe_decoder.py", line 178, in build
    layers = self.filter_layers(layers)
  File "/home/zgq/anaconda3/envs/paddle/lib/python3.7/site-packages/x2paddle/decoder/caffe_decoder.py", line 107, in filter_layers
    assert layer.name not in filtered_layer_names
AssertionError

**Comment by SunAhong1993** [comment]
你好，方便提供2个模型到545510262@qq.com吗？我这边进行测试

**Comment by zhuguiqian** [comment]
> 545510262@qq.com

大佬，模型已经发给您，麻烦帮忙看下，多谢

**Comment by SunAhong1993** [comment]
> > [545510262@qq.com](mailto:545510262@qq.com)
> 
> 大佬，模型已经发给您，麻烦帮忙看下，多谢

你好，请先卸载现在的x2paddle，按照如下方式安装x2paddle后进行转换
```
pip uninstall x2paddle
git clone https://github.com/PaddlePaddle/X2Paddle.git
cd X2Paddle
python setup.py install
```
针对第一个模型：
![image](https://user-images.githubusercontent.com/48579383/98784605-56524c00-2436-11eb-92b7-7191ac09d169.png)
prototxt中Input的第二个dim应为3，否则caffe无法跑前向。
针对第二个模型：
![image](https://user-images.githubusercontent.com/48579383/98784768-90235280-2436-11eb-99d4-e4e3d431f198.png)
prototxt中的该layer应去除，由于输入pts已经被注释，否则caffe无法跑前向。

如有其他问题，后续可在该issue中继续反馈。

**Comment by zhuguiqian** [comment]
> 针对第一个模型：
> ![image](https://user-images.githubusercontent.com/48579383/98784605-56524c00-2436-11eb-92b7-7191ac09d169.png)
> prototxt中Input的第二个dim应为3，否则caffe无法跑前向。

输入必须是3通道的吗?
但是,我有用单通道的caffe模型转onnx后再转paddle,是可以转成功的.

**Comment by zhuguiqian** [comment]
> 针对第二个模型：
> ![image](https://user-images.githubusercontent.com/48579383/98784768-90235280-2436-11eb-99d4-e4e3d431f198.png)
> prototxt中的该layer应去除，由于输入pts已经被注释，否则caffe无法跑前向。

抱歉,重新train的网络忘记删loss了
但是我将loss层删掉后,还是会报这个错.

**Comment by SunAhong1993** [comment]
> > 针对第二个模型：
> > ![image](https://user-images.githubusercontent.com/48579383/98784768-90235280-2436-11eb-99d4-e4e3d431f198.png)
> > prototxt中的该layer应去除，由于输入pts已经被注释，否则caffe无法跑前向。
> 
> 抱歉,重新train的网络忘记删loss了
> 但是我将loss层删掉后,还是会报这个错.

这边测试过是没问题的，有使用
```
pip uninstall x2paddle
git clone https://github.com/PaddlePaddle/X2Paddle.git
cd X2Paddle
python setup.py install
```
有重新安装x2paddle吗？

**Comment by SunAhong1993** [comment]
> > 针对第一个模型：
> > ![image](https://user-images.githubusercontent.com/48579383/98784605-56524c00-2436-11eb-92b7-7191ac09d169.png)
> > prototxt中Input的第二个dim应为3，否则caffe无法跑前向。
> 
> 输入必须是3通道的吗?
> 但是,我有用单通道的caffe模型转onnx后再转paddle,是可以转成功的.

这参数的c_in是3通道的，caffe模型跑前向也需要改为3才跑的通。跑若不修改为3，跑caffe前向会报如下错误：
![image](https://user-images.githubusercontent.com/48579383/98911043-f2478a80-24fe-11eb-8325-598df3d39ba3.png)
caffe跑前向测试代码：
```
import caffe
import numpy as np
net = caffe.Net('quantes_new.prototxt','quantes_new.caffemodel',caffe.TEST)
input_layer = list(net.blobs.keys())[0]
inputs = {input_layer: np.random(1, 1, 224, 224)}
net.forward_all(**inputs)
```

**Comment by SunAhong1993** [comment]
> 单通道的caffe模型转onnx后再转paddle

你可以查看下转换后的模型的输入是否为3通道，caffe转paddle时会多判断模型是否跑的了前向。

**Comment by zhuguiqian** [comment]
> ```
> pip uninstall x2paddle
> git clone https://github.com/PaddlePaddle/X2Paddle.git
> cd X2Paddle
> python setup.py install
> ```
> 
> 有重新安装x2paddle吗？

之前没有uninstall, 现在重装后, 可以转了

**Comment by zhuguiqian** [comment]
> > 单通道的caffe模型转onnx后再转paddle
> 
> 你可以查看下转换后的模型的输入是否为3通道，caffe转paddle时会多判断模型是否跑的了前向。

![image](https://user-images.githubusercontent.com/7693110/98925483-00060b80-2511-11eb-9ac5-da7252e0df58.png)
转成就是单通道的,有用单通道输入跑过推理. 转成paddle后也用单通道输入跑过推理

**Comment by zhuguiqian** [comment]
> > 单通道的caffe模型转onnx后再转paddle
> 
> 你可以查看下转换后的模型的输入是否为3通道，caffe转paddle时会多判断模型是否跑的了前向。

邮箱给您发了一个只有一层卷积的单通道输入caffe模型,我这边可以转成功,您那边可以试一下

**Comment by SunAhong1993** [comment]
> > > 单通道的caffe模型转onnx后再转paddle
> > 
> > 
> > 你可以查看下转换后的模型的输入是否为3通道，caffe转paddle时会多判断模型是否跑的了前向。
> 
> 邮箱给您发了一个只有一层卷积的单通道输入caffe模型,我这边可以转成功,您那边可以试一下

已尝试过，后面提供的模型第一层卷积weight的shape是(1,1,1,1)（所以可以转换），quantes_new模型的第一层卷积的shape是(16, 3, 3, 3)（卷积weight的in_channel和输入的Channel不一致，所以无法跑前向）。你可以尝试跑caffe前向，是跑不通的，你可以查看下caffe2onnx是否对第一层卷积的weight进行了处理。

**Comment by zhuguiqian** [comment]
好的，多谢
