### ISSUE TITLE
检查OP是否在PaddleLite支持报错

### ISSUE THREAD

**Issue by Jorsen0** [PaddlePaddle/X2Paddle#433]
Traceback (most recent call last):
  File "/paddle/X2Paddle/tools/check_for_lite.py", line 7, in <module>
    fetch = urllib.urlretrieve(ops_h, "./_paddle_use_ops.h")
AttributeError: module 'six.moves.urllib' has no attribute 'urlretrieve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/urllib/request.py", line 1349, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/root/anaconda3/lib/python3.6/http/client.py", line 1287, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/anaconda3/lib/python3.6/http/client.py", line 1333, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/anaconda3/lib/python3.6/http/client.py", line 1282, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/anaconda3/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/root/anaconda3/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/root/anaconda3/lib/python3.6/http/client.py", line 1440, in connect
    super().connect()
  File "/root/anaconda3/lib/python3.6/http/client.py", line 952, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/root/anaconda3/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/root/anaconda3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/paddle/X2Paddle/tools/check_for_lite.py", line 9, in <module>
    fetch = urllib.request.urlretrieve(ops_h, "./_paddle_use_ops.h")
  File "/root/anaconda3/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/root/anaconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/root/anaconda3/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/root/anaconda3/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/root/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/root/anaconda3/lib/python3.6/urllib/request.py", line 1392, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/root/anaconda3/lib/python3.6/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

Process finished with exit code 1

使用工具中提供的代码检测op是否支持，结果报错找不到地址，这个需要怎么解决呢？

**Comment by jiangjiajun** [comment]
请问是反复执行都会出现上述错误吗？

当前你可以手动下载此文件 https://raw.githubusercontent.com/PaddlePaddle/Paddle-Lite/develop/lite/api/_paddle_use_ops.h
将其放至在执行check_for_lite.py的同级目录，再将check_for_lite.py改为如下代码即可

```
import sys
from paddle.fluid.framework import Program

ops = list()
with open("./_paddle_use_ops.h") as f:
    for line in f:
        if "USE_LITE_OP" in line:
            op = line.strip().split('(')[1].split(')')[0]
            ops.append(op)

model_file = sys.argv[1]
with open(model_file, 'rb') as f:
    program = Program.parse_from_string(f.read())

unsupported_ops = set()
for op in program.blocks[0].ops:
    if op.type not in ops:
        unsupported_ops.add(op.type)

nums = len(unsupported_ops)
if len(unsupported_ops) > 0:
    print("========= {} OPs are not supported in Paddle-Lite=========".format(
        nums))
    for op in unsupported_ops:
        print("========= {} ========".format(op))
else:
    print("\n========== Good News! ========")
    print("Good! All ops in this model are supported in Paddle-Lite!\n")
```

**Comment by Jorsen0** [comment]
> 请问是反复执行都会出现上述错误吗？
> 
> 当前你可以手动下载此文件 https://raw.githubusercontent.com/PaddlePaddle/Paddle-Lite/develop/lite/api/_paddle_use_ops.h
> 将其放至在执行check_for_lite.py的同级目录，再将check_for_lite.py改为如下代码即可
> 
> ```
> import sys
> from paddle.fluid.framework import Program
> 
> ops = list()
> with open("./_paddle_use_ops.h") as f:
>     for line in f:
>         if "USE_LITE_OP" in line:
>             op = line.strip().split('(')[1].split(')')[0]
>             ops.append(op)
> 
> model_file = sys.argv[1]
> with open(model_file, 'rb') as f:
>     program = Program.parse_from_string(f.read())
> 
> unsupported_ops = set()
> for op in program.blocks[0].ops:
>     if op.type not in ops:
>         unsupported_ops.add(op.type)
> 
> nums = len(unsupported_ops)
> if len(unsupported_ops) > 0:
>     print("========= {} OPs are not supported in Paddle-Lite=========".format(
>         nums))
>     for op in unsupported_ops:
>         print("========= {} ========".format(op))
> else:
>     print("\n========== Good News! ========")
>     print("Good! All ops in this model are supported in Paddle-Lite!\n")
> ```

你好，您所给的链接无法打开呢

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/api/_paddle_use_ops.h 那下载此链接文件文件
