### ISSUE TITLE
openpose的caffe模型转换时报错

### ISSUE THREAD

**Issue by ZhangXinNan** [PaddlePaddle/X2Paddle#439]
参考链接：https://cloud.tencent.com/developer/article/1748267

报错信息：
(py36_pose) zhangxin@zx:~/github/X2Paddle$ x2paddle --framework=caffe \
>     --prototxt=/home/zhangxin/github/openpose-CMU/models/hand/pose_deploy.prototxt \
>     --weight=/home/zhangxin/github/openpose-CMU/models/hand/pose_iter_102000.caffemodel \
>     --save_dir=/home/zhangxin/gitlab_md/pose-service/data/hand \
>     --params_merge
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;paddle.__version__ = 1.8.5
Now translating model from caffe to paddle.
Traceback (most recent call last):
  File "/home/zhangxin/miniconda3/envs/py36_pose/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==0.8.8', 'console_scripts', 'x2paddle')())
  File "/home/zhangxin/miniconda3/envs/py36_pose/lib/python3.6/site-packages/x2paddle-0.8.8-py3.6.egg/x2paddle/convert.py", line 275, in main
    args.caffe_proto, params_merge)
  File "/home/zhangxin/miniconda3/envs/py36_pose/lib/python3.6/site-packages/x2paddle-0.8.8-py3.6.egg/x2paddle/convert.py", line 146, in caffe2paddle
    model = CaffeDecoder(proto, weight, caffe_proto)
  File "/home/zhangxin/miniconda3/envs/py36_pose/lib/python3.6/site-packages/x2paddle-0.8.8-py3.6.egg/x2paddle/decoder/caffe_decoder.py", line 248, in __init__
    self.load_using_pb()
  File "/home/zhangxin/miniconda3/envs/py36_pose/lib/python3.6/site-packages/x2paddle-0.8.8-py3.6.egg/x2paddle/decoder/caffe_decoder.py", line 256, in load_using_pb
    data.MergeFromString(open(self.model_path, 'rb').read())
google.protobuf.message.DecodeError: Error parsing message

**Comment by SunAhong1993** [comment]
> 参考链接：https://cloud.tencent.com/developer/article/1748267
> 
> 报错信息：
> (py36_pose) zhangxin@zx:~/github/X2Paddle$ x2paddle --framework=caffe \
> 
> > ```
> > --prototxt=/home/zhangxin/github/openpose-CMU/models/hand/pose_deploy.prototxt \
> > --weight=/home/zhangxin/github/openpose-CMU/models/hand/pose_iter_102000.caffemodel \
> > --save_dir=/home/zhangxin/gitlab_md/pose-service/data/hand \
> > --params_merge
> > ```
> 
> TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
> Suggestions:
> 
> 1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
> 2. Configure TensorRT dynamic library environment variables as follows:
> 
> * Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
> * Windows: set PATH by `set PATH=XXX;paddle.**version** = 1.8.5
>   Now translating model from caffe to paddle.
>   Traceback (most recent call last):
>   File "/home/zhangxin/miniconda3/envs/py36_pose/bin/x2paddle", line 33, in 
>   sys.exit(load_entry_point('x2paddle==0.8.8', 'console_scripts', 'x2paddle')())
>   File "/home/zhangxin/miniconda3/envs/py36_pose/lib/python3.6/site-packages/x2paddle-0.8.8-py3.6.egg/x2paddle/convert.py", line 275, in main
>   args.caffe_proto, params_merge)
>   File "/home/zhangxin/miniconda3/envs/py36_pose/lib/python3.6/site-packages/x2paddle-0.8.8-py3.6.egg/x2paddle/convert.py", line 146, in caffe2paddle
>   model = CaffeDecoder(proto, weight, caffe_proto)
>   File "/home/zhangxin/miniconda3/envs/py36_pose/lib/python3.6/site-packages/x2paddle-0.8.8-py3.6.egg/x2paddle/decoder/caffe_decoder.py", line 248, in **init**
>   self.load_using_pb()
>   File "/home/zhangxin/miniconda3/envs/py36_pose/lib/python3.6/site-packages/x2paddle-0.8.8-py3.6.egg/x2paddle/decoder/caffe_decoder.py", line 256, in load_using_pb
>   data.MergeFromString(open(self.model_path, 'rb').read())
>   google.protobuf.message.DecodeError: Error parsing message

可以使用`pip list`查看下protobuf的版本，如果protobuf版本低于3.6.0，请重新安装protobuf，安装命令：
```
pip uninstall protobuf
pip install protobuf==3.6.0
```
