### ISSUE TITLE
module 'paddle' has no attribute 'save'

### ISSUE THREAD

**Issue by zhangjf2018** [PaddlePaddle/X2Paddle#456]
['1', '6', '0']
Now translating model from pytorch to paddle.
Model optimizing ...
trace_fc_fuse_pass done!
Model optimized.
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    input_examples=[torch.tensor(input_data)])
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/x2paddle-1.0.0rc0-py3.7.egg/x2paddle/convert.py", line 231, in pytorch2paddle
    mapper.paddle_graph.gen_model(save_dir, jit_type=jit_type)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/x2paddle-1.0.0rc0-py3.7.egg/x2paddle/core/program.py", line 240, in gen_model
    self.gen_dygraph_model(save_dir, jit_type)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/x2paddle-1.0.0rc0-py3.7.egg/x2paddle/core/program.py", line 280, in gen_dygraph_model
    self.dump_dygraph_parameter(save_dir)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/x2paddle-1.0.0rc0-py3.7.egg/x2paddle/core/program.py", line 632, in dump_dygraph_parameter
    paddle.save(self.parameters, save_path)
AttributeError: module 'paddle' has no attribute 'save'

**Comment by SunAhong1993** [comment]
Your PaddlePaddle version is 1.6.0. The PaddlePaddle version must be 2.0-rc or develop when converting the PyTorch to PaddlePaddle. You can get the corresponding version in https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/install/Tables.html#ciwhls .

**Comment by zhangjf2018** [comment]
pytorch -> onnx -> paddlepaddle ? 这样操作也没问题吧？
paddlle version is 1.8.5

onxx -> paddlepaddle 也是要2.0.0以上

**Comment by SunAhong1993** [comment]
> pytorch -> onnx -> paddlepaddle ? 这样操作也没问题吧？
> paddlle version is 1.8.5
> 
> onxx -> paddlepaddle 也是要2.0.0以上

没问题的

**Comment by SunAhong1993** [comment]
> pytorch -> onnx -> paddlepaddle ? 这样操作也没问题吧？
> paddlle version is 1.8.5
> 
> onxx -> paddlepaddle 也是要2.0.0以上

目前的develop版本需要 2.0rc，你使用release-0.9则1.8.5即可
