### ISSUE TITLE
onnx to paddlepaddle operator < nearest_interp_v2 > error

### ISSUE THREAD

**Issue by zhangjf2018** [PaddlePaddle/X2Paddle#459]
paddle.__version__ = 2.0.0-rc0
Now translating model from onnx to paddle.
model ir_version: 6, op version: 12
shape inferencing ...
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 12, automatically treated as op_set: 9.
Total nodes: 360
Nodes converting ...
Converting node 772 ...     
Nodes converted.
Exporting inference model from python code ('/home/ai/Desktop/workspace/pytorch_paddle/pd_model/x2paddle_code.py')... 

W1215 15:07:35.616997 437839 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.0, Runtime API Version: 10.2
W1215 15:07:35.659567 437839 device_context.cc:346] device: 0, cuDNN Version: 7.6.
/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
Fail to generate inference model! Problem happend while export inference model from python code '/home/ai/Desktop/workspace/pytorch_paddle/pd_model/x2paddle_code.py';

===================Error Information===============
Traceback (most recent call last):
  File "/home/ai/anaconda3/envs/paddletest/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.0rc0', 'console_scripts', 'x2paddle')())
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/x2paddle-1.0.0rc0-py3.7.egg/x2paddle/convert.py", line 296, in main
    onnx2paddle(args.model, args.save_dir, args.paddle_type, params_merge)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/x2paddle-1.0.0rc0-py3.7.egg/x2paddle/convert.py", line 190, in onnx2paddle
    mapper.paddle_graph.gen_model(save_dir)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/x2paddle-1.0.0rc0-py3.7.egg/x2paddle/core/program.py", line 240, in gen_model
    self.gen_dygraph_model(save_dir, jit_type)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/x2paddle-1.0.0rc0-py3.7.egg/x2paddle/core/program.py", line 298, in gen_dygraph_model
    raise e
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/x2paddle-1.0.0rc0-py3.7.egg/x2paddle/core/program.py", line 294, in gen_dygraph_model
    self.dygraph2static(save_dir, input_shapes, input_types)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/x2paddle-1.0.0rc0-py3.7.egg/x2paddle/core/program.py", line 655, in dygraph2static
    paddle.jit.save(static_model, osp.join(save_dir, "inference_model/model"))
  File "<decorator-gen-54>", line 2, in save
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
    return func(*args, **kwargs)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 622, in save
    concrete_program = layer.forward.concrete_program
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 445, in concrete_program
    concrete_program, _ = self.get_concrete_program(*input_spec)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 385, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 656, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 647, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-46>", line 2, in from_func_spec
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
    return func(*args, **kwargs)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 603, in from_func_spec
    outputs = static_func(*inputs)
  File "/tmp/tmp3so9tw_m.py", line 344, in forward
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 485, in interpolate
    attrs=attrs)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2917, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/ai/anaconda3/envs/paddletest/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2123, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const
1   paddle::operators::InterpolateV2Op::InferShape(paddle::framework::InferShapeContext*) const
2   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
3   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Scale's shape must be 2 or 1, but got shape = 4 .
  [Hint: Expected scale_tensor[0] == 2 || scale_tensor[0] == 1 == true, but received scale_tensor[0] == 2 || scale_tensor[0] == 1:0 != true:1.] (at /paddle/paddle/fluid/operators/interpolate_v2_op.cc:162)
  [operator < nearest_interp_v2 > error]

**Comment by SunAhong1993** [comment]
> self.desc.infer_shape(self.block.desc)

当前已经转换成动态图代码和对应参数，但是动转静过程中可能由于有shape为-1的情况无法动转静（保存成inference model），所以您有以下2种选择：
1. 使用代码+模型即可进行预测。
2. 转换时设置--paddle_type static直接转换静态图形式。

**Comment by youngstu** [comment]
File "best_pd_model/model_with_code/x2paddle_model.py", line 489, in x2paddle_net
    x2paddle_811 = paddle.nn.functional.interpolate(x=x2paddle_806, scale_factor=x2paddle_1361, align_corners=False, mode='nearest', align_mode=1)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 481, in interpolate
    helper.append_op(
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2911, in append_op
    op = Operator(
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2123, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const
1   paddle::operators::InterpolateV2Op::InferShape(paddle::framework::InferShapeContext*) const
2   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
3   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Scale's shape must be 2 or 1, but got shape = 4 .
  [Hint: Expected scale_tensor[0] == 2 || scale_tensor[0] == 1 == true, but received scale_tensor[0] == 2 || scale_tensor[0] == 1:0 != true:1.] (at /paddle/paddle/fluid/operators/interpolate_v2_op.cc:162)
  [operator < nearest_interp_v2 > error]

我也有同样的问题，我是直接转static报错如上
