### ISSUE TITLE
onnx to paddlepaddle operator < nearest_interp_v2 > error 

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/X2Paddle#470]
File "best_pd_model/model_with_code/x2paddle_model.py", line 489, in x2paddle_net
    x2paddle_811 = paddle.nn.functional.interpolate(x=x2paddle_806, scale_factor=x2paddle_1361, align_corners=False, mode='nearest', align_mode=1)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 481, in interpolate
    helper.append_op(
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2911, in append_op
    op = Operator(
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.7/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2123, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const
1   paddle::operators::InterpolateV2Op::InferShape(paddle::framework::InferShapeContext*) const
2   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
3   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Scale's shape must be 2 or 1, but got shape = 4 .
  [Hint: Expected scale_tensor[0] == 2 || scale_tensor[0] == 1 == true, but received scale_tensor[0] == 2 || scale_tensor[0] == 1:0 != true:1.] (at /paddle/paddle/fluid/operators/interpolate_v2_op.cc:162)
  [operator < nearest_interp_v2 > error]

我也是同样的问题，直接转static和dygraph都不行。转static报错如上

**Comment by SunAhong1993** [comment]
这边问题已经修复，可按照如下方式重新安装下X2Paddle：
```
pip uninstall x2paddle
git clone https://github.com/PaddlePaddle/X2Paddle.git -b onnx
cd X2Paddle
pythoon setup.py install
```
