### ISSUE TITLE
你好，一个pytorch模型转paddle的过程中， 1 OPs are not supported yet

### ISSUE THREAD

**Issue by David20160511** [PaddlePaddle/X2Paddle#473]
你好，我在使用x2paddle把dbface的模型dbface.pth转成paddle的过程中报错，报错信息如下：

load model: ../../model/dbface.pth
['1', '7', '0']
Now translating model from pytorch to paddle.
Traceback (most recent call last):
  File "E:/github_cv/DBFace-master/mycode/pytorch2paddle/convert_code_dbface.py", line 31, in <module>
    input_examples=[torch.tensor(input_data)])
  File "D:\Anaconda3\envs\pytorch_env\lib\site-packages\x2paddle\convert.py", line 233, in pytorch2paddle
    mapper = PyTorchOpMapper(model)
  File "D:\Anaconda3\envs\pytorch_env\lib\site-packages\x2paddle\op_mapper\dygraph\pytorch2paddle\pytorch_op_mapper.py", line 42, in __init__
    raise Exception("Model is not supported yet.")
Exception: Model is not supported yet.

========= 1 OPs are not supported yet ===========
========== aten::upsample_nearest2d ============

我查了X2Paddle支持OP列表，aten::upsample_nearest2d现在不支持，这个不常用吗，以后会支持吗？

**Comment by SunAhong1993** [comment]
> dbface

**Comment by SunAhong1993** [comment]
> 你好，我在使用x2paddle把dbface的模型dbface.pth转成paddle的过程中报错，报错信息如下：
> 
> load model: ../../model/dbface.pth
> ['1', '7', '0']
> Now translating model from pytorch to paddle.
> Traceback (most recent call last):
> File "E:/github_cv/DBFace-master/mycode/pytorch2paddle/convert_code_dbface.py", line 31, in
> input_examples=[torch.tensor(input_data)])
> File "D:\Anaconda3\envs\pytorch_env\lib\site-packages\x2paddle\convert.py", line 233, in pytorch2paddle
> mapper = PyTorchOpMapper(model)
> File "D:\Anaconda3\envs\pytorch_env\lib\site-packages\x2paddle\op_mapper\dygraph\pytorch2paddle\pytorch_op_mapper.py", line 42, in **init**
> raise Exception("Model is not supported yet.")
> Exception: Model is not supported yet.
> 
> ========= 1 OPs are not supported yet ===========
> ========== aten::upsample_nearest2d ============
> 
> 我查了X2Paddle支持OP列表，aten::upsample_nearest2d现在不支持，这个不常用吗，以后会支持吗？

近期将支持这个op，请问您需要转换的是 https://github.com/dlunion/DBFace 这个repo吗？这边支持后会回复您。

**Comment by SunAhong1993** [comment]
> 你好，我在使用x2paddle把dbface的模型dbface.pth转成paddle的过程中报错，报错信息如下：
> 
> load model: ../../model/dbface.pth
> ['1', '7', '0']
> Now translating model from pytorch to paddle.
> Traceback (most recent call last):
> File "E:/github_cv/DBFace-master/mycode/pytorch2paddle/convert_code_dbface.py", line 31, in
> input_examples=[torch.tensor(input_data)])
> File "D:\Anaconda3\envs\pytorch_env\lib\site-packages\x2paddle\convert.py", line 233, in pytorch2paddle
> mapper = PyTorchOpMapper(model)
> File "D:\Anaconda3\envs\pytorch_env\lib\site-packages\x2paddle\op_mapper\dygraph\pytorch2paddle\pytorch_op_mapper.py", line 42, in **init**
> raise Exception("Model is not supported yet.")
> Exception: Model is not supported yet.
> 
> ========= 1 OPs are not supported yet ===========
> ========== aten::upsample_nearest2d ============
> 
> 我查了X2Paddle支持OP列表，aten::upsample_nearest2d现在不支持，这个不常用吗，以后会支持吗？

这边已经支持aten::upsample_nearest2d，你可以拉取分支代码，重新安装X2Paddle并进行转换，重装方式为：
```
pip uninstall x2paddle
git clone https://github.com/PaddlePaddle/X2Paddle.git -b pytorch
cd X2Paddle
python setup.py install
```
