### ISSUE TITLE
onnx2paddle算子不支持

### ISSUE THREAD

**Issue by czy1747** [PaddlePaddle/X2Paddle#475]
ONNX模型转换至PaddlePaddle，x2paddle==1.0.0rc0

模型来源：tensorflow pb文件转onnx而来 

详细情况见模型链接：
链接：https://pan.baidu.com/s/14Dp95xtUWdqrVDoHPndbCw 
提取码：zcan 

想把模型转换成paddle格式使用相关的推理功能，十分感谢！

![2021-01-01 22-29-44 的屏幕截图](https://user-images.githubusercontent.com/37530610/103471935-df945800-4dc1-11eb-9baf-87486e5a20ed.png)

**Comment by SunAhong1993** [comment]
当前动态图中刚已经新增这几个op的支持，稍后测试后会提PR，但是Pad的pad参数是一个tensor，paddle暂不支持，可否降低onnx协议进行转换（opset<11），同时将新的onnx模型提供给我们进行测试。

**Comment by SunAhong1993** [comment]
> 当前动态图中刚已经新增这几个op的支持，稍后测试后会提PR，但是Pad的pad参数是一个tensor，paddle暂不支持，可否降低onnx协议进行转换（opset<11），同时将新的onnx模型提供给我们进行测试。

尝试了下tf2onnx的转换，由于pad的原因只能使用opset11；之后又尝试使用了tf直接转换，但是BatchToSpaceND和SpaceToBatchND在Paddle中无对应实现，可否在代码中规避掉这2个op的使用（可能出现在tf.image.extract_pathches）

**Comment by czy1747** [comment]
（1）十分感谢您的回复和尝试
（2）这些转换方式，包括onnx opset以及pb转换之前也都试过了，最终不能转换，结论和您说的一样
（3）BatchToSpaceND和SpaceToBatchND 是由于使用了tf.nn.atrous_conv2d的api导致，onnx的PAD也是因为用了tf.nn.atrous_conv2d。可以将tf.nn.atrous_conv2d对应的组合算子，一起替换成paddle支持的算子吗？不然的话tf网络里面有空洞卷积不就转不了了
（4）新增的算子合并后请告知一下，我再试试，谢谢啦

**Comment by SunAhong1993** [comment]
> （1）十分感谢您的回复和尝试
> （2）这些转换方式，包括onnx opset以及pb转换之前也都试过了，最终不能转换，结论和您说的一样
> （3）BatchToSpaceND和SpaceToBatchND 是由于使用了tf.nn.atrous_conv2d的api导致，onnx的PAD也是因为用了tf.nn.atrous_conv2d。可以将tf.nn.atrous_conv2d对应的组合算子，一起替换成paddle支持的算子吗？不然的话tf网络里面有空洞卷积不就转不了了
> （4）新增的算子合并后请告知一下，我再试试，谢谢啦

目前该模型已经支持，可重装下X2Paddle进行转换，重装方式为：
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git -b onnx
cd X2Paddle
python setup.py install
```
修改的PR详见https://github.com/PaddlePaddle/X2Paddle/pull/479

**Comment by czy1747** [comment]
十分感谢，安装了您提供的x2paddle后，似乎还有点问题
(onnx) root@5ff032f73f34f2d4a631ca71:/data-output/ner# x2paddle --framework=onnx --model=bert6.onnx --save_dir=./bert6_paddle --paddle_type dygraph
paddle.__version__ = 2.0.0-rc1
Now translating model from onnx to paddle.
model ir_version: 6, op version: 11
skip op 101: embedding/bert/encoder/layer_0/attention/self/Softmax:0 -> Dropout -> Dropout__34:0
skip op 129: embedding/bert/encoder/layer_0/output/dense/BiasAdd:0 -> Dropout -> Dropout__36:0
skip op 164: embedding/bert/encoder/layer_1/attention/output/dense/BiasAdd:0 -> Dropout -> Dropout__38:0
skip op 216: embedding/bert/encoder/layer_2/attention/self/Softmax:0 -> Dropout -> Dropout__40:0
skip op 244: embedding/bert/encoder/layer_2/output/dense/BiasAdd:0 -> Dropout -> Dropout__42:0
skip op 279: embedding/bert/encoder/layer_3/attention/output/dense/BiasAdd:0 -> Dropout -> Dropout__44:0
skip op 331: embedding/bert/encoder/layer_4/attention/self/Softmax:0 -> Dropout -> Dropout__46:0
skip op 359: embedding/bert/encoder/layer_4/output/dense/BiasAdd:0 -> Dropout -> Dropout__48:0
skip op 394: embedding/bert/encoder/layer_5/attention/output/dense/BiasAdd:0 -> Dropout -> Dropout__50:0
skip op 561: embedding/dense/Relu:0 -> Dropout -> Dropout__52:0
Unknown shape for input tensor[tensor name: 'x2paddle_input_x_word_0'] -> shape: ['unk__931', 'unk__932'], Please define shape of input here,
Note:you can use visualization tools like Netron to check input shape.
Shape of Input(e.g. -1,3,224,224), enter 'N' to skip: -1,128
Unknown shape for input tensor[tensor name: 'x2paddle_input_mask_0'] -> shape: ['unk__933', 'unk__934'], Please define shape of input here,
Note:you can use visualization tools like Netron to check input shape.
Shape of Input(e.g. -1,3,224,224), enter 'N' to skip: -1,128
shape inferencing ...
Stopping at incomplete shape inference at Concat: x2paddle_idcnn_concat_0
node inputs:
name: "x2paddle_idcnn_atrous_conv_layer_2_Relu_0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "floor(Reshape639_o0__d0*Reshape639_o0__d1*Reshape639_o0__d2*Reshape639_o0__d3*Reshape639_o0__d4*Reshape639_o0__d5/(512*(2*floor(Pad609_o0__d2/2) - 4)*floor(Pad609_o0__d1/2)))"
      }
      dim {
        dim_param: "Slice642_o0__d1"
      }
      dim {
        dim_param: "Slice642_o0__d2"
      }
      dim {
        dim_value: 256
      }
    }
  }
}

name: "x2paddle_idcnn_atrous_conv_layer_2_1_Relu_0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "floor(Reshape730_o0__d0*Reshape730_o0__d1*Reshape730_o0__d2*Reshape730_o0__d3*Reshape730_o0__d4*Reshape730_o0__d5/(512*(2*floor(Pad700_o0__d2/2) - 4)*floor(Pad700_o0__d1/2)))"
      }
      dim {
        dim_param: "Slice733_o0__d1"
      }
      dim {
        dim_param: "Slice733_o0__d2"
      }
      dim {
        dim_value: 256
      }
    }
  }
}

node outputs:
name: "x2paddle_idcnn_concat_0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
      }
      dim {
      }
      dim {
      }
      dim {
        dim_value: 512
      }
    }
  }
}

!!!!!!!!!!
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 11, automatically treated as op_set: 9.
Total nodes: 745
Nodes converting ...
Converting node 916 ...
Nodes converted.
Exporting inference model from python code ('/data-output/ner/bert6_paddle/x2paddle_code.py')...

W0108 10:48:35.278515  4918 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.1
W0108 10:48:35.283311  4918 device_context.cc:330] device: 0, cuDNN Version: 7.6.
/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/layers/math_op_patch.py:297: UserWarning: /tmp/tmpons6n8mm.py:24
The behavior of expression A == B has been unified with equal(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use equal(X, Y, axis=0) instead of A == B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
Fail to generate inference model! Problem happend while export inference model from python code '/data-output/ner/bert6_paddle/x2paddle_code.py';

===================Error Information===============
Traceback (most recent call last):
  File "/opt/conda/envs/onnx/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')())
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 288, in main
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 189, in onnx2paddle
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 243, in gen_model
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 307, in gen_dygraph_model
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 303, in gen_dygraph_model
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 671, in dygraph2static
  File "<decorator-gen-60>", line 2, in save
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/jit.py", line 680, in save
    concrete_program = static_func.concrete_program
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 461, in concrete_program
    concrete_program, _ = self.get_concrete_program(*input_spec)
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 684, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 675, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-58>", line 2, in from_func_spec
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 631, in from_func_spec
    error_data.raise_new_exception()
  File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 186, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "./bert6_paddle/x2paddle_code.py", line 976, in forward (* user code *)
        x2paddle_idcnn_atrous_conv_layer_2_convolution_SpaceToBatchND_pad__529_0 = paddle.nn.functional.pad(x=x2paddle_idcnn_atrous_conv_layer_2_convolution_SpaceToBatchND_cast__523_0, mode='constant', pad=[1, 0, 0, 0])
    File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/nn/functional/common.py", line 1277, in pad
        ], "input tesor dimension must be in [3, 4, 5] but got {}".format(x_dim)
    AssertionError: input tesor dimension must be in [3, 4, 5] but got 2

**Comment by SunAhong1993** [comment]
> 十分感谢，安装了您提供的x2paddle后，似乎还有点问题
> (onnx) root@5ff032f73f34f2d4a631ca71:/data-output/ner# x2paddle --framework=onnx --model=bert6.onnx --save_dir=./bert6_paddle --paddle_type dygraph
> paddle.**version** = 2.0.0-rc1
> Now translating model from onnx to paddle.
> model ir_version: 6, op version: 11
> skip op 101: embedding/bert/encoder/layer_0/attention/self/Softmax:0 -> Dropout -> Dropout__34:0
> skip op 129: embedding/bert/encoder/layer_0/output/dense/BiasAdd:0 -> Dropout -> Dropout__36:0
> skip op 164: embedding/bert/encoder/layer_1/attention/output/dense/BiasAdd:0 -> Dropout -> Dropout__38:0
> skip op 216: embedding/bert/encoder/layer_2/attention/self/Softmax:0 -> Dropout -> Dropout__40:0
> skip op 244: embedding/bert/encoder/layer_2/output/dense/BiasAdd:0 -> Dropout -> Dropout__42:0
> skip op 279: embedding/bert/encoder/layer_3/attention/output/dense/BiasAdd:0 -> Dropout -> Dropout__44:0
> skip op 331: embedding/bert/encoder/layer_4/attention/self/Softmax:0 -> Dropout -> Dropout__46:0
> skip op 359: embedding/bert/encoder/layer_4/output/dense/BiasAdd:0 -> Dropout -> Dropout__48:0
> skip op 394: embedding/bert/encoder/layer_5/attention/output/dense/BiasAdd:0 -> Dropout -> Dropout__50:0
> skip op 561: embedding/dense/Relu:0 -> Dropout -> Dropout__52:0
> Unknown shape for input tensor[tensor name: 'x2paddle_input_x_word_0'] -> shape: ['unk__931', 'unk__932'], Please define shape of input here,
> Note:you can use visualization tools like Netron to check input shape.
> Shape of Input(e.g. -1,3,224,224), enter 'N' to skip: -1,128
> Unknown shape for input tensor[tensor name: 'x2paddle_input_mask_0'] -> shape: ['unk__933', 'unk__934'], Please define shape of input here,
> Note:you can use visualization tools like Netron to check input shape.
> Shape of Input(e.g. -1,3,224,224), enter 'N' to skip: -1,128
> shape inferencing ...
> Stopping at incomplete shape inference at Concat: x2paddle_idcnn_concat_0
> node inputs:
> name: "x2paddle_idcnn_atrous_conv_layer_2_Relu_0"
> type {
> tensor_type {
> elem_type: 1
> shape {
> dim {
> dim_param: "floor(Reshape639_o0__d0_Reshape639_o0__d1_Reshape639_o0__d2_Reshape639_o0__d3_Reshape639_o0__d4_Reshape639_o0__d5/(512_(2*floor(Pad609_o0__d2/2) - 4)*floor(Pad609_o0__d1/2)))"
> }
> dim {
> dim_param: "Slice642_o0__d1"
> }
> dim {
> dim_param: "Slice642_o0__d2"
> }
> dim {
> dim_value: 256
> }
> }
> }
> }
> 
> name: "x2paddle_idcnn_atrous_conv_layer_2_1_Relu_0"
> type {
> tensor_type {
> elem_type: 1
> shape {
> dim {
> dim_param: "floor(Reshape730_o0__d0_Reshape730_o0__d1_Reshape730_o0__d2_Reshape730_o0__d3_Reshape730_o0__d4_Reshape730_o0__d5/(512_(2*floor(Pad700_o0__d2/2) - 4)*floor(Pad700_o0__d1/2)))"
> }
> dim {
> dim_param: "Slice733_o0__d1"
> }
> dim {
> dim_param: "Slice733_o0__d2"
> }
> dim {
> dim_value: 256
> }
> }
> }
> }
> 
> node outputs:
> name: "x2paddle_idcnn_concat_0"
> type {
> tensor_type {
> elem_type: 1
> shape {
> dim {
> }
> dim {
> }
> dim {
> }
> dim {
> dim_value: 512
> }
> }
> }
> }
> 
> !!!!!!!!!!
> shape inferenced.
> Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 11, automatically treated as op_set: 9.
> Total nodes: 745
> Nodes converting ...
> Converting node 916 ...
> Nodes converted.
> Exporting inference model from python code ('/data-output/ner/bert6_paddle/x2paddle_code.py')...
> 
> W0108 10:48:35.278515 4918 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.1
> W0108 10:48:35.283311 4918 device_context.cc:330] device: 0, cuDNN Version: 7.6.
> /opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/layers/math_op_patch.py:297: UserWarning: /tmp/tmpons6n8mm.py:24
> The behavior of expression A == B has been unified with equal(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use equal(X, Y, axis=0) instead of A == B. This transitional warning will be dropped in the future.
> op_type, op_type, EXPRESSION_MAP[method_name]))
> Fail to generate inference model! Problem happend while export inference model from python code '/data-output/ner/bert6_paddle/x2paddle_code.py';
> 
> ===================Error Information===============
> Traceback (most recent call last):
> File "/opt/conda/envs/onnx/bin/x2paddle", line 33, in
> sys.exit(load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')())
> File "/opt/conda/envs/onnx/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 288, in main
> File "/opt/conda/envs/onnx/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 189, in onnx2paddle
> File "/opt/conda/envs/onnx/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 243, in gen_model
> File "/opt/conda/envs/onnx/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 307, in gen_dygraph_model
> File "/opt/conda/envs/onnx/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 303, in gen_dygraph_model
> File "/opt/conda/envs/onnx/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 671, in dygraph2static
> File "", line 2, in save
> File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in **impl**
> return wrapped_func(*args, **kwargs)
> File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 38, in **impl**
> return func(*args, **kwargs)
> File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/jit.py", line 680, in save
> concrete_program = static_func.concrete_program
> File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 461, in concrete_program
> concrete_program, _ = self.get_concrete_program(*input_spec)
> File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
> concrete_program, partial_program_layer = self._program_cache[cache_key]
> File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 684, in **getitem**
> self._caches[item] = self._build_once(item)
> File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 675, in _build_once class_instance=cache_key.class_instance) File "", line 2, in from_func_spec File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in **impl** return wrapped_func(*args, **kwargs) File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 38, in **impl** return func(*args, **kwargs) File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 631, in from_func_spec error_data.raise_new_exception() File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 186, in raise_new_exception six.exec_("raise new_exception from None")
> File "", line 1, in
> AssertionError: In transformed code:
> 
> ```
> File "./bert6_paddle/x2paddle_code.py", line 976, in forward (* user code *)
>     x2paddle_idcnn_atrous_conv_layer_2_convolution_SpaceToBatchND_pad__529_0 = paddle.nn.functional.pad(x=x2paddle_idcnn_atrous_conv_layer_2_convolution_SpaceToBatchND_cast__523_0, mode='constant', pad=[1, 0, 0, 0])
> File "/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/nn/functional/common.py", line 1277, in pad
>     ], "input tesor dimension must be in [3, 4, 5] but got {}".format(x_dim)
> AssertionError: input tesor dimension must be in [3, 4, 5] but got 2
> ```

这边paddle有个bug，你可以先注释掉/opt/conda/envs/onnx/lib/python3.6/site-packages/paddle/nn/functional/common.py 127行附近的几个断言，即可转换，且精度对齐。
![image](https://user-images.githubusercontent.com/48579383/103969834-cf092680-51a1-11eb-9283-43be8080ff12.png)

**Comment by czy1747** [comment]
模型能够正常转换，问题先关闭了，后续有问题再讨论，再次表示感谢

**Comment by czy1747** [comment]
想请教一下，crf的decode部分之前放在外面的，用crf_decoding实现然后并到模型结构里面放一起，请问我该怎么做啊
