### ISSUE TITLE
2 OPs are not supported yet

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/X2Paddle#476]
使用车牌识别训练的tensorflow模型，转化为paddle模型出错。下载的最新的X2Paddle代码安装的x2paddle转化

paddle.__version__ = 2.0.0-alpha0
Now translating model from tensorflow to paddle.

========= 2 OPs are not supported yet ===========
========== SparseToDense ============
========== CTCGreedyDecoder ============
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 128, in tf2paddle
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 94, in __init__
Exception: Model is not supported yet.

模型链接：https://pan.baidu.com/s/1lgnQlWwhqmSU_vXqebRNzQ 
提取码：9idk

**Comment by SunAhong1993** [comment]
SparseToDense 这个op可否规避掉，目前Paddle没有与SparseToDense对应的op。

**Comment by Huihuihh** [comment]
> SparseToDense 这个op可否规避掉，目前Paddle没有与SparseToDense对应的op。

这个op需要怎么规避掉，没处理过

**Comment by SunAhong1993** [comment]
> > SparseToDense 这个op可否规避掉，目前Paddle没有与SparseToDense对应的op。
> 
> 这个op需要怎么规避掉，没处理过

这边近期加入SparseToDense这个op的转换，支持后将回复您。

**Comment by SunAhong1993** [comment]
> > > SparseToDense 这个op可否规避掉，目前Paddle没有与SparseToDense对应的op。
> > 
> > 
> > 这个op需要怎么规避掉，没处理过
> 
> 这边近期加入SparseToDense这个op的转换，支持后将回复您。

CTCGreedyDecoder在Paddle中暂时无法对齐，建议将模型中的CTCGreedyDecoder和SparseToDense的处理放于后处理，而不在模型中，即去除CTCGreedyDecoder 、d_predictions、ToInt32这几个节点，生成新的pb模型即可完成转换。
![image](https://user-images.githubusercontent.com/48579383/104145326-7a63e680-5401-11eb-9daa-11fdd9a2c5d4.png)

**Comment by Huihuihh** [comment]
> > > > SparseToDense 这个op可否规避掉，目前Paddle没有与SparseToDense对应的op。
> > > 
> > > 
> > > 这个op需要怎么规避掉，没处理过
> > 
> > 
> > 这边近期加入SparseToDense这个op的转换，支持后将回复您。
> 
> CTCGreedyDecoder在Paddle中暂时无法对齐，建议将模型中的CTCGreedyDecoder和SparseToDense的处理放于后处理，而不在模型中，即去除CTCGreedyDecoder 、d_predictions、ToInt32这几个节点，生成新的pb模型即可完成转换。
> ![image](https://user-images.githubusercontent.com/48579383/104145326-7a63e680-5401-11eb-9daa-11fdd9a2c5d4.png)

没处理过怎么去除相关的节点，去除后，对应的模型预测还准确吗

**Comment by SunAhong1993** [comment]
> > > > > SparseToDense 这个op可否规避掉，目前Paddle没有与SparseToDense对应的op。
> > > > 
> > > > 
> > > > 这个op需要怎么规避掉，没处理过
> > > 
> > > 
> > > 这边近期加入SparseToDense这个op的转换，支持后将回复您。
> > 
> > 
> > CTCGreedyDecoder在Paddle中暂时无法对齐，建议将模型中的CTCGreedyDecoder和SparseToDense的处理放于后处理，而不在模型中，即去除CTCGreedyDecoder 、d_predictions、ToInt32这几个节点，生成新的pb模型即可完成转换。
> > ![image](https://user-images.githubusercontent.com/48579383/104145326-7a63e680-5401-11eb-9daa-11fdd9a2c5d4.png)
> 
> 没处理过怎么去除相关的节点，去除后，对应的模型预测还准确吗

让tf模型的输出为Transepose、Fill、Pack这几层的输出即可，在自己进行红框中这几个op的实现（即用numpy实现后处理）。
