### ISSUE TITLE
转换tensorflow模型报错Wrong wire type in tag

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/X2Paddle#480]
paddle.__version__ = 2.0.0-rc1
/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Now translating model from tensorflow to paddle.
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 127, in tf2paddle
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/decoder/tf_decoder.py", line 333, in __init__
  File "/usr/local/lib/python3.6/dist-packages/protobuf-4.0.0rc2-py3.6.egg/google/protobuf/message.py", line 199, in ParseFromString
    return self.MergeFromString(serialized)
  File "/usr/local/lib/python3.6/dist-packages/protobuf-4.0.0rc2-py3.6.egg/google/protobuf/internal/python_message.py", line 1145, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python3.6/dist-packages/protobuf-4.0.0rc2-py3.6.egg/google/protobuf/internal/python_message.py", line 1212, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/local/lib/python3.6/dist-packages/protobuf-4.0.0rc2-py3.6.egg/google/protobuf/internal/decoder.py", line 754, in DecodeField
    if value._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/usr/local/lib/python3.6/dist-packages/protobuf-4.0.0rc2-py3.6.egg/google/protobuf/internal/python_message.py", line 1212, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/local/lib/python3.6/dist-packages/protobuf-4.0.0rc2-py3.6.egg/google/protobuf/internal/decoder.py", line 733, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/usr/local/lib/python3.6/dist-packages/protobuf-4.0.0rc2-py3.6.egg/google/protobuf/internal/python_message.py", line 1212, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/local/lib/python3.6/dist-packages/protobuf-4.0.0rc2-py3.6.egg/google/protobuf/internal/decoder.py", line 888, in DecodeMap
    if submsg._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/usr/local/lib/python3.6/dist-packages/protobuf-4.0.0rc2-py3.6.egg/google/protobuf/internal/python_message.py", line 1199, in InternalParse
    buffer, new_pos, wire_type)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/protobuf-4.0.0rc2-py3.6.egg/google/protobuf/internal/decoder.py", line 989, in _DecodeUnknownField
    (data, pos) = _DecodeUnknownFieldSet(buffer, pos)
  File "/usr/local/lib/python3.6/dist-packages/protobuf-4.0.0rc2-py3.6.egg/google/protobuf/internal/decoder.py", line 968, in _DecodeUnknownFieldSet
    (data, pos) = _DecodeUnknownField(buffer, pos, wire_type)
  File "/usr/local/lib/python3.6/dist-packages/protobuf-4.0.0rc2-py3.6.egg/google/protobuf/internal/decoder.py", line 993, in _DecodeUnknownField
    raise _DecodeError('Wrong wire type in tag.')
google.protobuf.message.DecodeError: Wrong wire type in tag.

**Comment by SunAhong1993** [comment]
这个可能是环境问题造成的，您可尝试下环境是否可以跑通tensorflow的前向。
