### ISSUE TITLE
onnx模型转paddle失败

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/X2Paddle#481]
paddle.__version__ = 2.0.0-rc1
Now translating model from onnx to paddle.
model ir_version: 6, op version: 9
shape inferencing ...
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 9, automatically treated as op_set: 9.

========= 2 OPs are not supported yet ===========
========== LogSoftmax ============
========== LSTM ============
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 288, in main
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 187, in onnx2paddle
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/onnx2paddle/onnx_op_mapper.py", line 32, in __init__
Exception: Model is not supported yet.

模型链接：https://pan.baidu.com/s/1o177RN-Iu10l6yjx2F7jcg 
提取码：uy96

**Comment by SunAhong1993** [comment]
这两个op目前暂不支持，近期内支持后与您联系。
