### ISSUE TITLE
导入pytorch2paddle报错 ，from x2paddle.convert import pytorch2paddle报错

### ISSUE THREAD

**Issue by WeipengChan** [PaddlePaddle/X2Paddle#482]
paddlepaddle 1.8.5  
然后x2paddle是1.0.0rc。
报错。

Traceback (most recent call last):
  File "test/paddle_serveing/test_conver.py", line 69, in <module>
    from x2paddle.convert import pytorch2paddle
  File "/usr/local/lib/python3.6/site-packages/x2paddle/__init__.py", line 3, in <module>
    from .core.program import PaddleGraph
  File "/usr/local/lib/python3.6/site-packages/x2paddle/core/program.py", line 18, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.6/site-packages/paddle/__init__.py", line 37, in <module>
    import paddle.complex
  File "/usr/local/lib/python3.6/site-packages/paddle/complex/__init__.py", line 15, in <module>
    from . import tensor
  File "/usr/local/lib/python3.6/site-packages/paddle/complex/tensor/__init__.py", line 15, in <module>
    from . import math
  File "/usr/local/lib/python3.6/site-packages/paddle/complex/tensor/math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "/usr/local/lib/python3.6/site-packages/paddle/common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/core.py", line 273, in <module>
    raise e
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/core.py", line 243, in <module>
    from .core_avx import *
ImportError: /usr/local/lib/python3.6/site-packages/paddle/fluid/core_avx.so: undefined symbol: dnnl_matmul_desc_init

**Comment by WeipengChan** [comment]
python3.6.8
paddlepaddle 2.0.0rc 
然后x2paddle是1.0.0rc。
还是报错。错误名字不一样。。。。。。


Traceback (most recent call last):
  File "test/paddle_serveing/test_conver.py", line 69, in <module>
    from x2paddle.convert import pytorch2paddle
  File "/usr/local/lib/python3.6/site-packages/x2paddle/__init__.py", line 3, in <module>
    from .core.program import PaddleGraph
  File "/usr/local/lib/python3.6/site-packages/x2paddle/core/program.py", line 18, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.6/site-packages/paddle/__init__.py", line 29, in <module>
    from .fluid import monkey_patch_variable
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/core.py", line 286, in <module>
    raise e
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/core.py", line 254, in <module>
    from .core_avx import *
ImportError: /usr/local/lib/python3.6/site-packages/paddle/fluid/core_avx.so: undefined symbol: dnnl_primitive_attr_set_scales

**Comment by SunAhong1993** [comment]
您这边先看下paddle是否安装成功，执行下述python脚本如报错则表示安装失败：
```python
import paddle
paddle.utils.run_check()
```
安装成功会有如下提示：
![image](https://user-images.githubusercontent.com/48579383/103864071-ee01ad00-50fc-11eb-9f8c-f90db25ac818.png)
