### ISSUE TITLE
Message type "caffe.PoolingParameter" has no field named "ceil_mode".

### ISSUE THREAD

**Issue by WeipengChan** [PaddlePaddle/X2Paddle#483]
Caffe模型转换至PaddlePaddle，Caffe模型的来源是自研模型  ，模型任务是属于关键点

paddle.__version__ = 2.0.0-rc1
Now translating model from caffe to paddle.
Traceback (most recent call last):
  File "/root/miniconda3/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.6/site-packages/x2paddle/convert.py", line 298, in main
    args.caffe_proto, args.paddle_type, params_merge)
  File "/root/miniconda3/lib/python3.6/site-packages/x2paddle/convert.py", line 166, in caffe2paddle
    model = CaffeDecoder(proto, weight, caffe_proto)
  File "/root/miniconda3/lib/python3.6/site-packages/x2paddle/decoder/caffe_decoder.py", line 291, in __init__
    text_format.Merge(proto_str, self.net)
  File "/root/miniconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 737, in Merge
    allow_unknown_field=allow_unknown_field)
  File "/root/miniconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 805, in MergeLines
    return parser.MergeLines(lines, message)
  File "/root/miniconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 830, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/root/miniconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 852, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/root/miniconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 980, in _MergeField
    merger(tokenizer, message, field)
  File "/root/miniconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1054, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/root/miniconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 980, in _MergeField
    merger(tokenizer, message, field)
  File "/root/miniconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 1054, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/root/miniconda3/lib/python3.6/site-packages/google/protobuf/text_format.py", line 947, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 1858:5 : Message type "caffe.PoolingParameter" has no field named "ceil_mode".

**Comment by SunAhong1993** [comment]
您的Pooling添加了自定义的属性ceil_mode，可参照https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/user_guides/add_caffe_custom_layer.md进行使用，
![image](https://user-images.githubusercontent.com/48579383/103886240-2cf32b00-511c-11eb-8263-35e15478d624.png)，之后实现对应代码。

**Comment by WeipengChan** [comment]
> 您的Pooling添加了自定义的属性ceil_mode，可参照[https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/user_guides/add_caffe_custom_layer.md进行使用，](https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/user_guides/add_caffe_custom_layer.md%E8%BF%9B%E8%A1%8C%E4%BD%BF%E7%94%A8%EF%BC%8C)
> ![image](https://user-images.githubusercontent.com/48579383/103886240-2cf32b00-511c-11eb-8263-35e15478d624.png)，之后实现对应代码。

谢谢。
