### ISSUE TITLE
多目标检测模型转paddle出错

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/X2Paddle#484]
模型来自 https://github.com/open-mmlab/mmdetection
使用x2paddle转化为paddle模型时出错
paddle.__version__ = 2.0.0-rc1
Now translating model from onnx to paddle.
model ir_version: 6, op version: 11
shape inferencing ...
/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/decoder/onnx_shape_inference.py:510: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 11, automatically treated as op_set: 9.

========= 3 OPs are not supported yet ===========
========== NonMaxSuppression ============
========== Log ============
========== TopK ============
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 288, in main
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 187, in onnx2paddle
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/onnx2paddle/onnx_op_mapper.py", line 32, in __init__
Exception: Model is not supported yet.

模型链接：https://pan.baidu.com/s/1AZVzaLsZSf7hIvx6T_RpdA 
提取码：pez0

**Comment by SunAhong1993** [comment]
这边近期加入SparseToDense这个op的转换，支持后将回复您。

> 模型来自 https://github.com/open-mmlab/mmdetection
> 使用x2paddle转化为paddle模型时出错
> paddle.**version** = 2.0.0-rc1
> Now translating model from onnx to paddle.
> model ir_version: 6, op version: 11
> shape inferencing ...
> /usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/decoder/onnx_shape_inference.py:510: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
> shape inferenced.
> Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 11, automatically treated as op_set: 9.
> 
> ========= 3 OPs are not supported yet ===========
> ========== NonMaxSuppression ============
> ========== Log ============
> ========== TopK ============
> /usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
> import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
> Traceback (most recent call last):
> File "/usr/local/bin/x2paddle", line 11, in
> load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 288, in main
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 187, in onnx2paddle
> File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/onnx2paddle/onnx_op_mapper.py", line 32, in **init**
> Exception: Model is not supported yet.
> 
> 模型链接：https://pan.baidu.com/s/1AZVzaLsZSf7hIvx6T_RpdA
> 提取码：pez0

这边在跑onnx前向时会出错，可否提供一个输入，以numpy形式保存。

**Comment by Huihuihh** [comment]
输入默认的是[1, 3, 800, 1216]
