### ISSUE TITLE
TensorFlow OPs not supported

### ISSUE THREAD

**Issue by Dreamkeeper66666** [PaddlePaddle/X2Paddle#493]
```
paddle.__version__ = 2.0.0-rc0
Now translating model from tensorflow to paddle.

========= 11 OPs are not supported yet ===========
========== SaveV2 ============
========== PadV2 ============
========== Log ============
========== VariableV2 ============
========== NoOp ============
========== Cumsum ============
========== TruncatedNormal ============
========== ReverseV2 ============
========== RestoreV2 ============
========== Select ============
========== Assign ============
Traceback (most recent call last):
  File "/root/anaconda3/bin/x2paddle", line 10, in <module>
    sys.exit(main())
  File "/root/anaconda3/lib/python3.7/site-packages/x2paddle/convert.py", line 273, in main
    define_input_shape, args.paddle_type, params_merge)
  File "/root/anaconda3/lib/python3.7/site-packages/x2paddle/convert.py", line 128, in tf2paddle
    mapper = TFOpMapper(model)
  File "/root/anaconda3/lib/python3.7/site-packages/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 94, in __init__
    raise Exception("Model is not supported yet.")
Exception: Model is not supported yet.
```

**Comment by SunAhong1993** [comment]
请问下这个模型是否为训练模型，因为看到了SaveV2和TruncatedNormal等，目前训练模型不支持转换；如果喂预测模型，是否方便提供下模型到545510262@qq.com吗？近期支持后回复您。
