### ISSUE TITLE
将onnx模型转paddle报错

### ISSUE THREAD

**Issue by YangLiu0427** [PaddlePaddle/X2Paddle#494]
命令行：x2paddle --framework=onnx --model=mobilefacenet.onnx --save_dir=./
错误信息：paddle.__version__ = 2.0.0-rc0
Now translating model from onnx to paddle.
model ir_version: 4, op version: 9
shape inferencing ...
/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/decoder/onnx_shape_inference.py:510: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 9, automatically treated as op_set: 9.
Total nodes: 187
Nodes converting ...
Converting node 374 ...     convert failed node:337, op_type is PRelu
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')())
  File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/convert.py", line 288, in main
  File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/convert.py", line 187, in onnx2paddle
  File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/onnx_op_mapper.py", line 46, in __init__
  File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 72, in run_mapping
  File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 1395, in PRelu
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (64,)

请求帮助，谢谢。

**Comment by SunAhong1993** [comment]
这边更新下X2Paddle和PaddlePaddle，应该就可以转换了。
更新X2Paddle：
```
pip uninstall x2paddle
git clone https://github.com/PaddlePaddle/X2Paddle.git
cd X2Paddle
python setup.py install
```
更新Paddle:
```
pip uninstall paddlepaddle
pip install paddlepaddle==2.0.0-rc1
```

**Comment by YangLiu0427** [comment]
你好，我更新了，但还是报了一样的错误，请帮忙看看
paddle.__version__ = 2.0.0-rc1
Now translating model from onnx to paddle.
model ir_version: 4, op version: 9
shape inferencing ...
/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/decoder/onnx_shape_inference.py:510: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 9, automatically treated as op_set: 9.
Total nodes: 187
Nodes converting ...
Converting node 374 ...     convert failed node:337, op_type is PRelu
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')())
  File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/convert.py", line 288, in main
  File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/convert.py", line 187, in onnx2paddle
  File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/onnx_op_mapper.py", line 46, in __init__
  File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 72, in run_mapping
  File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 1395, in PRelu
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (64,)

**Comment by SunAhong1993** [comment]
> 你好，我更新了，但还是报了一样的错误，请帮忙看看
> paddle.**version** = 2.0.0-rc1
> Now translating model from onnx to paddle.
> model ir_version: 4, op version: 9
> shape inferencing ...
> /usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/decoder/onnx_shape_inference.py:510: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
> shape inferenced.
> Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 9, automatically treated as op_set: 9.
> Total nodes: 187
> Nodes converting ...
> Converting node 374 ... convert failed node:337, op_type is PRelu
> Traceback (most recent call last):
> File "/usr/local/bin/x2paddle", line 33, in
> sys.exit(load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')())
> File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/convert.py", line 288, in main
> File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/convert.py", line 187, in onnx2paddle
> File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/onnx_op_mapper.py", line 46, in **init**
> File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 72, in run_mapping
> File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 1395, in PRelu
> File "<**array_function** internals>", line 6, in reshape
> File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
> return _wrapfunc(a, 'reshape', newshape, order=order)
> File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
> return _wrapit(obj, method, *args, **kwds)
> File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
> result = getattr(asarray(obj), method)(*args, **kwds)
> ValueError: cannot reshape array of size 1 into shape (64,)

方便把模型提供给我们下吗？发送到545510262@qq.com

**Comment by YangLiu0427** [comment]
> > 你好，我更新了，但还是报了一样的错误，请帮忙看看
> > paddle.**version** = 2.0.0-rc1
> > Now translating model from onnx to paddle.
> > model ir_version: 4, op version: 9
> > shape inferencing ...
> > /usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/decoder/onnx_shape_inference.py:510: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
> > shape inferenced.
> > Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 9, automatically treated as op_set: 9.
> > Total nodes: 187
> > Nodes converting ...
> > Converting node 374 ... convert failed node:337, op_type is PRelu
> > Traceback (most recent call last):
> > File "/usr/local/bin/x2paddle", line 33, in
> > sys.exit(load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')())
> > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/convert.py", line 288, in main
> > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/convert.py", line 187, in onnx2paddle
> > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/onnx_op_mapper.py", line 46, in **init**
> > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 72, in run_mapping
> > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 1395, in PRelu
> > File "<**array_function** internals>", line 6, in reshape
> > File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
> > return _wrapfunc(a, 'reshape', newshape, order=order)
> > File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
> > return _wrapit(obj, method, *args, **kwds)
> > File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
> > result = getattr(asarray(obj), method)(*args, **kwds)
> > ValueError: cannot reshape array of size 1 into shape (64,)
> 
> 方便把模型提供给我们下吗？发送到[545510262@qq.com](mailto:545510262@qq.com)

**Comment by YangLiu0427** [comment]
> > 你好，我更新了，但还是报了一样的错误，请帮忙看看
> > paddle.**version** = 2.0.0-rc1
> > Now translating model from onnx to paddle.
> > model ir_version: 4, op version: 9
> > shape inferencing ...
> > /usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/decoder/onnx_shape_inference.py:510: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
> > shape inferenced.
> > Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 9, automatically treated as op_set: 9.
> > Total nodes: 187
> > Nodes converting ...
> > Converting node 374 ... convert failed node:337, op_type is PRelu
> > Traceback (most recent call last):
> > File "/usr/local/bin/x2paddle", line 33, in
> > sys.exit(load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')())
> > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/convert.py", line 288, in main
> > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/convert.py", line 187, in onnx2paddle
> > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/onnx_op_mapper.py", line 46, in **init**
> > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 72, in run_mapping
> > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 1395, in PRelu
> > File "<**array_function** internals>", line 6, in reshape
> > File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
> > return _wrapfunc(a, 'reshape', newshape, order=order)
> > File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
> > return _wrapit(obj, method, *args, **kwds)
> > File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
> > result = getattr(asarray(obj), method)(*args, **kwds)
> > ValueError: cannot reshape array of size 1 into shape (64,)
> 
> 方便把模型提供给我们下吗？发送到[545510262@qq.com](mailto:545510262@qq.com)

您好，我已经发邮件了，发件人为1109895468@qq.com，请帮忙看看，谢谢。

**Comment by SunAhong1993** [comment]
> > > 你好，我更新了，但还是报了一样的错误，请帮忙看看
> > > paddle.**version** = 2.0.0-rc1
> > > Now translating model from onnx to paddle.
> > > model ir_version: 4, op version: 9
> > > shape inferencing ...
> > > /usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/decoder/onnx_shape_inference.py:510: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
> > > shape inferenced.
> > > Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 9, automatically treated as op_set: 9.
> > > Total nodes: 187
> > > Nodes converting ...
> > > Converting node 374 ... convert failed node:337, op_type is PRelu
> > > Traceback (most recent call last):
> > > File "/usr/local/bin/x2paddle", line 33, in
> > > sys.exit(load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')())
> > > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/convert.py", line 288, in main
> > > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/convert.py", line 187, in onnx2paddle
> > > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/onnx_op_mapper.py", line 46, in **init**
> > > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 72, in run_mapping
> > > File "/usr/local/lib/python3.5/dist-packages/x2paddle-1.0.0rc1-py3.5.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 1395, in PRelu
> > > File "<**array_function** internals>", line 6, in reshape
> > > File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
> > > return _wrapfunc(a, 'reshape', newshape, order=order)
> > > File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
> > > return _wrapit(obj, method, *args, **kwds)
> > > File "/home/user/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
> > > result = getattr(asarray(obj), method)(*args, **kwds)
> > > ValueError: cannot reshape array of size 1 into shape (64,)
> > 
> > 
> > 方便把模型提供给我们下吗？发送到[545510262@qq.com](mailto:545510262@qq.com)
> 
> 您好，我已经发邮件了，发件人为[1109895468@qq.com](mailto:1109895468@qq.com)，请帮忙看看，谢谢。

已收到，这边帮忙查看

**Comment by SunAhong1993** [comment]
已修复该问题( https://github.com/PaddlePaddle/X2Paddle/pull/486/commits/5bddbb9a5bae468049523acf9fd36736902c48c1 )，您重新安装下X2Paddle：
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git -b onnx
cd X2Paddle
python setup.py install
```

**Comment by YangLiu0427** [comment]
> 已修复该问题( [5bddbb9](https://github.com/PaddlePaddle/X2Paddle/commit/5bddbb9a5bae468049523acf9fd36736902c48c1) )，您重新安装下X2Paddle：
> 
> ```
> pip uninstall x2paddle
> git clone https://github.com/SunAhong1993/X2Paddle.git -b onnx
> cd X2Paddle
> python setup.py install
> ```

十分感谢。

**Comment by YangLiu0427** [comment]
将onnx转成paddle之后生成了文件夹inference_model，然后我利用paddle_lite想转成.nb格式，出现错误。
命令：paddle_lite_opt --model_dir=./onnxToPaddle/inference_model --optimize_out=mobilefacenet --optimize_out_type=naive_buffer --valid_targets=arm
错误：WARNING: Logging before InitGoogleLogging() is written to STDERR
F0119 15:42:30.873152  4516 model_parser.cc:137] Check failed: fin.is_open() Cannot open file: ./onnxToPaddle/inference_model/__model__
*** Check failure stack trace: ***
Aborted


我看了一下，inference_model路径下，确实没有__model__，请问一下这是什么原因，谢谢。

**Comment by SunAhong1993** [comment]
> 将onnx转成paddle之后生成了文件夹inference_model，然后我利用paddle_lite想转成.nb格式，出现错误。
> 命令：paddle_lite_opt --model_dir=./onnxToPaddle/inference_model --optimize_out=mobilefacenet --optimize_out_type=naive_buffer --valid_targets=arm
> 错误：WARNING: Logging before InitGoogleLogging() is written to STDERR
> F0119 15:42:30.873152 4516 model_parser.cc:137] Check failed: fin.is_open() Cannot open file: ./onnxToPaddle/inference_model/**model**
> *** Check failure stack trace: ***
> Aborted
> 
> 我看了一下，inference_model路径下，确实没有__model__，请问一下这是什么原因，谢谢。

你把model.pdmodel改为__model__，model.pdiparams改为__params__，两者是等价的，只是明明不一致

**Comment by YangLiu0427** [comment]
你好，我再转另一个模型时，又报错了，请帮忙看一下，谢谢。
命令：x2paddle --framework=onnx --model=FaceDetector.onnx --save_dir=./FaceDetector
错误：AssertionError: value in inputs should be type of string or list of string

**Comment by SunAhong1993** [comment]
> 你好，我再转另一个模型时，又报错了，请帮忙看一下，谢谢。
> 命令：x2paddle --framework=onnx --model=FaceDetector.onnx --save_dir=./FaceDetector
> 错误：AssertionError: value in inputs should be type of string or list of string

方便把模型提供给我们下吗？发送到545510262@qq.com

**Comment by YangLiu0427** [comment]
> > 你好，我再转另一个模型时，又报错了，请帮忙看一下，谢谢。
> > 命令：x2paddle --framework=onnx --model=FaceDetector.onnx --save_dir=./FaceDetector
> > 错误：AssertionError: value in inputs should be type of string or list of string
> 
> 方便把模型提供给我们下吗？发送到[545510262@qq.com](mailto:545510262@qq.com)

你好，我已经发邮件了，发件人为1109895468@qq.com，请帮忙看看，谢谢。

**Comment by SunAhong1993** [comment]
> > > 你好，我再转另一个模型时，又报错了，请帮忙看一下，谢谢。
> > > 命令：x2paddle --framework=onnx --model=FaceDetector.onnx --save_dir=./FaceDetector
> > > 错误：AssertionError: value in inputs should be type of string or list of string
> > 
> > 
> > 方便把模型提供给我们下吗？发送到[545510262@qq.com](mailto:545510262@qq.com)
> 
> 你好，我已经发邮件了，发件人为[1109895468@qq.com](mailto:1109895468@qq.com)，请帮忙看看，谢谢。

已收到，修复后回复您

**Comment by SunAhong1993** [comment]
> > > > 你好，我再转另一个模型时，又报错了，请帮忙看一下，谢谢。
> > > > 命令：x2paddle --framework=onnx --model=FaceDetector.onnx --save_dir=./FaceDetector
> > > > 错误：AssertionError: value in inputs should be type of string or list of string
> > > 
> > > 
> > > 方便把模型提供给我们下吗？发送到[545510262@qq.com](mailto:545510262@qq.com)
> > 
> > 
> > 你好，我已经发邮件了，发件人为[1109895468@qq.com](mailto:1109895468@qq.com)，请帮忙看看，谢谢。
> 
> 已收到，修复后回复您

您好，已修复该问题，您可以重装下X2Paddle，进行转换：
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git -b develop
cd X2Paddle
python setup.py install
```
