### ISSUE TITLE
yolov5s.onnx转换报错

### ISSUE THREAD

**Issue by jedibobo** [PaddlePaddle/X2Paddle#497]
请说明模型的来源，模型类型（例如图像分类、目标检测等）  
yolov5目标检测模型，来自https://github.com/ultralytics/yolov5，v4.0 release的yolov5s.pt
通过repository中models/export.py文件夹导出，再用x2paddle时，命令如下：
 x2paddle --framework onnx --model yolov5s.onnx  --save_dir ./yolov5s --paddle_type static
x2paddle --framework onnx --model yolov5s.onnx --params_merge  --save_dir ./yolov5s --paddle_type static
x2paddle --framework onnx --model yolov5s.onnx --params_merge  --save_dir ./yolov5s --paddle_type dygraph

paddle版本：2.0.0-rc0（jetson上自己编译的，跑其他的没有问题）
转换过程出错提示如下：
```
W0124 22:53:53.971727 24235 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 72, Driver API Version: 10.2, Runtime API Version: 10.2
W0124 22:53:53.974630 24235 device_context.cc:346] device: 0, cuDNN Version: 8.0.
Fail to generate inference model! Problem happend while export inference model from python code '/home/lyb/code/x2paddle_test/yolov5s/x2paddle_code.py';

===================Error Information===============
Traceback (most recent call last):
  File "/home/lyb/envs/paddle-paddlex/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 288, in main
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 189, in onnx2paddle
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 246, in gen_model
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 310, in gen_dygraph_model
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 306, in gen_dygraph_model
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/core/program.py", line 683, in dygraph2static
  File "<decorator-gen-54>", line 2, in save
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
    return func(*args, **kwargs)
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/paddle/fluid/dygraph/jit.py", line 622, in save
    concrete_program = layer.forward.concrete_program
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 445, in concrete_program
    concrete_program, _ = self.get_concrete_program(*input_spec)
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 385, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 656, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 647, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-46>", line 2, in from_func_spec
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
    return func(*args, **kwargs)
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 603, in from_func_spec
    outputs = static_func(*inputs)
  File "/tmp/tmpqh_1f2dx.py", line 274, in forward
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/paddle/tensor/manipulation.py", line 117, in concat
    return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
  File "/home/lyb/envs/paddle-paddlex/lib/python3.6/site-packages/paddle/fluid/layers/tensor.py", line 307, in concat
    "All the Tensors in the input must have the same data type.")
TypeError: All the Tensors in the input must have the same data type.
```
谢谢！

**Comment by SunAhong1993** [comment]
该问题应该是由于转换的代码中使用了gather op，该op在动转静时存在bug，已在Paddle2.0.0-rc1中修复，您可重装下Paddle2.0.0-rc1。

**Comment by jedibobo** [comment]
ok我试一下嗷

**Comment by jedibobo** [comment]
确实可以，感谢！
