### ISSUE TITLE
onnx2paddle 報錯

### ISSUE THREAD

**Issue by tingggggg** [PaddlePaddle/X2Paddle#498]
模型來源：tf
inception v1 和 v2
先轉至 onnx 後

使用 x2paddle 出錯

v1
```
λ 3667badca247 /wd x2paddle --framework=onnx --model=/model_onnx/inception_v1.onnx --save_dir=onnx2paddle/inception_v1/ --paddle_type dygraph
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
paddle.__version__ = 2.0.0-rc1
Now translating model from onnx to paddle.
model ir_version: 4, op version: 8
shape inferencing ...
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 8, automatically treated as op_set: 9.
Total nodes: 146
Nodes converting ...
Converting node 80 ...     convert failed node:InceptionV1_InceptionV1_Conv2d_1a_7x7_BatchNorm_FusedBatchNorm_0, op_type is Conv
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 288, in main
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 187, in onnx2paddle
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/onnx2paddle/onnx_op_mapper.py", line 46, in __init__
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 97, in run_mapping
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 1719, in Conv
AttributeError: 'str' object has no attribute 'out_shapes'

```

v2
```
λ 3667badca247 /wd x2paddle --framework=onnx --model=/model_onnx/inception_v2.onnx --save_dir=onnx2paddle/inception_v2/ --paddle_type dygraph
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
paddle.__version__ = 2.0.0-rc1
Now translating model from onnx to paddle.
model ir_version: 4, op version: 8
shape inferencing ...
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 8, automatically treated as op_set: 9.
Total nodes: 171
Nodes converting ...
Converting node 86 ...     convert failed node:InceptionV2_InceptionV2_Conv2d_1a_7x7_separable_conv2d_depthwise_0, op_type is Conv
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 288, in main
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 187, in onnx2paddle
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/onnx2paddle/onnx_op_mapper.py", line 46, in __init__
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 97, in run_mapping
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 1719, in Conv
AttributeError: 'str' object has no attribute 'out_shapes'
```

**Comment by SunAhong1993** [comment]
您好，方便提供下v1和v2的onnx模型到545510262@qq.com吗

**Comment by tingggggg** [comment]
> 您好，方便提供下v1和v2的onnx模型到[545510262@qq.com](mailto:545510262@qq.com)吗

已寄送 v1 model 給您，v2檔案過大我再試看看如何寄給您
謝謝

**Comment by SunAhong1993** [comment]
> > 您好，方便提供下v1和v2的onnx模型到[545510262@qq.com](mailto:545510262@qq.com)吗
> 
> 已寄送 v1 model 給您，v2檔案過大我再試看看如何寄給您
> 謝謝

已收到，这边修复后，回复您。

**Comment by SunAhong1993** [comment]
你好，这边已经修复该问题，详见 https://github.com/PaddlePaddle/X2Paddle/pull/499 ，您可以重装X2Paddle：
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git
cd X2Paddle
python setup.py install
```

**Comment by tingggggg** [comment]
謝謝您，目前已可成功轉換 inception v1 v2

順帶一提，後來嘗試轉換手邊其他的 onnx 發現類似的問題發生在 AveragePool
參考您的 #499  修改後也順利修正 PR #500
