### ISSUE TITLE
onnx2paddle 報錯 關於 fusedBatchNorm

### ISSUE THREAD

**Issue by tingggggg** [PaddlePaddle/X2Paddle#501]
tf 官方來源 resnet_v2_50, 101, 152, 200
轉至 onnx 使用 X2paddle 報以下錯誤

```
λ 3667badca247 /wd x2paddle --framework=onnx --model=/model_onnx_tmp/resnet_v2_50.onnx --save_dir=onnx2paddle/resnet_v2_50/ --paddle_type dygraph
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
paddle.__version__ = 2.0.0-rc1
Now translating model from onnx to paddle.
model ir_version: 4, op version: 8
Unknown shape for input tensor[tensor name: 'x2paddle_X_0'] -> shape: ['unk__370', 224, 224, 3], Please define shape of input here,
Note:you can use visualization tools like Netron to check input shape.
Shape of Input(e.g. -1,3,224,224), enter 'N' to skip: -1,224,224,3
shape inferencing ...
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 8, automatically treated as op_set: 9.
Total nodes: 149
Nodes converting ...
Converting node 70 ...     ******************** x2paddle_resnet_v2_50_conv1_weights_read__265__cf__265_0
******************** x2paddle_resnet_v2_50_block1_unit_1_bottleneck_v2_preact_moving_mean_read__14__cf__14_0
Converting node 72 ...     ******************** x2paddle_resnet_v2_50_block1_unit_1_bottleneck_v2_preact_gamma_read__13__cf__13_0
******************** x2paddle_resnet_v2_50_block1_unit_1_bottleneck_v2_preact_moving_mean_read__14__cf__14_0
******************** x2paddle_resnet_v2_50_block1_unit_1_bottleneck_v2_preact_gamma_read__13__cf__13_0
convert failed node:resnet_v2_50_block1_unit_1_bottleneck_v2_preact_FusedBatchNorm_0, op_type is BatchNormalization
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 259, in main
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 172, in onnx2paddle
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/onnx2paddle/onnx_op_mapper.py", line 46, in __init__
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 98, in run_mapping
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 1355, in BatchNormalization
  File "/usr/local/lib/python3.6/site-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/dygraph/onnx2paddle/opset9/opset.py", line 61, in _rename_or_remove_weight
KeyError: "x2paddle_resnet_v2_50_block1_unit_1_bottleneck_v2_preact_gamma_read__13__cf__13_0 not a key in {'x2paddle_resnet_v2_50_logits_weights_read__267__cf__267_0':  .... （過長省略）
```

在猜測可能是 tf model 中 fusedBatchNorm is_training 被設為 true 轉換至 ONNX
ONNX 在轉換至 paddle 才造成此問題。

我需要重新存一個 model is_training set to False 嗎

------------------- 補充 -------------------
後來直接  x2paddle --framework=tensorflow 轉換 .pb 是成功的

**Comment by SunAhong1993** [comment]
方便提供下onnx模型到545510262@qq.com吗

**Comment by tingggggg** [comment]
> 方便提供下onnx模型到[545510262@qq.com](mailto:545510262@qq.com)吗

檔案過大，提供google drive 連結方便嗎

**Comment by SunAhong1993** [comment]
> > 方便提供下onnx模型到[545510262@qq.com](mailto:545510262@qq.com)吗
> 
> 檔案過大，提供google drive 連結方便嗎

可以的

**Comment by tingggggg** [comment]
另外還有一個 .pb model 在轉換 x2paddle --framework=tensorflow 也遇上了問題
若您方便就麻煩你一併幫忙確認一下，謝謝您！

該.pb 轉換報錯如下

```
Now translating model from tensorflow to paddle.
Total nodes: 1701
Nodes converting ...
Converting node 1701 ...     
Nodes converted.
dygraph_conv2d_add_fuse_pass done!
dygraph_tf_batchnorm_fuse_pass done!
dygraph_prelu_fuse_pass done!
Optimize Transpose Layers...70.66%
Transpose layers optimized, before: transpose_num=990, after: transpose_num=96
transpose_eliminate_pass done!
Exporting inference model from python code ('/wd/onnx2paddle/pnasnet_mobile/x2paddle_code.py')... 

In transformed code:

    File "onnx2paddle/pnasnet_mobile/x2paddle_code.py", line 875, in forward (* user code *)
	cell_0_comb_iter_1_left_separable_7x7_1_separable_conv2d_depthwise = self.conv68(depthwise_conv2d_transpose_28)
    File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.6/site-packages/paddle/nn/layer/conv.py", line 644, in forward
	use_cudnn=self._use_cudnn)
    File "/usr/local/lib/python3.6/site-packages/paddle/nn/functional/conv.py", line 144, in _conv_nd
	type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/usr/local/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
	return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2846, in append_op
	attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2046, in __init__
	self.desc.infer_shape(self.block.desc)
    ValueError: (InvalidArgument) The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 28, the input's shape is [-1, 28, 54, 28]; the filter's channels is 1, the filter's shape is [54, 1, 7, 7]; the groups is 54, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:28 != filter_dims[1] * groups:54.] (at /paddle/paddle/fluid/operators/conv_op.cc:96)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < depthwise_conv2d > error]
```

.pb .onnx 已寄出

**Comment by SunAhong1993** [comment]
> 若您方便就麻煩你一併幫忙確認一下，謝謝您！

已收到，修复后回复您

**Comment by SunAhong1993** [comment]
> > 若您方便就麻煩你一併幫忙確認一下，謝謝您！
> 
> 已收到，修复后回复您

均已修复，请更新最新版本的X2Paddle
