### ISSUE TITLE
“VGG_ILSVRC_19_layers.caffemodel“ X2Paddle失败

### ISSUE THREAD

**Issue by GreenValue** [PaddlePaddle/X2Paddle#505]
## 环境
docker pull paddlepaddle/paddle:2.0.0-gpu-cuda10.0-cudnn7
```
/ paddle --version
/usr/local/python2.7.15/lib/python2.7/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
PaddlePaddle 2.0.0.post100, compiled with
    with_avx: ON
    with_gpu: ON
    with_mkl: ON
    with_mkldnn: ON
    with_python: ON
```

## 执行记录

模型来源： caffe，图像分类
模型说明： VGG19的预训练模型：
[http://www.robots.ox.ac.uk/~vgg/software/very_deep/caffe/VGG_ILSVRC_19_layers.caffemodel](url)
模型文件： 百度网盘上传中
转换过程出错提示如下：
```
命令：
 x2paddle --framework=caffe --prototxt=VGG_ILSVRC_19_layers_deploy.prototxt --weight=VGG_ILSVRC_19_layers.caffemodel --save_dir=pd_model --paddle_type static

输出：
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
paddle.__version__ = 2.0.0
Now translating model from caffe to paddle.
The filter layer:drop6
The filter layer:drop7
Total nodes: 44
Nodes converting ...

Nodes converted.
Traceback (most recent call last):
  File "/usr/local/python2.7.15/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')()
  File "build/bdist.linux-x86_64/egg/x2paddle/convert.py", line 256, in main
  File "build/bdist.linux-x86_64/egg/x2paddle/convert.py", line 144, in caffe2paddle
  File "build/bdist.linux-x86_64/egg/x2paddle/core/program.py", line 178, in build
AssertionError: Couldn't find data_p0 in previous layers, the layers should be make by topological sort
```

**Comment by GreenValue** [comment]
模型文件：链接：https://pan.baidu.com/s/1nF6jItH5o29hW-wYBegxfQ 提取码：s1dx

**Comment by SunAhong1993** [comment]
> 模型文件：链接：https://pan.baidu.com/s/1nF6jItH5o29hW-wYBegxfQ 提取码：s1dx

收到，我们这边查看下原因回复您

**Comment by SunAhong1993** [comment]
> > 模型文件：链接：https://pan.baidu.com/s/1nF6jItH5o29hW-wYBegxfQ 提取码：s1dx
> 
> 收到，我们这边查看下原因回复您

已修复该问题，您可以重装下X2Paddle进行转换：
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git
cd X2Paddle
python setup.py install
```
但是MemoryData中有的transform不属于模型转换范畴（属于数据预处理），该部分不进行转换，您可自行添加该部分的处理。

**Comment by GreenValue** [comment]
感谢，感谢。
>>但是MemoryData中有的transform不属于模型转换范畴（属于数据预处理），该部分不进行转换，您可自行添加该部分的处理
具体指哪里？如果添加该部分处理？有列子吗？

**Comment by SunAhong1993** [comment]
> 感谢，感谢。
> 
> > > 但是MemoryData中有的transform不属于模型转换范畴（属于数据预处理），该部分不进行转换，您可自行添加该部分的处理
> > > 具体指哪里？如果添加该部分处理？有列子吗？

这边没有例子，您只需自己使用python实现下图中的数据预处理即可（包括crop、mirror、normalization）
![image](https://user-images.githubusercontent.com/48579383/106559902-11374500-6561-11eb-868c-367edb12e22a.png)
