### ISSUE TITLE
TensorFlow模型pb文件转， 提示模型不支持

### ISSUE THREAD

**Issue by 459936800** [PaddlePaddle/X2Paddle#506]
模型来源： TensorFlow
模型说明： 图像生成，https://gitee.com/Harry6011/DCGAN-tensorflow 

命令：
x2paddle --framework=tensorflow --model=checkpoint/DCGAN_64_64_64/DCGAN.pb --save_dir=pd_model/DCGAN --paddle_type static

转换过程出错提示如下：
```
Now translating model from tensorflow to paddle.

========= 24 OPs are not supported yet ===========
========== NoOp ============
========== ScalarSummary ============
========== ShapeN ============
========== BiasAddGrad ============
========== BroadcastGradientArgs ============
========== RestoreV2 ============
========== FusedBatchNormGrad ============
========== SaveV2 ============
========== ZerosLike ============
========== ReluGrad ============
========== TanhGrad ============
========== MergeSummary ============
========== TruncatedNormal ============
========== Conv2DBackpropFilter ============
========== VariableV2 ============
========== ImageSummary ============
========== Reciprocal ============
========== HistogramSummary ============
========== Log1p ============
========== ApplyAdam ============
========== RandomStandardNormal ============
========== Assign ============
========== Select ============
========== AssignSub ============
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.0rc1', 'console_scripts', 'x2paddle')())
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 273, in main
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/convert.py", line 128, in tf2paddle
  File "/usr/local/lib/python3.6/dist-packages/x2paddle-1.0.0rc1-py3.6.egg/x2paddle/op_mapper/static/tf2paddle/tf_op_mapper.py", line 96, in __init__
Exception: Model is not supported yet.
```

备注：
  def save(self, checkpoint_dir, step):
    model_name = "DCGAN.model"
    checkpoint_dir = os.path.join(checkpoint_dir, self.model_dir)
    # 本身没有转化pd文件的code，下面这行是自己后来加的。
    tf.train.write_graph(self.sess.graph.as_graph_def(), checkpoint_dir, self.dataset_name+'DCGAN.pb', as_text=False)
    if not os.path.exists(checkpoint_dir):
      os.makedirs(checkpoint_dir)
    self.saver.save(self.sess,
            os.path.join(checkpoint_dir, model_name),
            global_step=step)

**Comment by jiangjiajun** [comment]
当前这个模型中存在大量XXXGrad类的OP，应该是在导出模型时，将整个计算图导了出来。

实际上我们日常在用时，只需要前向计算的那部分图，因此需要给定图的输入和输出节点，来导出需要的部分，参考下面文档
https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/user_guides/export_tf_model.md
