### ISSUE TITLE
pytorch模型转为paddle模型，提示prelu不支持

### ISSUE THREAD

**Issue by zhudibo** [PaddlePaddle/X2Paddle#513]
pytorch模型直接转为paddle模型时提示错误，prelu不支持，错误如下：
Now translating model from pytorch to paddle.
Traceback (most recent call last):
  File "/home/un/Silent-Face-Anti-Spoofing/conver.py", line 32, in <module>

========= 1 OPs are not supported yet ===========
========== aten::prelu ============
    input_examples=[torch.tensor(input_data)])
  File "/usr/local/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 201, in pytorch2paddle
  File "/usr/local/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/op_mapper/dygraph/pytorch2paddle/pytorch_op_mapper.py", line 43, in __init__
Exception: Model is not supported yet.

Process finished with exit code 1

**Comment by SunAhong1993** [comment]
您可以将模型和相关代码提供至545510262@qq.com吗？近期我们将对这个op进行支持

**Comment by zhudibo** [comment]
好的

**Comment by SunAhong1993** [comment]
已更新相关op，您可重装X2Paddle进行转换，重装方式如下：
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git
cd X2Paddle
python setup.py install
```

**Comment by zhudibo** [comment]
好的，谢谢大佬



---原始邮件---
发件人: "SunAhong1993"<notifications@github.com&gt;
发送时间: 2021年3月4日(周四) 中午11:53
收件人: "PaddlePaddle/X2Paddle"<X2Paddle@noreply.github.com&gt;;
抄送: "zhudibo"<1020286694@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/X2Paddle] pytorch模型转为paddle模型，提示prelu不支持 (#513)




 
已更新相关op，您可重装X2Paddle进行转换，重装方式如下：
 pip uninstall x2paddle git clone https://github.com/SunAhong1993/X2Paddle.git cd X2Paddle python setup.py install
