### ISSUE TITLE
ONNX通过X2paddle转换时出现GPU错误

### ISSUE THREAD

**Issue by Owen-Fish** [PaddlePaddle/X2Paddle#519]
概要：在实验将pytorh中训练的模型通过x2paddle转化，实施路径是pytorch模型->onnx->paddle，在onnx->paddle
过程中出现了GPU问题。报错信息简要为（这种错误出现在我一张卡满负荷跑的时候，切换到另一张空卡的时候没问题）

> OSError: (External)  Cublas error, `CUSOLVER_STATUS_INTERNAL_ERROR`. An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.  (at /paddle/paddle/fluid/platform/device_context.h:264)

安装库：paddlepaddle-gpu 2.0.0.post101以及其他必须库

疑惑：我是onnx通过X2paddle转为pd模型，为什么需要在GPU有显存的时候才可以进行？是我paddlepaddle为GPU版本的原因吗？

**error trace**：
(paddle) lenovo@lenovo-desktop:~/4T/xxx/program/Torch$ x2paddle --framework=onnx --model=./resnet18.onnx --save_dir=pd_model --paddle_type dygraph
paddle.__version__ = 2.0.0
Now translating model from onnx to paddle.
model ir_version: 6, op version: 10
shape inferencing ...
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 10, automatically treated as op_set: 9.
Total nodes: 69
Nodes converting ...
Converting node 172 ...     
Nodes converted.
Exporting inference model from python code ('/home/lenovo/4T/xxxx/program/Torch/pd_model/x2paddle_code.py')... 

W0303 10:10:54.654881 28945 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.1, Runtime API Version: 10.1
W0303 10:10:54.655699 28945 device_context.cc:372] device: 0, cuDNN Version: 8.0.
Fail to generate inference model! Problem happend while export inference model from python code '/home/lenovo/4T/xxx/program/Torch/pd_model/x2paddle_code.py';

===================Error Information===============
Traceback (most recent call last):
  File "/home/lenovo/anaconda2/envs/paddle/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')())
  File "/home/lenovo/anaconda2/envs/paddle/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 264, in main
  File "/home/lenovo/anaconda2/envs/paddle/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 174, in onnx2paddle
  File "/home/lenovo/anaconda2/envs/paddle/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/core/program.py", line 245, in gen_model
  File "/home/lenovo/anaconda2/envs/paddle/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/core/program.py", line 304, in gen_dygraph_model
  File "/home/lenovo/anaconda2/envs/paddle/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/core/program.py", line 300, in gen_dygraph_model
  File "/home/lenovo/anaconda2/envs/paddle/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/core/program.py", line 667, in dygraph2static
  File "pd_model/x2paddle_code.py", line 8, in __init__
    self.x2paddle_fc_bias = self.create_parameter(shape=[1000], attr='x2paddle_fc_bias', dtype='float32', default_initializer=paddle.nn.initializer.Constant(value=0.0))
  File "/home/lenovo/anaconda2/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 397, in create_parameter
    default_initializer)
  File "/home/lenovo/anaconda2/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 372, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/lenovo/anaconda2/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2979, in create_parameter
    initializer(param, self)
  File "/home/lenovo/anaconda2/envs/paddle/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 165, in __call__
    stop_gradient=True)
  File "/home/lenovo/anaconda2/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3095, in _prepend_op
    kwargs.get("stop_gradient", False))
  File "/home/lenovo/anaconda2/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
**OSError: (External)  Cublas error, `CUSOLVER_STATUS_INTERNAL_ERROR`. An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.  (at /paddle/paddle/fluid/platform/device_context.h:264)
  [operator < fill_constant > error]**

**Comment by SunAhong1993** [comment]
可先尝试安装使用paddlepaddle进行转换，（pip install paddlepaddle）。
同时方便把模型发给我们（发送至545510262@qq.com），我们查看下原因吗。

**Comment by Owen-Fish** [comment]
@SunAhong1993 我用CUDA_VISIBLE_DEVICES切换到另一块空闲的卡上去之后就没这问题。用的模型就是resnet18，在torchvision里面下载的。我想这会不会是paddle-gpu在X2paddle转换会有用到GPU的资源啊？

**Comment by SunAhong1993** [comment]
> @SunAhong1993 我用CUDA_VISIBLE_DEVICES切换到另一块空闲的卡上去之后就没这问题。用的模型就是resnet18，在torchvision里面下载的。我想这会不会是paddle-gpu在X2paddle转换会有用到GPU的资源啊？

是会用到GPU资源，所以推荐使用CPU的paddlepaddle进行转换。

**Comment by Owen-Fish** [comment]
@SunAhong1993 了解了，谢谢。
