### ISSUE TITLE
caffe 转 paddle

### ISSUE THREAD

**Issue by jon135790** [PaddlePaddle/X2Paddle#521]
模型来源： caffe
模型说明： retinaface
环境:windows10
转换过程出错提示如下：
```
paddle.__version__ = 2.0.0
Now translating model from caffe to paddle.
Total nodes: 125
Nodes converting ...
Converting node 125 ...
Nodes converted.
Model optimizing ...
dygraph_bn_scale_fuse_pass done!
Model optimized.
Exporting inference model from python code ('retinaface\x2paddle_code.py')...

Fail to generate inference model! Problem happend while export inference model from python code 'retinaface\x2paddle_code.py';

===================Error Information===============
Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\x2paddle-script.py", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')())
  File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\convert.py", line 260, in main
  File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\convert.py", line 150, in caffe2paddle
  File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 245, in gen_model
  File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 304, in gen_dygraph_model
  File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 300, in gen_dygraph_model
  File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 664, in dygraph2static
  File "retinaface\x2paddle_code.py", line 222
    class = paddle.reshape(x=class_softmax, shape=[-1, 33600])
          ^
SyntaxError: invalid syntax
```

**Comment by SunAhong1993** [comment]
> 模型来源： caffe
> 模型说明： retinaface
> 环境:windows10
> 转换过程出错提示如下：
> 
> ```
> paddle.__version__ = 2.0.0
> Now translating model from caffe to paddle.
> Total nodes: 125
> Nodes converting ...
> Converting node 125 ...
> Nodes converted.
> Model optimizing ...
> dygraph_bn_scale_fuse_pass done!
> Model optimized.
> Exporting inference model from python code ('retinaface\x2paddle_code.py')...
> 
> Fail to generate inference model! Problem happend while export inference model from python code 'retinaface\x2paddle_code.py';
> 
> ===================Error Information===============
> Traceback (most recent call last):
>   File "D:\Anaconda3\Scripts\x2paddle-script.py", line 33, in <module>
>     sys.exit(load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')())
>   File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\convert.py", line 260, in main
>   File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\convert.py", line 150, in caffe2paddle
>   File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 245, in gen_model
>   File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 304, in gen_dygraph_model
>   File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 300, in gen_dygraph_model
>   File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 664, in dygraph2static
>   File "retinaface\x2paddle_code.py", line 222
>     class = paddle.reshape(x=class_softmax, shape=[-1, 33600])
>           ^
> SyntaxError: invalid syntax
> ```
可以查看下prototxt中是否有命名为class的层（将相关层修改），class在代码中为关键字所以出错了

**Comment by jon135790** [comment]
这个问题修改了名称后已经可以了。谢谢

**Comment by jon135790** [comment]
Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\x2paddle-script.py", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')())
  File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\convert.py", line 260, in main
  File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\convert.py", line 150, in caffe2paddle
  File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 245, in gen_model
  File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 304, in gen_dygraph_model
  File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 300, in gen_dygraph_model
  File "D:\Anaconda3\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 667, in dygraph2static
  File "retinaface\x2paddle_code.py", line 9, in __init__
    self.relu0 = paddle.nn.LeakyReLU(alpha=0.10000000149011612)
TypeError: __init__() got an unexpected keyword argument 'alpha'

**Comment by SunAhong1993** [comment]
> LeakyReLU

这边修复下回复您

**Comment by SunAhong1993** [comment]
> > LeakyReLU
> 
> 这边修复下回复您

该问题已修复，您可重装X2Paddle进行使用，重装方式：
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git
cd X2Paddle
python setup.py install
```

**Comment by jon135790** [comment]
刚才的问题已解决。新的提示：
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
'utf-8' codec can't decode byte 0xa3 in position 6889: invalid start byte
目前的python版本是3.8.5   是否需要将python版本升级到指定版本？谢谢
