### ISSUE TITLE
module 'paddle' has no attribute 'nn'

### ISSUE THREAD

**Issue by nlj0011** [PaddlePaddle/X2Paddle#522]
paddlepaddle = 1.8.5
x2paddle按照第一种方式安装，需要pytorch模型转为paddle，现试用下面的例子会报错：
import torch
import numpy as np
from torchvision.models import AlexNet
from torchvision.models.utils import load_state_dict_from_url
# 构建输入
input_data = np.random.rand(1, 3, 224, 224).astype("float32")
# 获取PyTorch Module
torch_module = AlexNet()
# 设置为eval模式
torch_module.eval()
# 进行转换
from x2paddle.convert import pytorch2paddle
pytorch2paddle(torch_module,
               save_dir="pd_model_trace",
               jit_type="trace",
               input_examples=[torch.tensor(input_data)])

报错信息如下：
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    input_examples=[torch.tensor(input_data)])
  File "lib/python3.6/site-packages/x2paddle-1.0.1-py3.6.egg/x2paddle/convert.py", line 208, in pytorch2paddle
  File "lib/python3.6/site-packages/x2paddle-1.0.1-py3.6.egg/x2paddle/core/program.py", line 245, in gen_model
  File "lib/python3.6/site-packages/x2paddle-1.0.1-py3.6.egg/x2paddle/core/program.py", line 279, in gen_dygraph_model
  File "lib/python3.6/site-packages/x2paddle-1.0.1-py3.6.egg/x2paddle/optimizer/pytorch_code_optimizer/hierachical_tree.py", line 399, in save_source_files
  File "lib/python3.6/site-packages/x2paddle-1.0.1-py3.6.egg/x2paddle/optimizer/pytorch_code_optimizer/hierachical_tree.py", line 362, in convert_subgraph_to_layer
  File "lib/python3.6/site-packages/x2paddle-1.0.1-py3.6.egg/x2paddle/optimizer/pytorch_code_optimizer/hierachical_tree.py", line 228, in merge_node
  File "lib/python3.6/site-packages/x2paddle-1.0.1-py3.6.egg/x2paddle/optimizer/pytorch_code_optimizer/layer_code_generator.py", line 243, in gen_layer_code
  File "lib/python3.6/site-packages/x2paddle-1.0.1-py3.6.egg/x2paddle/optimizer/pytorch_code_optimizer/layer_code_generator.py", line 145, in _update_attrs
  File "lib/python3.6/site-packages/x2paddle-1.0.1-py3.6.egg/x2paddle/core/util.py", line 62, in remove_default_attrs
AttributeError: module 'paddle' has no attribute 'nn'

**Comment by SunAhong1993** [comment]
需要将paddlepaddle更新至2.0.0

**Comment by jiangjiajun** [comment]
> 需要将paddlepaddle更新至2.0.0

建议在X2Paddle中加入一下PaddlePaddle版本的判断

**Comment by nlj0011** [comment]
> 需要将paddlepaddle更新至2.0.0

好的，谢谢！
