### ISSUE TITLE
SyntaxError: invalid decimal literal

### ISSUE THREAD

**Issue by gongruiyang** [PaddlePaddle/X2Paddle#532]
模型来源：onnx
模型说明：图像分割模型，将onnx模型文件转换为paddle
转换过程出错提示如下：
```
F:\Anaconda\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
paddle.__version__ = 2.0.1
Now translating model from onnx to paddle.
model ir_version: 7, op version: 12
shape inferencing ...
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 12, automatically treated as op_set: 9.
Total nodes: 835
Nodes converting ...
Converting node 1831 ...
Nodes converted.
Exporting inference model from python code ('C:\Users\1111\Desktop\test\x2paddle_code.py')...

Fail to generate inference model! Problem happend while export inference model from python code 'C:\Users\1111\Desktop\test\x2paddle_code.py';

===================Error Information===============
Traceback (most recent call last):
  File "F:\Anaconda\Scripts\x2paddle-script.py", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')())
  File "F:\Anaconda\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\convert.py", line 264, in main
  File "F:\Anaconda\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\convert.py", line 174, in onnx2paddle
  File "F:\Anaconda\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 245, in gen_model
  File "F:\Anaconda\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 304, in gen_dygraph_model
  File "F:\Anaconda\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 300, in gen_dygraph_model
  File "F:\Anaconda\lib\site-packages\x2paddle-1.0.1-py3.8.egg\x2paddle\core\program.py", line 664, in dygraph2static
  File "C:\Users\1111\Desktop\test\x2paddle_code.py", line 866
    x2paddle_Concat@1_nc,x2paddle_Concat@1_hw = paddle.split(x=x2paddle_Concat@1, num_or_sections=[2, 2])
                     ^
SyntaxError: invalid decimal literal
```

**Comment by SunAhong1993** [comment]
这个问题是由于onnx模型中的命名出现了非法字符@，把onnx模型中的@替换成合法字符（比如：_）可解决该问题

**Comment by gongruiyang** [comment]
好的，我来试试，谢谢你😃



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 29, 2021 10:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/X2Paddle] SyntaxError: invalid decimal literal (#532)




 
这个问题是由于onnx模型中的命名出现了非法字符@，把onnx模型中的@替换成合法字符（比如：_）可解决该问题
