### ISSUE TITLE
tensorflow转paddle

### ISSUE THREAD

**Issue by jogogohaha** [PaddlePaddle/X2Paddle#533]
```
paddle.__version__ = 2.0.1
/tensorflow-1.15.2/python3.7/tensorflow_core/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Now translating model from tensorflow to paddle.

========= 1 OPs are not supported yet ===========
========== ReverseV2 ============
Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/x2paddle/convert.py", line 256, in main
    define_input_shape, args.paddle_type)
  File "/usr/local/lib/python3.7/dist-packages/x2paddle/convert.py", line 114, in tf2paddle
    mapper = TFOpMapper(model)
  File "/usr/local/lib/python3.7/dist-packages/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 94, in __init__
    raise Exception("Model is not supported yet.")
Exception: Model is not supported yet.
```

请问可以提供ReverseV2的支持吗，谢谢

**Comment by SunAhong1993** [comment]
当前已更新代码支持了ReverseV2，您可按照以下方式更新代码：
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git
cd X2Paddle
python setup.py install
```
有问题可随时反馈。

**Comment by Dreamkeeper66666** [comment]
> 当前已更新代码支持了ReverseV2，您可按照以下方式更新代码：
> 
> ```
> pip uninstall x2paddle
> git clone https://github.com/SunAhong1993/X2Paddle.git
> cd X2Paddle
> python setup.py install
> ```
> 
> 有问题可随时反馈。

```
paddle.__version__ = 2.0.1
/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Now translating model from tensorflow to paddle.
Total nodes: 703
Nodes converting ...
Converting node 313 ...     Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')())
  File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 256, in main
  File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 114, in tf2paddle
  File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 132, in __init__
  File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 251, in Transpose
AssertionError: Perm of transpose OP should be Const
```
请问这是什么问题

**Comment by jogogohaha** [comment]
> 当前已更新代码支持了ReverseV2，您可按照以下方式更新代码：
> 
> ```
> pip uninstall x2paddle
> git clone https://github.com/SunAhong1993/X2Paddle.git
> cd X2Paddle
> python setup.py install
> ```
> 
> 有问题可随时反馈。

```
paddle.__version__ = 2.0.1
/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Now translating model from tensorflow to paddle.
Total nodes: 703
Nodes converting ...
Converting node 313 ...     Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')())
  File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 256, in main
  File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 114, in tf2paddle
  File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 132, in __init__
  File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 251, in Transpose
AssertionError: Perm of transpose OP should be Const
```

下面是一个transpose的node，请问是这里有什么问题吗

```
node {
  name: "swa_model/Tensordot/transpose"
  op: "Transpose"
  input: "swa_model/include_history"
  input: "swa_model/Tensordot/concat"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tperm"
    value {
      type: DT_INT32
    }
  }
}
```
我把报错的地方输出了一下，好像变成ConcatV2了
```
perm: swa_model_Tensordot_concat
input: swa_model_include_history
node: swa_model_Tensordot_transpose
type: ConcatV2
```

**Comment by SunAhong1993** [comment]
> > 当前已更新代码支持了ReverseV2，您可按照以下方式更新代码：
> > ```
> > pip uninstall x2paddle
> > git clone https://github.com/SunAhong1993/X2Paddle.git
> > cd X2Paddle
> > python setup.py install
> > ```
> > 
> > 
> > 有问题可随时反馈。
> 
> ```
> paddle.__version__ = 2.0.1
> /usr/local/lib/python3.7/dist-packages/tensorflow_core/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>   import imp
> Now translating model from tensorflow to paddle.
> Total nodes: 703
> Nodes converting ...
> Converting node 313 ...     Traceback (most recent call last):
>   File "/usr/local/bin/x2paddle", line 33, in <module>
>     sys.exit(load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')())
>   File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 256, in main
>   File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 114, in tf2paddle
>   File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 132, in __init__
>   File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 251, in Transpose
> AssertionError: Perm of transpose OP should be Const
> ```
> 
> 下面是一个transpose的node，请问是这里有什么问题吗
> 
> ```
> node {
>   name: "swa_model/Tensordot/transpose"
>   op: "Transpose"
>   input: "swa_model/include_history"
>   input: "swa_model/Tensordot/concat"
>   attr {
>     key: "T"
>     value {
>       type: DT_FLOAT
>     }
>   }
>   attr {
>     key: "Tperm"
>     value {
>       type: DT_INT32
>     }
>   }
> }
> ```
> 
> 我把报错的地方输出了一下，好像变成ConcatV2了
> 
> ```
> perm: swa_model_Tensordot_concat
> input: swa_model_include_history
> node: swa_model_Tensordot_transpose
> type: ConcatV2
> ```

目前paddle中的transpose的perm只能支持是一个常量，而你的网络中的perm为concat的结果（一个Tensor），您那边可否修改代码把这个perm修改为常量

**Comment by Dreamkeeper66666** [comment]
> > > 当前已更新代码支持了ReverseV2，您可按照以下方式更新代码：
> > > ```
> > > pip uninstall x2paddle
> > > git clone https://github.com/SunAhong1993/X2Paddle.git
> > > cd X2Paddle
> > > python setup.py install
> > > ```
> > > 
> > > 
> > > 有问题可随时反馈。
> > 
> > 
> > ```
> > paddle.__version__ = 2.0.1
> > /usr/local/lib/python3.7/dist-packages/tensorflow_core/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
> >   import imp
> > Now translating model from tensorflow to paddle.
> > Total nodes: 703
> > Nodes converting ...
> > Converting node 313 ...     Traceback (most recent call last):
> >   File "/usr/local/bin/x2paddle", line 33, in <module>
> >     sys.exit(load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')())
> >   File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 256, in main
> >   File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 114, in tf2paddle
> >   File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 132, in __init__
> >   File "/usr/local/lib/python3.7/dist-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 251, in Transpose
> > AssertionError: Perm of transpose OP should be Const
> > ```
> > 
> > 
> > 下面是一个transpose的node，请问是这里有什么问题吗
> > ```
> > node {
> >   name: "swa_model/Tensordot/transpose"
> >   op: "Transpose"
> >   input: "swa_model/include_history"
> >   input: "swa_model/Tensordot/concat"
> >   attr {
> >     key: "T"
> >     value {
> >       type: DT_FLOAT
> >     }
> >   }
> >   attr {
> >     key: "Tperm"
> >     value {
> >       type: DT_INT32
> >     }
> >   }
> > }
> > ```
> > 
> > 
> > 我把报错的地方输出了一下，好像变成ConcatV2了
> > ```
> > perm: swa_model_Tensordot_concat
> > input: swa_model_include_history
> > node: swa_model_Tensordot_transpose
> > type: ConcatV2
> > ```
> 
> 目前paddle中的transpose的perm只能支持是一个常量，而你的网络中的perm为concat的结果（一个Tensor），您那边可否修改代码把这个perm修改为常量

这个tensor是tf.constant(np.array[a1,a2,a3,....])这种格式,其中a1，a2...为numpy数组，不知道这个算constant吗。可能是这个过程变成了concat？有什么办法变成const呢

**Comment by SunAhong1993** [comment]
> np.array[a1,a2,a3,....]

np.array[a1,a2,a3,....] 是否为一个常量，如果为常量，建议直接传入常量。

**Comment by SunAhong1993** [comment]
这边方便把模型提供给我们下吗

**Comment by Dreamkeeper66666** [comment]
> > np.array[a1,a2,a3,....]
> 
> np.array[a1,a2,a3,....] 是否为一个常量，如果为常量，建议直接传入常量。

a1,a2,a3会随着输入的变化而变化，似乎不是常量。

**Comment by SunAhong1993** [comment]
> > > np.array[a1,a2,a3,....]
> > 
> > 
> > np.array[a1,a2,a3,....] 是否为一个常量，如果为常量，建议直接传入常量。
> 
> a1,a2,a3会随着输入的变化而变化，似乎不是常量。

由于paddle的transpose暂不支持perm为Tensor，所以这样的模型暂不支持

**Comment by Dreamkeeper66666** [comment]
> > > > np.array[a1,a2,a3,....]
> > > 
> > > 
> > > np.array[a1,a2,a3,....] 是否为一个常量，如果为常量，建议直接传入常量。
> > 
> > 
> > a1,a2,a3会随着输入的变化而变化，似乎不是常量。
> 
> 由于paddle的transpose暂不支持perm为Tensor，所以这样的模型暂不支持

我刚刚看了下，这个可能是tf.tensordot过程中涉及到了transpose。 下面是相关的代码
  ```    
      h0 = np.zeros([22,22],dtype=np.float32)
      h0[9,9] = 1.0 
      h0[14,15] = -1.0 
      h0[14,16] = -1.0
      h0[15,15] = 1.0
      h0[15,16] = 1.0
      h1 = np.zeros([22,22],dtype=np.float32)
      h1[10,10] = 1.0
      h1[15,16] = -1.0
      h1[16,16] = 1.0
      h2 = np.zeros([22,22],dtype=np.float32)
      h2[11,11] = 1.0
      h3 = np.zeros([22,22],dtype=np.float32)
      h3[12,12] = 1.0
      h4 = np.zeros([22,22],dtype=np.float32)
      h4[13,13] = 1.0
      hist_matrix_builder = tf.constant(np.array([h0,h1,h2,h3,h4]))
      hist_filter_matrix = hist_matrix_base + tf.tensordot(include_history, hist_matrix_builder, axes=[[1],[0]])
```

请问有什么办法可以定义成常量吗，谢谢！

**Comment by SunAhong1993** [comment]
方便把pb模型发到sunyanfang01@baidu.com吗？这边具体看下模型

**Comment by Dreamkeeper66666** [comment]
> sunyanfang01@baidu.com
谢谢，已发送

**Comment by SunAhong1993** [comment]
> > [sunyanfang01@baidu.com](mailto:sunyanfang01@baidu.com)
> > 谢谢，已发送

已收到，查到原因后回复您

**Comment by Dreamkeeper66666** [comment]
> > > [sunyanfang01@baidu.com](mailto:sunyanfang01@baidu.com)
> > > 谢谢，已发送
> 
> 已收到，查到原因后回复您

或许是tensordot的问题，并不是直接转换的，似乎目前并没有支持tensordot？

**Comment by SunAhong1993** [comment]
这边更新了下代码，支持了你这类模型，您可重装X2Paddle进行转换：
```
pip uninstall x2paddle
git clone https://github.com/SunAhong1993/X2Paddle.git
cd X2Paddle
python setup.py install
```

**Comment by Dreamkeeper66666** [comment]
> https://github.com/SunAhong1993/X2Paddle.git

可以了，非常感谢！！

**Comment by Dreamkeeper66666** [comment]
@SunAhong1993 请问一下这个转换是等价的吗，我刚刚试了下相同的输入(例如，全1的矩阵)，输出似乎不太一样诶。

**Comment by SunAhong1993** [comment]
> @SunAhong1993 请问一下这个转换是等价的吗，我刚刚试了下相同的输入(例如，全1的矩阵)，输出似乎不太一样诶。

查看原因后发现是Pad op操作出现部分问题，已修改部分代码，您可按照之前的方式重装X2Paddle，即可对齐

**Comment by Dreamkeeper66666** [comment]
> > @SunAhong1993 请问一下这个转换是等价的吗，我刚刚试了下相同的输入(例如，全1的矩阵)，输出似乎不太一样诶。
> 
> 查看原因后发现是Pad op操作出现部分问题，已修改部分代码，您可按照之前的方式重装X2Paddle，即可对齐

非常感谢，可以使用了。最后有个小问题。就是有报错我之前把输入的x2改成constant了，现在我改回tf.placeholder(tf.bool, shape=[3])后发现可以生成paddle参数，但是生成inference model的过程就会报错：
`The feeded_var_names[2]: 'x2' doesn't exist in pruned inference program. Please check whether 'x2' is a valid feed_var name, or remove it from feeded_var_names if 'x2' is not involved in the target_vars calculation.`
请问是inference program是不支持这个类型作为输入吗。谢谢

**Comment by SunAhong1993** [comment]
> 就是有报错我之前把输入的x2改成constant了，

你把你的pb模型发我看下
