### ISSUE TITLE
AssertionError: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

### ISSUE THREAD

**Issue by janoslim** [PaddlePaddle/X2Paddle#534]
Hello,

I used X2paddle to run my tensorflow model at paddle-lite.
I noticed an error when converting my tf model by x2paddle dynamic option
but static seems fine. Is is okay to be compiled to static only to use with paddle-lite? 
Thank you.

Framework: Tensorflow
Model Description: mobilenet_v1, classify
Link: [frozen_mobilenet_v1.pb.zip](https://github.com/PaddlePaddle/X2Paddle/files/6252038/frozen_mobilenet_v1.pb.zip)
Error Message:

```
2021-04-03 15:08:35,659 Dynamic-to-Static WARNING: <function to_tensor at 0x7fdee8180e18> doesn't have to be transformed to static function because it has been transformed before, it will be run as-is.
Fail to generate inference model! Problem happend while export inference model from python code '/home/janoslim/projects/DeepLearningModels/paddle/x2paddle_code.py';

===================Error Information===============
Traceback (most recent call last):
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')()
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/x2paddle/convert.py", line 256, in main
    define_input_shape, args.paddle_type)
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/x2paddle/convert.py", line 124, in tf2paddle
    mapper.paddle_graph.gen_model(save_dir)
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/x2paddle/core/program.py", line 245, in gen_model
    self.gen_dygraph_model(save_dir, jit_type)
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/x2paddle/core/program.py", line 304, in gen_dygraph_model
    raise e
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/x2paddle/core/program.py", line 300, in gen_dygraph_model
    self.dygraph2static(save_dir, input_shapes, input_types)
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/x2paddle/core/program.py", line 675, in dygraph2static
    paddle.jit.save(static_model, osp.join(save_dir, "inference_model/model"))
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/decorator.py", line 214, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/paddle/fluid/dygraph/jit.py", line 681, in save
    inner_input_spec)
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/decorator.py", line 214, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 189, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "paddle/x2paddle_code.py", line 94, in forward (* user code *)
        input = paddle.to_tensor(data=x0)
    File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/decorator.py", line 214, in fun
        return caller(func, *(extras + args), **kw)
    File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
        return wrapped_func(*args, **kwargs)
    File "/home/janoslim/projects/NPUDNN/paddle-lite/venv/lib/python3.6/site-packages/paddle/fluid/framework.py", line 224, in __impl__
        ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
    AssertionError: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.
```

**Comment by SunAhong1993** [comment]
The inference model can work well. You can set "paddle.disable_static()" in your code. Or you can move this issue to [PaddleLite repo](https://github.com/PaddlePaddle/Paddle-Lite). They will help you.

**Comment by janoslim** [comment]
Thank you! I am making some progress.
