### ISSUE TITLE
onnx模型转paddle时出错

### ISSUE THREAD

**Issue by zouzhuo777** [PaddlePaddle/X2Paddle#535]
模型来源：onnx
模型说明：ReXNet V1，用于手部关键点标注。 

转paddle模型时出错，生成的model.py文件中输出层axes参数初始化为None，但是在后续处理中要求这个参数为list。
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle/core/op_mapper.py", line 142, in save_inference_model
    inputs, outputs = model.x2paddle_net()
  File "pd_model_rexnet/model_with_code/model.py", line 1371, in x2paddle_net
    x2paddle_output = fluid.layers.squeeze(x2paddle_1379, axes=None, name='x2paddle_output')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 7490, in squeeze
    check_type(axes, 'axes', list, 'squeeze')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 96, in check_type
    (input_name, op_name, expected_type, type(input), extra_message))
TypeError: The type of 'axes' in squeeze must be <class 'list'>, but received <class 'NoneType'>.

**Comment by SunAhong1993** [comment]
你好，建议使用x2paddle1.0.1进行转换，如果还是出问题方便方便提供下onnx模型吗？

**Comment by zouzhuo777** [comment]
已解决，非常感谢！

**Comment by zouzhuo777** [comment]
感谢，已经解决了
