### ISSUE TITLE
onnx模型转成paddle报错

### ISSUE THREAD

**Issue by Jackson8888** [PaddlePaddle/X2Paddle#540]
模型用于目标检测

模型来源：
    模型vgg16_bn
    使用pytorch -> onnx, 在使用onnx转换成paddle时报错

Now translating model from onnx to paddle.
model ir_version: 6, op version: 9
shape inferencing ...
Warning: Unsupported operator adaptive_avg_pool2d. No schema registered for this operator.
Stopping at incomplete shape inference at adaptive_avg_pool2d: x2paddle_143
node inputs:
name: "x2paddle_141"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 1
      }
      dim {
        dim_value: 512
      }
      dim {
        dim_value: 16
      }
      dim {
        dim_value: 16
      }
    }
  }
}

name: "x2paddle_142"
type {
  tensor_type {
    elem_type: 7
    shape {
      dim {
        dim_value: 2
      }
    }
  }
}

node outputs:
name: "x2paddle_143"
type {
  tensor_type {
    elem_type: 0
  }
}

!!!!!!!!!!
Warning: Unsupported operator adaptive_avg_pool2d. No schema registered for this operator.
shape inferenced.
Traceback (most recent call last):
  File "/Users/baijunjie/.pyenv/versions/env/bin/x2paddle", line 10, in <module>
    sys.exit(main())
  File "/Users/baijunjie/.pyenv/versions/3.7.3/envs/env/lib/python3.7/site-packages/x2paddle/convert.py", line 264, in main
    onnx2paddle(args.model, args.save_dir, args.paddle_type)
  File "/Users/baijunjie/.pyenv/versions/3.7.3/envs/env/lib/python3.7/site-packages/x2paddle/convert.py", line 171, in onnx2paddle
    model = ONNXDecoder(model_path)
  File "/Users/baijunjie/.pyenv/versions/3.7.3/envs/env/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py", line 420, in __init__
    self.graph = ONNXGraph(onnx_model)
  File "/Users/baijunjie/.pyenv/versions/3.7.3/envs/env/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py", line 183, in __init__
    self.collect_value_infos()
  File "/Users/baijunjie/.pyenv/versions/3.7.3/envs/env/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py", line 381, in collect_value_infos
    TENSOR_TYPE_TO_NP_TYPE[item.type.tensor_type.elem_type],
KeyError: 0

**Comment by SunAhong1993** [comment]
方便把onnx模型发送到sunyanfang01@baidu.com吗？

**Comment by hong19860320** [comment]
我在转onnx的ssd-mobilenetv1模型到paddle模型也遇到这个问题。
[ssd_mobilenet_v1_10.onnx.zip](https://github.com/PaddlePaddle/X2Paddle/files/6415931/ssd_mobilenet_v1_10.onnx.zip)

**Comment by nissansz** [comment]
可以分享一下 vgg16_bn 的onnx模型吗？
