### ISSUE TITLE
Exception: Model is not supported yet.

### ISSUE THREAD

**Issue by ezekielqu** [PaddlePaddle/X2Paddle#554]
转换tensorflow的模型时，提示操作不支持，但是op表中现在已经支持这两个op

`========= 2 OPs are not supported yet ===========
========== BatchToSpaceND ============
========== SpaceToBatchND ============
Traceback (most recent call last):
  File "/home/senn/.conda/envs/envPaddle/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.2', 'console_scripts', 'x2paddle')())
  File "/home/senn/.conda/envs/envPaddle/lib/python3.7/site-packages/x2paddle-1.0.2-py3.7.egg/x2paddle/convert.py", line 249, in main
  File "/home/senn/.conda/envs/envPaddle/lib/python3.7/site-packages/x2paddle-1.0.2-py3.7.egg/x2paddle/convert.py", line 111, in tf2paddle
  File "/home/senn/.conda/envs/envPaddle/lib/python3.7/site-packages/x2paddle-1.0.2-py3.7.egg/x2paddle/op_mapper/dygraph/tf2paddle/tf_op_mapper.py", line 94, in __init__
Exception: Model is not supported yet.
`

x2paddle==1.0.2，paddle==2.0.2
附上模型
[test.zip](https://github.com/PaddlePaddle/X2Paddle/files/6375673/test.zip)

**Comment by wjj19950828** [comment]
这边新增了这两个op，请重装一下X2Paddle

然后输出下列命令

```
pip uninstall x2paddle
git clone https://github.com/PaddlePaddle/X2Paddle.git
cd X2Paddle
python setup.py install
```

**Comment by wjj19950828** [comment]
如果方便的话把模型对应repo链接也发一下可以吗，谢谢啦！
