### ISSUE TITLE
【论文复现营】已安装“detach”但提示【AttributeError: 'collections.OrderedDict' object has no attribute 'detach'】

### ISSUE THREAD

**Issue by wyxogo** [PaddlePaddle/X2Paddle#578]
模型来源： Pytorch
模型说明： 目标检测detr
转换过程出错提示如下：
```
(paddle) E:\Github\detr>pip show detach
Name: detach
Version: 1.0
Summary: Fork and detach the current processe.
Home-page: https://github.com/bluedragonx/detach
Author: Ryan Bourgeois
Author-email: bluedragonx@gmail.com
License: BSD-derived
Location: d:\app\miniconda\envs\paddle\lib\site-packages
Requires:
Required-by:

(paddle) E:\Github\detr>x2paddle --convert_torch_project --project_dir='./' --save_dir='./x2paddle/detr' --pretrain_model="./pth/detr-r50-dc5-f0fb7ef5.pth"
paddle.__version__ = 2.0.2
Traceback (most recent call last):
  File "d:\app\miniconda\envs\paddle\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\app\miniconda\envs\paddle\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\APP\miniconda\envs\paddle\Scripts\x2paddle.exe\__main__.py", line 7, in <module>
  File "d:\app\miniconda\envs\paddle\lib\site-packages\x2paddle\convert.py", line 270, in main
    convert_torch(args)
  File "d:\app\miniconda\envs\paddle\lib\site-packages\x2paddle\project_convertor\pytorch\convert.py", line 110, in main
    convert_params(params_path)
  File "d:\app\miniconda\envs\paddle\lib\site-packages\x2paddle\project_convertor\pytorch\convert.py", line 89, in convert_params
    new_params[k] = v.detach().numpy()
AttributeError: 'collections.OrderedDict' object has no attribute 'detach'
```

**Comment by SunAhong1993** [comment]
当前转换的模型文件只支持：参数名-参数值的键值对；若出现包含optimizer或者scheduler等信息的的模型暂时无法转换，建议把这类模型的optimier的optimizer去掉，只保留参数名-参数值的键值对。

**Comment by SSyangguang** [comment]
> 
> 
> 当前转换的模型文件只支持：参数名-参数值的键值对；若出现包含optimizer或者scheduler等信息的的模型暂时无法转换，建议把这类模型的optimier的optimizer去掉，只保留参数名-参数值的键值对。

请问可以用一个例子解释一下吗？刚开始接触paddle，不太明白去掉optimizer具体是在什么位置去掉

**Comment by SunAhong1993** [comment]
> > 当前转换的模型文件只支持：参数名-参数值的键值对；若出现包含optimizer或者scheduler等信息的的模型暂时无法转换，建议把这类模型的optimier的optimizer去掉，只保留参数名-参数值的键值对。
> 
> 请问可以用一个例子解释一下吗？刚开始接触paddle，不太明白去掉optimizer具体是在什么位置去掉

这里是针对PyTorch而言，你重新保存为只包含模型参数的模型即可，过程如下：
```
import torch
pth = torch.load("detr-r50-e632da11.pth")
torch.save(pth["model"],  "detr_new.pth")
```
