### ISSUE TITLE
【论文复现营】转换DETR源码时报错

### ISSUE THREAD

**Issue by hrdwsong** [PaddlePaddle/X2Paddle#591]
请说明模型的来源，模型类型（例如图像分类、目标检测等）  
目标检测，DETR官方源代码，pytorch版本
如有原模型文件或github链接，如方便可一并附上，方便开发人员分析。
https://github.com/facebookresearch/detr
**为了便于开发人员快速定位原因，建议将模型文件上传（或通过百度网盘分享）**

## 示例

模型来源： pytorch
模型说明： https://github.com/facebookresearch/detr
模型文件： https://dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth
转换过程出错提示如下：
```
(pt2pd) PS F:\FormalDL\论文复现\复现04_End-to-End Object Detection with Transformers> x2paddle --convert_torch_project --project_dir=detr-master --save_dir=detr_2paddle --pretrain_model=detr-master/detr-r50-e632da11.pth
d:\programdata\anaconda3\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
paddle.__version__ = 2.0.2
Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\Scripts\x2paddle.exe\__main__.py", line 7, in <module>
  File "d:\programdata\anaconda3\lib\site-packages\x2paddle\convert.py", line 270, in main
    convert_torch(args)
  File "d:\programdata\anaconda3\lib\site-packages\x2paddle\project_convertor\pytorch\convert.py", line 110, in main
    convert_params(params_path)
  File "d:\programdata\anaconda3\lib\site-packages\x2paddle\project_convertor\pytorch\convert.py", line 89, in convert_params
    new_params[k] = v.detach().numpy()
AttributeError: 'collections.OrderedDict' object has no attribute 'detach'
```

**Comment by SunAhong1993** [comment]
参见[issue](https://github.com/PaddlePaddle/X2Paddle/issues/578)。
