### ISSUE TITLE
x2paddle 将.pb转化pd_model

### ISSUE THREAD

**Issue by bin0612** [PaddlePaddle/X2Paddle#598]
OCR

尝试通过
x2paddle --framework=tensorflow --model=tf1_14train_weight.pb --save_dir=pd_model
将.pb转化pd_model出现错误。

错误如下：
Traceback (most recent call last):
  File "/home/wuzhou/.local/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/home/wuzhou/.local/lib/python3.7/site-packages/x2paddle/convert.py", line 278, in main
    args.paddle_type)
  File "/home/wuzhou/.local/lib/python3.7/site-packages/x2paddle/convert.py", line 128, in tf2paddle
    model = TFDecoder(model_path, define_input_shape=define_input_shape)
  File "/home/wuzhou/.local/lib/python3.7/site-packages/x2paddle/decoder/tf_decoder.py", line 353, in __init__
    self.tf_graph.build()
  File "/home/wuzhou/.local/lib/python3.7/site-packages/x2paddle/decoder/tf_decoder.py", line 175, in build
    self._remove_identity_node()
  File "/home/wuzhou/.local/lib/python3.7/site-packages/x2paddle/decoder/tf_decoder.py", line 281, in _remove_identity_node
    self.remove_node(node_name)
  File "/home/wuzhou/.local/lib/python3.7/site-packages/x2paddle/decoder/tf_decoder.py", line 218, in remove_node
    idx = self.topo_sort.index(node_name)
ValueError: 'LSTM_1_while_Merge' is not in list

**Comment by wjj19950828** [comment]
方便把模型以及对应repo发我一份吗，放到百度网盘即可
