### ISSUE TITLE
【论文复现营】TypeError: __init__() got an unexpected keyword argument 'affine'

### ISSUE THREAD

**Issue by ArlanCooper** [PaddlePaddle/X2Paddle#599]
StarGAN方法，图像翻译，主要是X2Paddle 的 demo，讲解的例子。
如有原模型文件或github链接，如方便可一并附上，方便开发人员分析。
https://github.com/yunjey/stargan

模型来源： pytorch
模型说明： 图像翻译，其相应repo为 https://github.com/yunjey/stargan
转换过程没有问题，但是运行paddlepaddle命令之后，报错:

```
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main(config)
  File "main.py", line 32, in main
    solver = Solver(celeba_loader, rafd_loader, config)
  File "D:\360下载\paper_reproduct\x2paddle\test\paddle_project\solver.py", line 55, in __init__
    self.build_model()
  File "D:\360下载\paper_reproduct\x2paddle\test\paddle_project\solver.py", line 62, in build_model
    self.G = Generator(self.g_conv_dim, self.c_dim, self.g_repeat_num)
  File "D:\360下载\paper_reproduct\x2paddle\test\paddle_project\model.py", line 31, in __init__
    layers.append(nn.InstanceNorm2D(conv_dim, affine=True))
TypeError: __init__() got an unexpected keyword argument 'affine'
```
环境是windows
paddlepaddle版本：Version: 2.0.2
x2paddle 版本: Version: 1.2.0
torch 版本: Version: 1.8.1+cpu

**Comment by SunAhong1993** [comment]
由于之前只于Linux\MacOS上测试过，我们将在近期于Windows上测试是否存在相关问题，建议想使用LInux进行转换，或手动把各处`affine=True`去掉。

**Comment by SunAhong1993** [comment]
> 由于之前只于Linux\MacOS上测试过，我们将在近期于Windows上测试是否存在相关问题，建议使用LInux进行转换，或手动把各处`affine=True`去掉。

这边尝试过Windows未出现此类问题，建议使用LInux进行转换，或手动把各处`affine=True`去掉。

**Comment by ArlanCooper** [comment]
> > 由于之前只于Linux\MacOS上测试过，我们将在近期于Windows上测试是否存在相关问题，建议使用LInux进行转换，或手动把各处`affine=True`去掉。
> 
> 这边尝试过Windows未出现此类问题，建议使用LInux进行转换，或手动把各处`affine=True`去掉。

好的，已经去掉了，谢谢，我查了paddlepaddle.nn.InstanceNorm2D的接口文档，发现是没有affine 参数的，所以，您说其他地方没报错，不应该的吧？

**Comment by SunAhong1993** [comment]
> > > 由于之前只于Linux\MacOS上测试过，我们将在近期于Windows上测试是否存在相关问题，建议使用LInux进行转换，或手动把各处`affine=True`去掉。
> > 
> > 
> > 这边尝试过Windows未出现此类问题，建议使用LInux进行转换，或手动把各处`affine=True`去掉。
> 
> 好的，已经去掉了，谢谢，我查了paddlepaddle.nn.InstanceNorm2D的接口文档，发现是没有affine 参数的，所以，您说其他地方没报错，不应该的吧？

我们这边转换过程中，对应会把`affine=True`去掉，目前无法排除啊您那边什么原因，导致这一参数在转换工程中未去掉。
