### ISSUE TITLE
转换模型出错：Now translating model from pytorch to paddle. Could not get name of python class object

### ISSUE THREAD

**Issue by WAS2001** [PaddlePaddle/X2Paddle#615]
模型来源： pytorch
模型说明： 图像分割模型，对应代码地址为：https://github.com/DengPingFan/PraNet
模型：
链接：https://pan.baidu.com/s/1VoWdBUnLgPXzqKyRv0-n4A 
          提取码：gfwx 

版本为python:3.8.5
torch：1.7.1

转换代码：
opt = parser.parse_args()
model = PraNet()
model = nn.DataParallel(model)
model.load_state_dict(torch.load(opt.pth_path),False)
model.cuda()
model.eval()

from x2paddle.convert import pytorch2paddle

input_data = torch.rand(1, 3, 352, 352)
pytorch2paddle(module="model",
               save_dir="utils",
               jit_type="trace",
               input_examples=[torch.tensor(input_data)])

转换过程出错提示如下：
```
['1', '7', '1']
Now translating model from pytorch to paddle.
Could not get name of python class object
```

**Comment by xiaobu404** [comment]
如果方便的话，麻烦发一下模型的下载链接！

**Comment by SunAhong1993** [comment]
![image](https://user-images.githubusercontent.com/48579383/121487254-7d8cee00-ca04-11eb-99f3-1bc8221185e5.png)
你的model传成了一个字符串。

**Comment by WAS2001** [comment]
> ![图像](https://user-images.githubusercontent.com/48579383/121487254-7d8cee00-ca04-11eb-99f3-1bc8221185e5.png)
> 你的模特传成为一个字符串。

非常感谢，此问题已经解决。
但现在报错./snapshots\x2paddle_code.py:2097: DeprecationWarning: invalid escape sequence \z
'utf-8' codec can't decode byte 0xb9 in position 6851: invalid start byte

这个转义该如何解决。应用了转义字符仍然在自动生成的X2paddle_code.py中无法正确转义

**Comment by SunAhong1993** [comment]
> > ![图像](https://user-images.githubusercontent.com/48579383/121487254-7d8cee00-ca04-11eb-99f3-1bc8221185e5.png)
> > 你的模特传成为一个字符串。
> 
> 非常感谢，此问题已经解决。
> 但现在报错./snapshots\x2paddle_code.py:2097: DeprecationWarning: invalid escape sequence \z
> 'utf-8' codec can't decode byte 0xb9 in position 6851: invalid start byte
> 
> 这个转义该如何解决。应用了转义字符仍然在自动生成的X2paddle_code.py中无法正确转义

建议使用最新的X2Paddle (pip install x2paddle==1.2.2)，搭配Paddle2.1.0

**Comment by WAS2001** [comment]
> > > ![图像](https://user-images.githubusercontent.com/48579383/121487254-7d8cee00-ca04-11eb-99f3-1bc8221185e5.png)
> > > 你的模特传一个字符串。
> > 
> > 
> > 非常感谢，这个问题已经解决。
> > 但现在报错。/snapshots\x2paddle_code.py:2097: DeprecationWarning: invalid escape sequence \z 
> > 'utf-8' codec can't decode byte 0xb9 in position 6851: invalid start byte
> > 这个转义方法解决。 应用了转义字符仍然在自动生成的X2paddle_code.py中无法正确转
> 
> 建议使用最新的X2Paddle (pip install x2paddle==1.2.2)，搭配Paddle2.1.0

你好，它现在报这些错是什么原因？ 个人认为安装最新版本之后，它只是把报错绕过去了，实际还是没解决路径问题？
pd_model_trace\x2paddle_code.py:1077: DeprecationWarning: invalid escape sequence \z
  params = paddle.load('D:\bszl\zhuanhuan\pd_model_trace\model.pdparams')
Fail to generate inference model! Problem happend while export inference model from python code 'D:\bszl\zhuanhuan\pd_model_trace\x2paddle_code.py';
===================Error Information===============
Traceback (most recent call last):
  File "testpaddle.py", line 40, in <module>
    pytorch2paddle(module=model,
  File "C:\ProgramData\Anaconda3\lib\site-packages\x2paddle\convert.py", line 199, in pytorch2paddle
    mapper.paddle_graph.gen_model(save_dir, jit_type=jit_type)
  File "C:\ProgramData\Anaconda3\lib\site-packages\x2paddle\core\program.py", line 279, in gen_model
    raise e
  File "C:\ProgramData\Anaconda3\lib\site-packages\x2paddle\core\program.py", line 273, in gen_model
    self.dygraph2static(save_dir, input_shapes, input_types)
  File "C:\ProgramData\Anaconda3\lib\site-packages\x2paddle\core\program.py", line 538, in dygraph2static
    paddle.jit.save(static_model,
  File "<decorator-gen-60>", line 2, in save
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\jit.py", line 680, in save
    concrete_program = static_func.concrete_program_specify_input_spec(
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 487, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 698, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "<decorator-gen-58>", line 2, in from_func_spec
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 189, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "pd_model_trace\x2paddle_code.py", line 437, in forward (* user code *)
        x126 = paddle.split(x=x125, axis=x89, num_or_sections=27)
    File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\tensor\manipulation.py", line 494, in split
        return paddle.fluid.layers.split(
    File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\layers\nn.py", line 4922, in split
        assert input_shape[dim] % num_or_sections ==0, \
    AssertionError: The input's size along the split dimension must be evenly divisible by Attr(num_or_sections). But 27 is not evenly divisible by 104.
