### ISSUE TITLE
FaceNet(Inception Resnet V1 model）can't be converted from onnx to paddle!

### ISSUE THREAD

**Issue by rolfma19** [PaddlePaddle/X2Paddle#634]
```shell
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
paddle.__version__ = 2.1.0
Now translating model from onnx to paddle.
model ir_version: 6, op version: 9
shape inferencing ...
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 9, automatically treated as op_set: 9.

========= 1 OPs are not supported yet ===========
========== ReduceL2 ============
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/x2paddle", line 11, in <module>
    load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 264, in main
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 172, in onnx2paddle
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/op_mapper/dygraph/onnx2paddle/onnx_op_mapper.py", line 32, in __init__
Exception: Model is not supported yet.
```

**Comment by wjj19950828** [comment]
您好，麻烦提供一下ONNX模型吧

**Comment by rolfma** [comment]
模型见附件，期待您的回复！




马万皓
***@***.***

武汉工程大学
信息工程


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/X2Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 下午3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/X2Paddle] FaceNet(Inception Resnet V1 model）can't be converted from onnx to paddle! (#634)





 
您好，麻烦提供一下ONNX模型吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

faceNet.rar (83.57M, 2021年08月01日 15:54 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=2632396207b3f198a0e4c0511661054d5e505c5401520f564b020f00564c0306505614035500524f505300035153015553500156306a370407515c2c551519100740395f&code=f29b0a7b

**Comment by rolfma19** [comment]
> 您好，麻烦提供一下ONNX模型吧
模型见如下链接，期待您的回复！
链接：https://pan.baidu.com/s/10PVy_5I2G0wpTIj_v-iZfQ 
提取码：s32s

**Comment by wjj19950828** [comment]
麻烦直接提供一下onnx模型吧，不要rar压缩

**Comment by rolfma19** [comment]
> 麻烦直接提供一下onnx模型吧，不要rar压缩

已修改格式，期待您的回复，谢谢！
链接：https://pan.baidu.com/s/1QJXSvHYavI8y3XHzOY53xQ 
提取码：813p
