### ISSUE TITLE
yolov5是否支持转换为paddle

### ISSUE THREAD

**Issue by duantangjin** [PaddlePaddle/X2Paddle#640]
我在转换过程中，已经将yolov5模型转换为onnx模型，但始终无法将转换出来的onnx模型转为paddle。

**Comment by wjj19950828** [comment]
麻烦提供一下ONNX模型以及对应yolov5的repo吧

**Comment by duantangjin** [comment]
> 麻烦提供一下ONNX模型以及对应yolov5的repo吧
我并没有repo,我只是获得了团队工作中的pytorch模型，而且我的工作都是在本地和服务器上完成的，我试过给您发邮件，但是被退回了。

**Comment by wjj19950828** [comment]
直接把模型放到评论吧

**Comment by duantangjin** [comment]
> 直接把模型放到评论吧

> 模型上传不了，我再试试其他办法吧。谢谢！

**Comment by duantangjin** [comment]
可以百度网盘链接发给你么？

**Comment by wjj19950828** [comment]
可以的

**Comment by duantangjin** [comment]
链接：https://pan.baidu.com/s/1so5V3jIaao_lEgjUQdZ-Sg 
提取码：qlzp

**Comment by duantangjin** [comment]
> 可以的

您好，请问转换有结果了吗？

**Comment by yeliang2258** [comment]
> 链接：https://pan.baidu.com/s/1so5V3jIaao_lEgjUQdZ-Sg
> 提取码：qlzp

您好，您提供的model使用onnxruntime跑不通，应该是导出onnx时某一步有问题。
此外github上yolov5的模型我尝试了是可以转换成功的，具体您可以参考，https://github.com/ultralytics/yolov5/issues/251
如果还是有问题，请您导出一个正确的模型，onnxruntime测试通过之后更新给我们，谢谢！

**Comment by duantangjin** [comment]
> > 链接：[https](https://pan.baidu.com/s/1so5V3jIaao_lEgjUQdZ-Sg) 
> > ://pan.baidu.com/s/1so5V3jIaao_​​lEgjUQdZ-Sg提取码：qlzp
> 
> 您好，您提供的模型使用onnxruntime跑不通，应该是导出onnx时有问题。
> 另外github上yolov5的模型我尝试了是可以转换成功的，具体可以参考，[ultalytics/yolov5#251](https://github.com/ultralytics/yolov5/issues/251)
> 如果还是有问题，请您导出一个正确的模型，onnxruntime测试通过之后更新给我们，谢谢！

谢谢您啊!那您可以帮忙将我的pytorch模型转为paddle模型么？

**Comment by yeliang2258** [comment]
> > > 链接：[https](https://pan.baidu.com/s/1so5V3jIaao_lEgjUQdZ-Sg)
> > > ://pan.baidu.com/s/1so5V3jIaao_​​lEgjUQdZ-Sg提取码：qlzp
> > 
> > 
> > 您好，您提供的模型使用onnxruntime跑不通，应该是导出onnx时有问题。
> > 另外github上yolov5的模型我尝试了是可以转换成功的，具体可以参考，[ultalytics/yolov5#251](https://github.com/ultralytics/yolov5/issues/251)
> > 如果还是有问题，请您导出一个正确的模型，onnxruntime测试通过之后更新给我们，谢谢！
> 
> 谢谢您啊!那您可以帮忙将我的pytorch模型转为paddle模型么？

您先将pytorch的模型导出到onnx，然后使用onnxruntime测试，如果可以跑通，再使用x2paddle进行转换。

**Comment by duantangjin** [comment]
> > > > 链接：[https](https://pan.baidu.com/s/1so5V3jIaao_lEgjUQdZ-Sg)
> > > > ://pan.baidu.com/s/1so5V3jIaao_​​lEgjUQdZ-Sg提取码：qlzp
> > > 
> > > 
> > > 您好，您提供的模型使用onnxruntime跑不通，应该是导出onnx时有问题。
> > > 另外github上yolov5的模型我尝试了是可以转换成功的，具体可以参考，[ultalytics/yolov5#251](https://github.com/ultralytics/yolov5/issues/251)
> > > 如果还是有问题，请您导出一个正确的模型，onnxruntime测试通过之后更新给我们，谢谢！
> > 
> > 
> > 谢谢您啊!那您可以帮忙将我的pytorch模型转为paddle模型么？
> 
> 您先将pytorch的模型导出到onnx，然后使用onnxruntime测试，如果可以跑通，再使用x2paddle进行转换。

我现在已经将pytorch模型转为onnx，onnxruntime测试也已经通过，但是转paddle的时候仍有报错，我希望得到您的帮助。onnx
![报错信息](https://user-images.githubusercontent.com/49987390/126469225-f4860c4e-f6e7-4d33-b56c-e6d5b0e03ac1.png)
模型连接：链接：https://pan.baidu.com/s/1vBer6Fril5H5KUcKPnaAgg 
提取码：1wsl

**Comment by yeliang2258** [comment]
> > > > > 链接：[https](https://pan.baidu.com/s/1so5V3jIaao_lEgjUQdZ-Sg)
> > > > > ://pan.baidu.com/s/1so5V3jIaao_​​lEgjUQdZ-Sg提取码：qlzp
> > > > 
> > > > 
> > > > 您好，您提供的模型使用onnxruntime跑不通，应该是导出onnx时有问题。
> > > > 另外github上yolov5的模型我尝试了是可以转换成功的，具体可以参考，[ultalytics/yolov5#251](https://github.com/ultralytics/yolov5/issues/251)
> > > > 如果还是有问题，请您导出一个正确的模型，onnxruntime测试通过之后更新给我们，谢谢！
> > > 
> > > 
> > > 谢谢您啊!那您可以帮忙将我的pytorch模型转为paddle模型么？
> > 
> > 
> > 您先将pytorch的模型导出到onnx，然后使用onnxruntime测试，如果可以跑通，再使用x2paddle进行转换。
> 
> 我现在已经将pytorch模型转为onnx，onnxruntime测试也已经通过，但是转paddle的时候仍有报错，我希望得到您的帮助。onnx
> ![报错信息](https://user-images.githubusercontent.com/49987390/126469225-f4860c4e-f6e7-4d33-b56c-e6d5b0e03ac1.png)
> 模型连接：链接：https://pan.baidu.com/s/1vBer6Fril5H5KUcKPnaAgg
> 提取码：1wsl

您的模型确实比较奇怪，有一些操作是可以合并简化的，您有验证过onnruntime和你pytorch的model跑的结果有没有误差？里面的一些操作能否做简化，比如下图的操作？导出onnx的python代码也请提供以下。
![image](https://user-images.githubusercontent.com/30516196/126651163-8b784a03-6956-45de-a1eb-c3d5260bc663.png)

**Comment by duantangjin** [comment]
> > > > > > 链接：[https](https://pan.baidu.com/s/1so5V3jIaao_lEgjUQdZ-Sg)
> > > > > > ://pan.baidu.com/s/1so5V3jIaao_​​lEgjUQdZ-Sg提取码：qlzp
> > > > > 
> > > > > 
> > > > > 您好，您提供的模型使用onnxruntime跑不通，应该是导出onnx时有问题。
> > > > > 另外github上yolov5的模型我尝试了是可以转换成功的，具体可以参考，[ultalytics/yolov5#251](https://github.com/ultralytics/yolov5/issues/251)
> > > > > 如果还是有问题，请您导出一个正确的模型，onnxruntime测试通过之后更新给我们，谢谢！
> > > > 
> > > > 
> > > > 谢谢您啊!那您可以帮忙将我的pytorch模型转为paddle模型么？
> > > 
> > > 
> > > 您先将pytorch的模型导出到onnx，然后使用onnxruntime测试，如果可以跑通，再使用x2paddle进行转换。
> > 
> > 
> > 我现在已经将pytorch模型转为onnx，onnxruntime测试也已经通过，但是转paddle的时候仍有报错，我希望得到您的帮助。onnx
> > ![报错信息](https://user-images.githubusercontent.com/49987390/126469225-f4860c4e-f6e7-4d33-b56c-e6d5b0e03ac1.png)
> > 模型连接：链接：https://pan.baidu.com/s/1vBer6Fril5H5KUcKPnaAgg
> > 提取码：1wsl
> 
> 您的模型确实比较奇怪，有一些操作是可以合并简化的，您有验证过onnruntime和你pytorch的model跑的结果有没有误差？里面的一些操作能否做简化，比如下图的操作？导出onnx的python代码也请提供以下。
> ![image](https://user-images.githubusercontent.com/30516196/126651163-8b784a03-6956-45de-a1eb-c3d5260bc663.png)

在模型转换这方面我不是很有经验，非常感谢您的帮助，我现在将pytorch模型（best.pt）已及我转换的onnx模型和转换代码发给您。谢谢！链接：https://pan.baidu.com/s/1tB1iBvYj8jKrLt_YDz9LFw 
提取码：fzp4

**Comment by yeliang2258** [comment]
> > > > > > > 链接：[https](https://pan.baidu.com/s/1so5V3jIaao_lEgjUQdZ-Sg)
> > > > > > > ://pan.baidu.com/s/1so5V3jIaao_​​lEgjUQdZ-Sg提取码：qlzp
> > > > > > 
> > > > > > 
> > > > > > 您好，您提供的模型使用onnxruntime跑不通，应该是导出onnx时有问题。
> > > > > > 另外github上yolov5的模型我尝试了是可以转换成功的，具体可以参考，[ultalytics/yolov5#251](https://github.com/ultralytics/yolov5/issues/251)
> > > > > > 如果还是有问题，请您导出一个正确的模型，onnxruntime测试通过之后更新给我们，谢谢！
> > > > > 
> > > > > 
> > > > > 谢谢您啊!那您可以帮忙将我的pytorch模型转为paddle模型么？
> > > > 
> > > > 
> > > > 您先将pytorch的模型导出到onnx，然后使用onnxruntime测试，如果可以跑通，再使用x2paddle进行转换。
> > > 
> > > 
> > > 我现在已经将pytorch模型转为onnx，onnxruntime测试也已经通过，但是转paddle的时候仍有报错，我希望得到您的帮助。onnx
> > > ![报错信息](https://user-images.githubusercontent.com/49987390/126469225-f4860c4e-f6e7-4d33-b56c-e6d5b0e03ac1.png)
> > > 模型连接：链接：https://pan.baidu.com/s/1vBer6Fril5H5KUcKPnaAgg
> > > 提取码：1wsl
> > 
> > 
> > 您的模型确实比较奇怪，有一些操作是可以合并简化的，您有验证过onnruntime和你pytorch的model跑的结果有没有误差？里面的一些操作能否做简化，比如下图的操作？导出onnx的python代码也请提供以下。
> > ![image](https://user-images.githubusercontent.com/30516196/126651163-8b784a03-6956-45de-a1eb-c3d5260bc663.png)
> 
> 在模型转换这方面我不是很有经验，非常感谢您的帮助，我现在将pytorch模型（best.pt）已及我转换的onnx模型和转换代码发给您。谢谢！链接：https://pan.baidu.com/s/1tB1iBvYj8jKrLt_YDz9LFw
> 提取码：fzp4

您试试这样导出
#coding: utf-8
import torch
import torchvision

# 指定输入大小的shape
dummy_input = torch.randn(1, 3, 224, 224)

# 构建pytorch model，并载入模型参数
resnet18 = torchvision.models.resnet18(pretrained=True)

# 导出resnet18.onnx模型文件
torch.onnx.export(resnet18, dummy_input, "resnet18.onnx",verbose=True)

**Comment by yeliang2258** [comment]
> > > > > > > 链接：[https](https://pan.baidu.com/s/1so5V3jIaao_lEgjUQdZ-Sg)
> > > > > > > ://pan.baidu.com/s/1so5V3jIaao_​​lEgjUQdZ-Sg提取码：qlzp
> > > > > > 
> > > > > > 
> > > > > > 您好，您提供的模型使用onnxruntime跑不通，应该是导出onnx时有问题。
> > > > > > 另外github上yolov5的模型我尝试了是可以转换成功的，具体可以参考，[ultalytics/yolov5#251](https://github.com/ultralytics/yolov5/issues/251)
> > > > > > 如果还是有问题，请您导出一个正确的模型，onnxruntime测试通过之后更新给我们，谢谢！
> > > > > 
> > > > > 
> > > > > 谢谢您啊!那您可以帮忙将我的pytorch模型转为paddle模型么？
> > > > 
> > > > 
> > > > 您先将pytorch的模型导出到onnx，然后使用onnxruntime测试，如果可以跑通，再使用x2paddle进行转换。
> > > 
> > > 
> > > 我现在已经将pytorch模型转为onnx，onnxruntime测试也已经通过，但是转paddle的时候仍有报错，我希望得到您的帮助。onnx
> > > ![报错信息](https://user-images.githubusercontent.com/49987390/126469225-f4860c4e-f6e7-4d33-b56c-e6d5b0e03ac1.png)
> > > 模型连接：链接：https://pan.baidu.com/s/1vBer6Fril5H5KUcKPnaAgg
> > > 提取码：1wsl
> > 
> > 
> > 您的模型确实比较奇怪，有一些操作是可以合并简化的，您有验证过onnruntime和你pytorch的model跑的结果有没有误差？里面的一些操作能否做简化，比如下图的操作？导出onnx的python代码也请提供以下。
> > ![image](https://user-images.githubusercontent.com/30516196/126651163-8b784a03-6956-45de-a1eb-c3d5260bc663.png)
> 
> 在模型转换这方面我不是很有经验，非常感谢您的帮助，我现在将pytorch模型（best.pt）已及我转换的onnx模型和转换代码发给您。谢谢！链接：https://pan.baidu.com/s/1tB1iBvYj8jKrLt_YDz9LFw
> 提取码：fzp4

您试试这样：
dummy_input = torch.randn(1, 3, 640, 640)
torch.onnx.export(model, dummy_input, "resnet18.onnx",verbose=True)

**Comment by duantangjin** [comment]
> > > > > > > > 链接：[https](https://pan.baidu.com/s/1so5V3jIaao_lEgjUQdZ-Sg)
> > > > > > > > ://pan.baidu.com/s/1so5V3jIaao_​​lEgjUQdZ-Sg提取码：qlzp
> > > > > > > 
> > > > > > > 
> > > > > > > 您好，您提供的模型使用onnxruntime跑不通，应该是导出onnx时有问题。
> > > > > > > 另外github上yolov5的模型我尝试了是可以转换成功的，具体可以参考，[ultalytics/yolov5#251](https://github.com/ultralytics/yolov5/issues/251)
> > > > > > > 如果还是有问题，请您导出一个正确的模型，onnxruntime测试通过之后更新给我们，谢谢！
> > > > > > 
> > > > > > 
> > > > > > 谢谢您啊!那您可以帮忙将我的pytorch模型转为paddle模型么？
> > > > > 
> > > > > 
> > > > > 您先将pytorch的模型导出到onnx，然后使用onnxruntime测试，如果可以跑通，再使用x2paddle进行转换。
> > > > 
> > > > 
> > > > 我现在已经将pytorch模型转为onnx，onnxruntime测试也已经通过，但是转paddle的时候仍有报错，我希望得到您的帮助。onnx
> > > > ![报错信息](https://user-images.githubusercontent.com/49987390/126469225-f4860c4e-f6e7-4d33-b56c-e6d5b0e03ac1.png)
> > > > 模型连接：链接：https://pan.baidu.com/s/1vBer6Fril5H5KUcKPnaAgg
> > > > 提取码：1wsl
> > > 
> > > 
> > > 您的模型确实比较奇怪，有一些操作是可以合并简化的，您有验证过onnruntime和你pytorch的model跑的结果有没有误差？里面的一些操作能否做简化，比如下图的操作？导出onnx的python代码也请提供以下。
> > > ![image](https://user-images.githubusercontent.com/30516196/126651163-8b784a03-6956-45de-a1eb-c3d5260bc663.png)
> > 
> > 
> > 在模型转换这方面我不是很有经验，非常感谢您的帮助，我现在将pytorch模型（best.pt）已及我转换的onnx模型和转换代码发给您。谢谢！链接：https://pan.baidu.com/s/1tB1iBvYj8jKrLt_YDz9LFw
> > 提取码：fzp4
> 
> 您试试这样：
> dummy_input = torch.randn(1, 3, 640, 640)
> torch.onnx.export(model, dummy_input, "resnet18.onnx",verbose=True)

按照您说的改完以后我去进行onnxruntime时报错：
Traceback (most recent call last):
  File "F:/Python/paddle/pytorchToPaddle_yolov5/verify.py", line 9, in <module>
    ort_session = ort.InferenceSession('yolov5.onnx')
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 310, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from yolov5.onnx failed:Node (Mul_1322) Op (Mul) [ShapeInferenceError] Incompatible dimensions

在转paddle时报错：
![Uploading 报错信息.png…]()

**Comment by yeliang2258** [comment]
> 链接：https
> ://pan.baidu.com/s/1so5V3jIaao_​​lEgjUQdZ-Sg提取码：qlzp
> 
> 您好，您提供的模型使用onnxruntime跑不通，应该是导出onnx时有问题。
> 另外github上yolov5的模型我尝试了是可以转换成功的，具体可以参考，ultalytics/yolov5#251
> 如果还是有问题，请您导出一个正确的模型，onnxruntime测试通过之后更新给我们，谢谢！
> 
> 谢谢您啊!那您可以帮忙将我的pytorch模型转为paddle模型么？
> 
> 您先将pytorch的模型导出到onnx，然后使用onnxruntime测试，如果可以跑通，再使用x2paddle进行转换。
> 
> 我现在已经将pytorch模型转为onnx，onnxruntime测试也已经通过，但是转paddle的时候仍有报错，我希望得到您的帮助。onnx
> 
> 模型连接：链接：https://pan.baidu.com/s/1vBer6Fril5H5KUcKPnaAgg
> 提取码：1wsl
> 
> 您的模型确实比较奇怪，有一些操作是可以合并简化的，您有验证过onnruntime和你pytorch的model跑的结果有没有误差？里面的一些操作能否做简化，比如下图的操作？导出onnx的python代码也请提供以下。
> 
> 
> 在模型转换这方面我不是很有经验，非常感谢您的帮助，我现在将pytorch模型（best.pt）已及我转换的onnx模型和转换代码发给您。谢谢！链接：https://pan.baidu.com/s/1tB1iBvYj8jKrLt_YDz9LFw
> 提取码：fzp4
> 
> 您试试这样：
> dummy_input = torch.randn(1, 3, 640, 640)
> torch.onnx.export(model, dummy_input, "resnet18.onnx",verbose=True)
> 
> 按照您说的改完以后我去进行onnxruntime时报错：
> Traceback (most recent call last):
> File "F:/Python/paddle/pytorchToPaddle_yolov5/verify.py", line 9, in
> ort_session = ort.InferenceSession('yolov5.onnx')
> File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 283, in init
> self._create_inference_session(providers, provider_options, disabled_optimizers)
> File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 310, in _create_inference_session
> sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
> onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from yolov5.onnx failed:Node (Mul_1322) Op (Mul) [ShapeInferenceError] Incompatible dimensions
> 
> 在转paddle时报错：

建议您先检查一下您的模型，检查网络是否合理

**Comment by litao-zhx** [comment]
你好，请问你paddle推理yolov5实现了吗？最近我也在研究这个，可以交流一下吗？
