### ISSUE TITLE
pytorch模型Conv2DTranspose转换报错

### ISSUE THREAD

**Issue by jianganbai** [PaddlePaddle/X2Paddle#641]
我在进行SfMlearner的预训练模型转换时，模型参数可以正常转化，网络代码也可以正常生成，但在生成网络代码时出现报错。

报错信息指出output_padding参数转换错误，整个网络中仅Conv2DTranspose函数具有output_padding项，故怀疑是该函数的转化出错。

尽管出现了报错，转换后的模型参数和网络代码均可以正常使用，即可将转换后的模型参数加载进x2paddle_code.py定义的网络，并能正常进行预测。

模型来源： Pytorch
模型说明： 图像深度估计模型，源repo为https://github.com/ClementPinard/SfmLearner-Pytorch
模型转换代码及预训练参数： 链接: https://pan.baidu.com/s/1_-QGiZG29NXGRzmcDyxCwA 提取码: ugfi
版本：paddle 2.1，paddlehub 2.1

模型转换时的输出：
```
Now translating model from pytorch to paddle.
Model optimizing ...
trace_fc_fuse_pass done!
Model optimized.
Exporting inference model from python code
Fail to generate inference model! Problem happend while export inference model from python code 'x2paddle_code.py'
```

详细报错信息：
```
===================Error Information===============
Traceback (most recent call last):
  File "trans.py", line 14, in <module>
    pytorch2paddle(module=disp_net, 
  File "anaconda3/envs/work/lib/python3.8/site-packages/x2paddle/convert.py", line 199, in pytorch2paddle
    mapper.paddle_graph.gen_model(save_dir, jit_type=jit_type)
  File "anaconda3/envs/work/lib/python3.8/site-packages/x2paddle/core/program.py", line 279, in gen_model
    raise e
  File "/anaconda3/envs/work/lib/python3.8/site-packages/x2paddle/core/program.py", line 273, in gen_model
    self.dygraph2static(save_dir, input_shapes, input_types)
  File "anaconda3/envs/work/lib/python3.8/site-packages/x2paddle/core/program.py", line 538, in dygraph2static
    paddle.jit.save(static_model,
  File "<decorator-gen-67>", line 2, in save
  File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 718, in save
    concrete_program = static_func.concrete_program_specify_input_spec(
  File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 487, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 698, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "<decorator-gen-65>", line 2, in from_func_spec
  File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
KeyError: 
In transformed code:
File "SfMlearner_trans/pd_model_trace/x2paddle_code.py", line 319, in forward (* user code *)
x8 = self.upconv70(x7)
File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_call_func.py", line 140, in convert_call
"Convert callable object: convert {}.".format(func))
File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1189, in __repr__
sublayer_str = repr(layer)
File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1185, in __repr__
extra_repr = self.extra_repr()
File "anaconda3/envs/work/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 173, in extra_repr
return main_str.format(**self.__dict__)
KeyError: \'_output_padding\'
```
注意到keyError项最后给出out_padding关键词，故怀疑是conv2dtranspose的转化出错

**Comment by wjj19950828** [comment]
这个是跟paddle框架有关，更新到最新的paddle即可，相关PR：https://github.com/PaddlePaddle/Paddle/pull/33429

**Comment by jianganbai** [comment]
谢谢回复，使用百度源更新paddle和x2paddle后的确不报错了

**Comment by wjj19950828** [comment]
没事，记得点个star
