### ISSUE TITLE
upsample_nearest2d 算子仅使用 `scale_factor` 参数时转换出错

### ISSUE THREAD

**Issue by lytning98** [PaddlePaddle/X2Paddle#647]
`torch.nn.functional.interpolate` 转换出错，详情见下

#### 环境
x2paddle 1.3.0
pytorch 1.8.1

#### 最小复现代码：
```python3
class Debug(torch.nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        x = torch.nn.functional.interpolate(x, scale_factor=2.0, mode='nearest')
        return x

model = Debug()
input = torch.randn((1, 256, 14, 14), dtype=torch.float32)

pytorch2paddle(module=model,
    save_dir="./convert/output/debug",
    jit_type="trace",
    input_examples=[input])
```

#### 报错信息
```python3
Traceback (most recent call last):
  File "converter.py", line 95, in <module>
    convert_Debug()
  File "converter.py", line 79, in convert_Debug
    pytorch2paddle(module=model,
  File "/xx/anaconda3/envs/paddle_real/lib/python3.9/site-packages/x2paddle/convert.py", line 192, in pytorch2paddle
    mapper = PyTorchOpMapper(model)
  File "/xx/anaconda3/envs/paddle_real/lib/python3.9/site-packages/x2paddle/op_mapper/pytorch2paddle/pytorch_op_mapper.py", line 42, in __init__
    self.paddle_graph, _ = self.traverse(decoder.graph)
  File "/xx/anaconda3/envs/paddle_real/lib/python3.9/site-packages/x2paddle/op_mapper/pytorch2paddle/pytorch_op_mapper.py", line 113, in traverse
    inputs, outputs = func(self, graph, node)
  File "/xx/anaconda3/envs/paddle_real/lib/python3.9/site-packages/x2paddle/op_mapper/pytorch2paddle/aten.py", line 5533, in aten_upsample_nearest2d
    mapper._check_input(graph, inputs_node[3], inputs_name[3],
IndexError: list index out of range
```

**Comment by lytning98** [comment]
报错的代码在这里，看起来是下标写错了，改成2可以正常转换
https://github.com/PaddlePaddle/X2Paddle/blob/379ce426d3f5656a6428f058d66423c0d9ef4cc8/x2paddle/op_mapper/pytorch2paddle/aten.py#L5516-L5518
+@SunAhong1993 as PR author
