### ISSUE TITLE
cannot import name 'polish_model' from 'onnx.utils'

### ISSUE THREAD

**Issue by KoTion** [PaddlePaddle/X2Paddle#649]
模型是由paddlex训练的yolov3转为onnx的，在使用x2paddle转为paddle时，报如下错误：

paddle.__version__ = 2.1.1
Now translating model from onnx to paddle.
Traceback (most recent call last):
  File "/root/anaconda3/envs/torch2paddle/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.3.0', 'console_scripts', 'x2paddle')())
  File "/root/anaconda3/envs/torch2paddle/lib/python3.7/site-packages/x2paddle-1.3.0-py3.7.egg/x2paddle/convert.py", line 259, in main
    onnx2paddle(args.model, args.save_dir)
  File "/root/anaconda3/envs/torch2paddle/lib/python3.7/site-packages/x2paddle-1.3.0-py3.7.egg/x2paddle/convert.py", line 160, in onnx2paddle
    from x2paddle.decoder.onnx_decoder import ONNXDecoder
  File "/root/anaconda3/envs/torch2paddle/lib/python3.7/site-packages/x2paddle-1.3.0-py3.7.egg/x2paddle/decoder/onnx_decoder.py", line 19, in <module>
    from onnx.utils import polish_model
ImportError: cannot import name 'polish_model' from 'onnx.utils' (/root/anaconda3/envs/torch2paddle/lib/python3.7/site-packages/onnx/utils.py)

**Comment by yeliang2258** [comment]
请问onnx装的是那个版本？

**Comment by yeliang2258** [comment]
请问安装的onnx是那个版本？

**Comment by KoTion** [comment]
> 好像安装的onnx是那个版本？

onnx是1.9.0的

**Comment by yeliang2258** [comment]
> > 好像安装的onnx是那个版本？
> 
> onnx是1.9.0的

onnx安装1.7.0再试一下
