### ISSUE TITLE
tensorflow 文本分类 文本命名实体识别 转换异常

### ISSUE THREAD

**Issue by natureLanguageQing** [PaddlePaddle/X2Paddle#653]
请说明模型的来源，模型类型（例如图像分类、目标检测等）  

如有原模型文件或github链接，如方便可一并附上，方便开发人员分析。

**为了便于开发人员快速定位原因，建议将模型文件上传（或通过百度网盘分享）**

## 示例

模型来源： TensorFlow
模型说明： 文本分类 文本命名实体识别，其相应repo为 https://github.com/bert4keras
模型文件： 链接：https://pan.baidu.com/s/1DSBcTXekqrTwzCeJ8nEbNA 提取码：296t
转换过程出错提示如下：
```
paddle.__version__ = 2.0.0
C:\ProgramData\Anaconda3\envs\X2Paddle\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importli
b; see the module's documentation for alternative uses
  import imp
Now translating model from tensorflow to paddle.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\X2Paddle\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\X2Paddle\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\X2Paddle\Scripts\x2paddle.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\envs\X2Paddle\lib\site-packages\x2paddle\convert.py", line 256, in main
    define_input_shape, args.paddle_type)
  File "C:\ProgramData\Anaconda3\envs\X2Paddle\lib\site-packages\x2paddle\convert.py", line 113, in tf2paddle
    model = TFDecoder(model_path, define_input_shape=define_input_shape)
  File "C:\ProgramData\Anaconda3\envs\X2Paddle\lib\site-packages\x2paddle\decoder\tf_decoder.py", line 339, in __init__
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message

```

**Comment by jiangjiajun** [comment]
以上转换过程，常出现的问题是，转换TensorFlow时，注意输入的模型需为FrozenGraph格式，你当前可以检查下你转换时输入的是否符合要求，根据上面的提示，猜测你可能将`SavedModel`格式模型传了进去

------------
另外你这边转换模型的应用场景是什么呢，方便开发人员更好的了解用户需求

**Comment by natureLanguageQing** [comment]
FrozenGraph格式转换paddle model 时候异常。
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 1 of node StatefulPartitionedCall_2 was passed float from hanzi/embeddings:0 incompatible with expected resource.

**Comment by natureLanguageQing** [comment]
文本分类 命名实体识别 为了模型加密选择了paddlex作为备选方案。

**Comment by natureLanguageQing** [comment]
感谢回复
