### ISSUE TITLE
caffemodel转PaddlePaddle 失败 AttributeError: input

### ISSUE THREAD

**Issue by 78666621** [PaddlePaddle/X2Paddle#658]
模型来源： CAFFE
模型说明： RCF边缘检测，其相应GitHub：https://github.com/yun-liu/RCF
模型文件：链接：https://pan.baidu.com/s/1vscZPDIWE3tia9V-1Fo7OQ 提取码：c2ya 
环境：python3.8
转换过程出错提示如下：
paddle.__version__ = 2.1.1
Now translating model from caffe to paddle.
Total nodes: 70
Nodes converting ...
Converting node 15 ...     Traceback (most recent call last):
  File "G:\Anaconda3\envs\eiseg\Scripts\x2paddle-script.py", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.3.1', 'console_scripts', 'x2paddle')())
  File "G:\Anaconda3\envs\eiseg\lib\site-packages\x2paddle\convert.py", line 255, in main
    caffe2paddle(args.prototxt, args.weight, args.save_dir,
  File "G:\Anaconda3\envs\eiseg\lib\site-packages\x2paddle\convert.py", line 137, in caffe2paddle
    mapper = CaffeOpMapper(model)
  File "G:\Anaconda3\envs\eiseg\lib\site-packages\x2paddle\op_mapper\caffe2paddle\caffe_op_mapper.py", line 147, in __init__
    self.directly_map(node)
  File "G:\Anaconda3\envs\eiseg\lib\site-packages\x2paddle\op_mapper\caffe2paddle\caffe_op_mapper.py", line 171, in directly_map
    inputs = node.layer.input
AttributeError: input

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/X2Paddle/pull/663
你好，由于X2Paddle先前Eltwise和Crop, 以及Directly map 3个OP类型转换过程中字段没考虑完全导致转换失败，目前在PR中已修复，请拉这个PR进行测试。
