### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by fcqfcq** [PaddlePaddle/X2Paddle#671]
模型来源： pytorch
模型说明： 图像分割模型，其相应repo为 https://github.com/xxxx
模型文件： https://github.com/xuebinqin/U-2-Net  u2netp
onnx == <1.6,1.9>
x2paddle==1.3.1
paddlepaddle-gpu=2.1.2
paddlelite=2.9.1
转换过程出错提示如下：
```
Now translating model from onnx to paddle.
Traceback (most recent call last):
  File "/media/anaconda/envs/pd/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/media//anaconda/envs/pd/lib/python3.7/site-packages/x2paddle/convert.py", line 286, in main
    onnx2paddle(args.model, args.save_dir, args.paddle_type)
  File "/media//anaconda/envs/pd/lib/python3.7/site-packages/x2paddle/convert.py", line 180, in onnx2paddle
    from x2paddle.decoder.onnx_decoder import ONNXDecoder
  File "/media/anaconda/envs/pd/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py", line 17, in <module>
    from x2paddle.decoder.onnx_shape_inference import SymbolicShapeInference
  File "/media//anaconda/envs/pd/lib/python3.7/site-packages/x2paddle/decoder/onnx_shape_inference.py", line 24, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'

```

**Comment by yeliang2258** [comment]
请尝试使用下面命令安装，pip install packaging
