### ISSUE TITLE
onnx模型转换时，报MemoryError: std::bad_alloc

### ISSUE THREAD

**Issue by saler-1** [PaddlePaddle/X2Paddle#679]
模型来源： mmdetection的yolov3_d53_mstrain-608_273e_coco重训练模型
模型说明：  
1.转onnx
'''
python tools/deployment/pytorch2onnx.py     configs/yolo/yolov3_d53_mstrain-608_273e_coco.py     /u01/Code/mmdetection/work_dirs/yolov3_d53_mstrain-608_273e_coco/latest.pth     --output-file /u01/Code/mmdetection/work_dirs/yolov3_d53_mstrain-608_273e_coco/yolov3_d53_mstrain-608_273e_coco.onnx     --input-img /u01/Code/mmdetection/data/VOCdevkit/VOC2007/JPEGImages/站101_transformer.jpg     --test-img tests/data/color.jpg     --shape 608 608     --mean 0 0 0     --std 255 255 255     --show     --verify    --dynamic-export     --cfg-options       model.test_cfg.deploy_nms_pre=-1 
'''
结果：
'''
Successfully exported ONNX model: /u01/Code/mmdetection/work_dirs/yolov3_d53_mstrain-608_273e_coco/yolov3_d53_mstrain-608_273e_coco.onnx
...
The numerical values are the same between Pytorch and ONNX
'''

2.onnx转paddle
'''
x2paddle --framework=onnx --model=/u01/Code/mmdetection/work_dirs/yolov3_d53_mstrain-608_273e_coco/yolov3_d53_mstrain-608_273e_coco.onnx --save_dir=/u01/Code/mmdetection/work_dirs/yolov3_d53_mstrain-608_273e_coco/pd_model

'''
转换过程出错提示如下：

过程中输入：Shape of Input(e.g. -1,3,224,224), enter 'N' to skip: N
```
 x2paddle --framework=onnx --model=/u01/Code/mmdetection/work_dirs/yolov3_d53_mstrain-608_273e_coco/yolov3_d53_mstrain-608_273e_coco.onnx --save_dir=/u01/Code/mmdetection/work_dirs/yolov3_d53_mstrain-608_273e_coco/pd_model
paddle.__version__ = 2.1.3
/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/onnx/mapping.py:25: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
Now translating model from onnx to paddle.
model ir_version: 6, op version: 11
Unknown shape for input tensor[tensor name: 'x2paddle_input'] -> shape: ['batch', 3, 'width', 'height'], Please define shape of input here,
Note:you can use visualization tools like Netron to check input shape.
Shape of Input(e.g. -1,3,224,224), enter 'N' to skip: N
shape inferencing ...
Stopping at incomplete shape inference at Concat: x2paddle_641
node inputs:
name: "x2paddle_640"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "floor(1.0*batch)"
      }
      dim {
        dim_value: 256
      }
      dim {
        dim_param: "floor(2.0*floor(floor(floor(floor(floor(width/2 - 1/2)/2)/2)/2)/2) + 2.0)"
      }
      dim {
        dim_param: "floor(2.0*floor(floor(floor(floor(floor(height/2 - 1/2)/2)/2)/2)/2) + 2.0)"
      }
    }
  }
}

name: "x2paddle_586"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "batch"
      }
      dim {
        dim_value: 512
      }
      dim {
        dim_param: "floor(floor(floor(floor(width/2 - 1/2)/2)/2)/2) + 1"
      }
      dim {
        dim_param: "floor(floor(floor(floor(height/2 - 1/2)/2)/2)/2) + 1"
      }
    }
  }
}

node outputs:
name: "x2paddle_641"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
      }
      dim {
        dim_value: 768
      }
      dim {
      }
      dim {
      }
    }
  }
}

!!!!!!!!!!
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 11, automatically treated as op_set: 9.
Total nodes: 717
Nodes converting ...
Converting node 633 ...     Traceback (most recent call last):
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/x2paddle-1.3.2-py3.7.egg/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 101, in run_mapping
    res = func(*args, **kwargs)
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/x2paddle-1.3.2-py3.7.egg/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 1077, in Slice
    idx]] and val_x.out_shapes[0][axes[idx]] > 0:
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u01/anaconda3/envs/mmdetection/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.3.2', 'console_scripts', 'x2paddle')())
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/x2paddle-1.3.2-py3.7.egg/x2paddle/convert.py", line 261, in main
    onnx2paddle(args.model, args.save_dir)
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/x2paddle-1.3.2-py3.7.egg/x2paddle/convert.py", line 165, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/x2paddle-1.3.2-py3.7.egg/x2paddle/op_mapper/onnx2paddle/onnx_op_mapper.py", line 44, in __init__
    func(node)
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/x2paddle-1.3.2-py3.7.egg/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 104, in run_mapping
    node.name[9:], node.layer_type))
Exception: convert failed node:895, op_type is Slice
```
输入
Shape of Input(e.g. -1,3,224,224), enter 'N' to skip: 1,3,608,608
'''
 x2paddle --framework=onnx --model=/u01/Code/mmdetection/work_dirs/yolov3_d53_mstrain-608_273e_coco/yolov3_d53_mstrain-608_273e_coco.onnx --save_dir=/u01/Code/mmdetection/work_dirs/yolov3_d53_mstrain-608_273e_coco/pd_model
paddle.__version__ = 2.1.3
/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/onnx/mapping.py:25: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
Now translating model from onnx to paddle.
model ir_version: 6, op version: 11
Unknown shape for input tensor[tensor name: 'x2paddle_input'] -> shape: ['batch', 3, 'width', 'height'], Please define shape of input here,
Note:you can use visualization tools like Netron to check input shape.
Shape of Input(e.g. -1,3,224,224), enter 'N' to skip: 1,3,608,608
shape inferencing ...
/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/x2paddle-1.3.2-py3.7.egg/x2paddle/decoder/onnx_shape_inference.py:510: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  new_v = int(np.asscalar(v))
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 11, automatically treated as op_set: 9.
Total nodes: 717
Nodes converting ...
Converting node 1147 ...     
Nodes converted.
Exporting inference model from python code ('/u01/Code/mmdetection/work_dirs/yolov3_d53_mstrain-608_273e_coco/pd_model/x2paddle_code.py')... 

/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
Fail to generate inference model! Problem happend while export inference model from python code '/u01/Code/mmdetection/work_dirs/yolov3_d53_mstrain-608_273e_coco/pd_model/x2paddle_code.py';

===================Error Information===============
Traceback (most recent call last):
  File "/u01/anaconda3/envs/mmdetection/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.3.2', 'console_scripts', 'x2paddle')())
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/x2paddle-1.3.2-py3.7.egg/x2paddle/convert.py", line 261, in main
    onnx2paddle(args.model, args.save_dir)
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/x2paddle-1.3.2-py3.7.egg/x2paddle/convert.py", line 167, in onnx2paddle
    mapper.paddle_graph.gen_model(save_dir)
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/x2paddle-1.3.2-py3.7.egg/x2paddle/core/program.py", line 280, in gen_model
    raise e
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/x2paddle-1.3.2-py3.7.egg/x2paddle/core/program.py", line 274, in gen_model
    self.dygraph2static(save_dir, input_shapes, input_types)
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/x2paddle-1.3.2-py3.7.egg/x2paddle/core/program.py", line 554, in dygraph2static
    osp.join(save_dir, "inference_model/model"))
  File "<decorator-gen-66>", line 2, in save
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 726, in save
    inner_input_spec)
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 491, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 705, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-64>", line 2, in from_func_spec
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 661, in from_func_spec
    error_data.raise_new_exception()
  File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
MemoryError: In transformed code:

    File "/u01/Code/mmdetection/work_dirs/yolov3_d53_mstrain-608_273e_coco/pd_model/x2paddle_code.py", line 676, in forward (* user code *)
	x2paddle_739_ones = paddle.full(shape=x2paddle_738, dtype='int64', fill_value=1)
    File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/tensor/creation.py", line 466, in full
	return fill_constant(shape=shape, dtype=dtype, value=fill_value, name=name)
    File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/layers/tensor.py", line 751, in fill_constant
	stop_gradient=True)
    File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
	return self.main_program.current_block().append_op(*args, **kwargs)
    File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2967, in append_op
	attrs=kwargs.get("attrs", None))
    File "/u01/anaconda3/envs/mmdetection/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2154, in __init__
	self.desc.infer_shape(self.block.desc)
    MemoryError: std::bad_alloc

'''

**Comment by yeliang2258** [comment]
您好，请提供一下你的onnx模型

**Comment by saler-1** [comment]
> 您好，请提供一下你的onnx模型
链接: https://pan.baidu.com/s/1CXKfqckkjx-lUBLMPjrJZQ 提取码: 512y

**Comment by yeliang2258** [comment]
可以尝试一下使用paddlepaddle的CPU运行，不要调用GPU

**Comment by saler-1** [comment]
> 可以尝试一下使用paddlepaddle的CPU运行，不要调用GPU

还是同样的报错，环境如下
'''
(test_pp_cpu) [10:15:37 lhh:/u01/Code/mmdetection ] # pip list
Package            Version
------------------ ---------
astor              0.8.1
brotlipy           0.7.0
certifi            2021.5.30
cffi               1.14.6
charset-normalizer 2.0.4
cryptography       3.4.7
decorator          5.0.9
gast               0.3.3
idna               3.2
mkl-fft            1.0.14
mkl-random         1.0.4
mkl-service        2.3.0
mpmath             1.2.1
numpy              1.17.0
olefile            0.46
onnx               1.6.0
packaging          21.0
paddlepaddle       2.1.3
Pillow             8.3.1
pip                21.2.2
protobuf           3.17.2
pycparser          2.20
pyOpenSSL          20.0.1
pyparsing          2.4.7
PySocks            1.7.1
requests           2.26.0
setuptools         58.0.4
six                1.16.0
sympy              1.8
typing-extensions  3.10.0.2
urllib3            1.26.6
wheel              0.37.0
x2paddle           1.3.2
'''

**Comment by vxfla** [comment]
请问解决了吗，我也遇到了同样的问题。现在打算直接把项目源码转了..

**Comment by yeliang2258** [comment]
> 请问解决了吗，我也遇到了同样的问题。现在打算直接把项目源码转了..

你好，请试一下只使用paddle的CPU版本，看是否能转成功。谢谢

**Comment by saler-1** [comment]
> 请问解决了吗，我也遇到了同样的问题。现在打算直接把项目源码转了..

你用cpu版本的转换成功没有   我这边还是同样的报错

**Comment by vxfla** [comment]
> 
> 
> > 请问解决了吗，我也遇到了同样的问题。现在打算直接把项目源码转了..
> 
> 你用cpu版本的转换成功没有 我这边还是同样的报错

cpu版本也失败了，我转源码重新练了

**Comment by yeliang2258** [comment]
> > > 请问解决了吗，我也遇到了同样的问题。现在打算直接把项目源码转了..
> > 
> > 
> > 你用cpu版本的转换成功没有 我这边还是同样的报错
> 
> cpu版本也失败了，我转源码重新练了

CPU版本的报错是？

**Comment by saler-1** [comment]
> > > > 既然解决了，我也遇到了同样的问题。现在可以直接把项目源码转了..
> > > 
> > > 
> > > 你用cpu版本的转换成功了我还是同样的报错
> > 
> > 
> > cpu也失败了，我转原版重练了
> 
> CPU 版本的报错是什么？

同样的报错，MemoryError: std::bad_alloc....最开始用的其实也是cpu版本的，后面重建了个虚拟环境，还是这个错
