### ISSUE TITLE
onnx模型转paddle提示 Exception: convert failed node:577, op_type is Slice

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/X2Paddle#697]
库版本:
    paddlepaddle            2.1.3
    x2paddle                1.3.0

模型来源：pytorch(转换至onnx成功，未报错)
模型说明：关键点模型，backbone为shufflenetV2
模型文件： 待如流给出
转换过程出错提示如下：
```
convert to paddle xxx_pose
paddle.__version__ = 2.1.3
Now translating model from onnx to paddle.
model ir_version: 4, op version: 11
shape inferencing ...
/usr/local/Cellar/python@3.6/3.6.10/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/lib/type_check.py:546: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  'a.item() instead', DeprecationWarning, stacklevel=1)
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 11, automatically treated as op_set: 9.
Total nodes: 560
Nodes converting ...
Converting node 811 ...     Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.6/3.6.10/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 101, in run_mapping
    res = func(*args, **kwargs)
  File "/usr/local/Cellar/python@3.6/3.6.10/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 1062, in Slice
    axes = _const_weight_or_none(axes_node, necessary=True).tolist()
AttributeError: 'NoneType' object has no attribute 'tolist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/python@3.6/3.6.10/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/x2paddle/convert.py", line 259, in main
    onnx2paddle(args.model, args.save_dir)
  File "/usr/local/Cellar/python@3.6/3.6.10/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/x2paddle/convert.py", line 163, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "/usr/local/Cellar/python@3.6/3.6.10/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/x2paddle/op_mapper/onnx2paddle/onnx_op_mapper.py", line 44, in __init__
    func(node)
  File "/usr/local/Cellar/python@3.6/3.6.10/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 104, in run_mapping
    node.name[9:], node.layer_type))
Exception: convert failed node:577, op_type is Slice
```

而x2paddle0.8版本则提示:
```
convert to paddle xxx_pose
paddle.__version__ = 1.8.5
Now translating model from onnx to paddle.
model ir_version: 4, op version: 11
shape inferencing ...
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 11, automatically treated as op_set: 9.
Total nodes: 560
Nodes converting ...
Warnning: paddle not support op:resize wiht mode: linear, we use bilinear replace linear
Warnning: paddle not support op:resize wiht mode: linear, we use bilinear replace linear
Warnning: paddle not support op:resize wiht mode: linear, we use bilinear replace linear
Nodes converted.
Model optimizing ...
Model optimized.
Paddle model and code generating ...
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.6/3.6.10/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/x2paddle/core/op_mapper.py", line 142, in save_inference_model
    inputs, outputs = model.x2paddle_net()
  File "/Users/model_with_code/model.py", line 272, in x2paddle_net
    x2paddle_577 = fluid.layers.strided_slice(x2paddle_565, axes=None, starts=x2paddle_573_cast, ends=x2paddle_574_cast, strides=[1])
  File "/usr/local/Cellar/python@3.6/3.6.10/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 12048, in strided_slice
    check_type(axes, 'axes', (list, tuple), 'strided_slice')
  File "/usr/local/Cellar/python@3.6/3.6.10/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/paddle/fluid/data_feeder.py", line 97, in check_type
    (input_name, op_name, expected_type, type(input), extra_message))
TypeError: The type of 'axes' in strided_slice must be (<class 'list'>, <class 'tuple'>), but received <class 'NoneType'>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/python@3.6/3.6.10/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/x2paddle/convert.py", line 282, in main
    onnx2paddle(args.model, args.save_dir, params_merge)
  File "/usr/local/Cellar/python@3.6/3.6.10/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/x2paddle/convert.py", line 178, in onnx2paddle
    mapper.save_inference_model(save_dir, params_merge)
  File "/usr/local/Cellar/python@3.6/3.6.10/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/x2paddle/core/op_mapper.py", line 197, in save_inference_model
    .format(py_code_dir))
Exception: Paddle code was saved in /Users/paddle/model_with_code/model.py, but seems there's wrong exist, please check model.py manually.
```

**Comment by ZJX-CV** [comment]
我也是pytorch转onnx没办错只有tracewarning，我看网上说可以忽略。但是onnx转paddle就报错：Exception: convert failed node:_base_stages_1_blocks_0_attn_Pad_output_0, op_type is Pad

**Comment by DeadlyAbyss** [comment]
一样的问题，请问大佬们解决了吗

**Comment by ZJX-CV** [comment]
换个模型，转onnx的版本换下或者



---原始邮件---
发件人: "Yingzhi ***@***.***&gt;
发送时间: 2024年6月17日(周一) 晚上9:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/X2Paddle] onnx模型转paddle提示 Exception: convert failed node:577, op_type is Slice (Issue #697)




 
一样的问题，请问大佬们解决了吗
