### ISSUE TITLE
pytorch2paddle转ResNet18出错

### ISSUE THREAD

**Issue by Yihouyihou** [PaddlePaddle/X2Paddle#698]
模型来源：pytorch的 ResNet18模型
模型说明：图像分类模型，其repo为https://github.com/ozanciga/self-supervised-histopathology/releases/tag/tenpercent
转换过程出错提示如下：
```
========= 1 OPs are not supported yet ===========
========== aten::linear ============
Traceback (most recent call last):
  File "D:\zhuyuang\projects\multi-classification\torchTransformPaddle.py", line 43, in <module>
    pytorch2paddle(module=model,
  File "C:\Users\lenovo\.conda\envs\paddle\lib\site-packages\x2paddle\convert.py", line 249, in pytorch2paddle
    mapper = PyTorchOpMapper(model)
  File "C:\Users\lenovo\.conda\envs\paddle\lib\site-packages\x2paddle\op_mapper\pytorch2paddle\pytorch_op_mapper.py", line 41, in __init__
    raise Exception("Model is not supported yet.")
Exception: Model is not supported yet.
```

**Comment by wjj19950828** [comment]
因为开发过程依赖PyTorch 1.6.0，将版本降为1.6.0应该可以解决此问题
