### ISSUE TITLE
onnx  opset11 Slice error

### ISSUE THREAD

**Issue by zgq91** [PaddlePaddle/X2Paddle#752]
环境:paddle 2.2.2, onnx opset11,x2paddle1.3.5；转换mmdection训练的yolov3.onnx  链接: https://pan.baidu.com/s/1xzOLXguibbImhjf7g02oGw 提取码: s9tf   出现以下错误:

INFO:root:paddle.__version__ = 2.2.2
INFO:root:Now translating model from onnx to paddle.
model ir_version: 7, op version: 11
shape inferencing ...
[WARNING] Incomplete symbolic shape inference
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 11, automatically treated as op_set: 9.
Total nodes: 730
Nodes converting ...
Converting node 815 ...     Traceback (most recent call last):
  File "/home/gpu/anaconda3/lib/python3.8/site-packages/x2paddle-1.3.5-py3.8.egg/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 107, in run_mapping
    res = func(*args, **kwargs)
  File "/home/gpu/anaconda3/lib/python3.8/site-packages/x2paddle-1.3.5-py3.8.egg/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 1161, in Slice
    if starts_value[idx] >= val_x.out_shapes[0][axes[
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gpu/anaconda3/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.3.5', 'console_scripts', 'x2paddle')())
  File "/home/gpu/anaconda3/lib/python3.8/site-packages/x2paddle-1.3.5-py3.8.egg/x2paddle/convert.py", line 349, in main
    onnx2paddle(
  File "/home/gpu/anaconda3/lib/python3.8/site-packages/x2paddle-1.3.5-py3.8.egg/x2paddle/convert.py", line 219, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "/home/gpu/anaconda3/lib/python3.8/site-packages/x2paddle-1.3.5-py3.8.egg/x2paddle/op_mapper/onnx2paddle/onnx_op_mapper.py", line 44, in __init__
    func(node)
  File "/home/gpu/anaconda3/lib/python3.8/site-packages/x2paddle-1.3.5-py3.8.egg/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 109, in run_mapping
    raise Exception("convert failed node:{}, op_type is {}".format(
Exception: convert failed node:824, op_type is Slice

**Comment by wjj19950828** [comment]
@zgq91 我看您有在转mmocr以及mmdetection的模型，这个是什么业务背景呢，可以描述一下吗～

**Comment by zgq91** [comment]
> @zgq91 我看您有在转mmocr以及mmdetection的模型，这个是什么业务背景呢，可以描述一下吗～

对铁包的编号识别,用paddleOCR dbnet文本检测用同样的模型识别率会比mmocr更低；mmocr能达到0.98,paddleOCR只能达到0.94左右

**Comment by wjj19950828** [comment]
@zgq91 这个slice op之前修过，源码安装最新的x2paddle即可解决~
```shell
pip uninstall x2paddle
cd X2Paddle
python setup.py install
```

**Comment by zgq91** [comment]
> @zgq91 这个slice op之前修过，源码安装最新的x2paddle即可解决~
> 
> ```shell
> pip uninstall x2paddle
> cd X2Paddle
> python setup.py install
> ```

您好，我用源码安装最新的x2paddle还是报同样的错误 
![image](https://user-images.githubusercontent.com/18069515/157161328-b38a984d-e1f5-4595-b2f0-e3c3a9fe8c4f.png)

**Comment by wjj19950828** [comment]
@zgq91 有卸载之前版本吗，pip uninstall一下

**Comment by zgq91** [comment]
> @zgq91 有卸载之前版本吗，pip uninstall一下

有卸载了之前的版本,重新安装的

**Comment by wjj19950828** [comment]
@zgq91 我确定是可以的呀，你删除之前源码，重新git clone一下再安装吧

**Comment by zgq91** [comment]
> @zgq91 我确定是可以的呀，你删除之前源码，重新git clone一下再安装吧

好奇怪 我这边删除之前的源码，重新git clone还是一样报错；转成动态的onnx，不会报错Slice 但会报以下错误。
x2paddle --framework onnx --model yolo.onnx  --save_dir yolo_model
INFO:root:paddle.__version__ = 2.2.2
INFO:root:Now translating model from onnx to paddle.
model ir_version: 7, op version: 11
Unknown shape for input tensor[tensor name: 'x2paddle_input'] -> shape: ['batch', 3, 'height', 'width'], Please define shape of input here,
Note:you can use visualization tools like Netron to check input shape.
Shape of Input(e.g. -1,3,224,224), enter 'N' to skip: -1,3,640,480
shape inferencing ...
[WARNING] Incomplete symbolic shape inference
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 11, automatically treated as op_set: 9.
Total nodes: 746
Nodes converting ...
Converting node 719 ...     Traceback (most recent call last):
  File "/home/gpu/anaconda3/lib/python3.8/site-packages/x2paddle-1.3.5-py3.8.egg/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 107, in run_mapping
    res = func(*args, **kwargs)
  File "/home/gpu/anaconda3/lib/python3.8/site-packages/x2paddle-1.3.5-py3.8.egg/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 1686, in MatMul
    if y_shape[0] == 1 and x_shape[-1] != 1 and x_shape[0] != 1:
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gpu/anaconda3/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.3.5', 'console_scripts', 'x2paddle')())
  File "/home/gpu/anaconda3/lib/python3.8/site-packages/x2paddle-1.3.5-py3.8.egg/x2paddle/convert.py", line 349, in main
    onnx2paddle(
  File "/home/gpu/anaconda3/lib/python3.8/site-packages/x2paddle-1.3.5-py3.8.egg/x2paddle/convert.py", line 219, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "/home/gpu/anaconda3/lib/python3.8/site-packages/x2paddle-1.3.5-py3.8.egg/x2paddle/op_mapper/onnx2paddle/onnx_op_mapper.py", line 44, in __init__
    func(node)
  File "/home/gpu/anaconda3/lib/python3.8/site-packages/x2paddle-1.3.5-py3.8.egg/x2paddle/op_mapper/onnx2paddle/opset9/opset.py", line 109, in run_mapping
    raise Exception("convert failed node:{}, op_type is {}".format(
Exception: convert failed node:568, op_type is MatMul

**Comment by wjj19950828** [comment]
@zgq91  你的onnx模型是不是提供错了，这边onnx输入是固定的
![image](https://user-images.githubusercontent.com/19977378/157176582-db11556a-b147-4d17-8df1-9f7613634944.png)

**Comment by zgq91** [comment]
> @zgq91 你的onnx模型是不是提供错了，这边onnx输入是固定的 ![image](https://user-images.githubusercontent.com/19977378/157176582-db11556a-b147-4d17-8df1-9f7613634944.png)

链接: https://pan.baidu.com/s/1xhRJG9u2cs8V2X-pSBmaPw 提取码: 3d41 动态的onnx刚上传,麻烦你那边测试一下；我这边用按你之前提供方法还是不行

**Comment by wjj19950828** [comment]
@zgq91 您好，因为一些历史原因当reshape里有超过两个-1时动转静会失败，静态shape的onnx的reshape节点有-1，所以动态shape会有两个-1，目前我调整了shape手动动转静成功，验证没问题，你下载一下吧～

链接: https://pan.baidu.com/s/1xDv6nHOZq0RTW9peQGrWGg 提取码: 13fb

**Comment by zgq91** [comment]
> @zgq91 您好，因为一些历史原因当reshape里有超过两个-1时动转静会失败，静态shape的onnx的reshape节点有-1，所以动态shape会有两个-1，目前我调整了shape手动动转静成功，验证没问题，你下载一下吧～
> 
> 链接: https://pan.baidu.com/s/1xDv6nHOZq0RTW9peQGrWGg 提取码: 13fb

非常感谢，试了可以，能否将你修改后代码更新到X2Paddle上；后期我会需要改变输入大小

**Comment by wjj19950828** [comment]
@zgq91 上传的有一份动态图代码x2paddle_code.py，根据相应shape做对应修改，因为是手动修改所以不适配所有模型，目前推荐先静态shape转换->手动动态shape动转静

**Comment by zgq91** [comment]
> @zgq91 上传的有一份动态图代码x2paddle_code.py，根据相应shape做对应修改，因为是手动修改所以不适配所有模型，目前推荐先静态shape转换->手动动态shape动转静

能分享一下，你改的代码嘛，我这边检测算法还在训练中，之前上传的onnx模型不是最终部署

**Comment by wjj19950828** [comment]
@zgq91 我并没有改相应代码，可直接输入静态shape，然后照着x2paddle_code.py修改相应shape即可

**Comment by zgq91** [comment]
> shape

是onnx模型输入静态shape?  但model.pdparams模型参数怎么获取的呢

**Comment by wjj19950828** [comment]
@zgq91 仅支持batch纬度动态，所以与模型参数无关
