### ISSUE TITLE
onnx 转换为paddle失败

### ISSUE THREAD

**Issue by tomjeans** [PaddlePaddle/X2Paddle#767]
感谢您参与 X2Paddle 社区！ 问题模版为了 X2Paddle 能更好的迭代，例如新功能发布、 RoadMaps 和错误跟踪. :smile_cat:

## 问题描述
你好 我通过转换 tf2onnx 转换 movenet tensorflow pb模型到onnx 然后通过x2paddle 转换报错
- 错误信息
===================Error Information===============
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "/home/test/.local/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/home/test/.local/lib/python3.6/site-packages/x2paddle/convert.py", line 354, in main
    lite_model_type=args.lite_model_type)
  File "/home/test/.local/lib/python3.6/site-packages/x2paddle/convert.py", line 221, in onnx2paddle
    mapper.paddle_graph.gen_model(save_dir)
  File "/home/test/.local/lib/python3.6/site-packages/x2paddle/core/program.py", line 280, in gen_model
    raise e
  File "/home/test/.local/lib/python3.6/site-packages/x2paddle/core/program.py", line 274, in gen_model
    self.dygraph2static(save_dir, input_shapes, input_types)
  File "/home/test/.local/lib/python3.6/site-packages/x2paddle/core/program.py", line 554, in dygraph2static
    osp.join(save_dir, "inference_model/model"))
  File "<decorator-gen-101>", line 2, in save
  File "/home/test/.local/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/test/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/home/test/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/jit.py", line 744, in save
    inner_input_spec)
  File "/home/test/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/home/test/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/test/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/test/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
    **cache_key.kwargs)
  File "<decorator-gen-99>", line 2, in from_func_spec
  File "/home/test/.local/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/test/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/home/test/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 668, in from_func_spec
    error_data.raise_new_exception()
  File "/home/test/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "pd_model_movenent/x2paddle_code.py", line 131, in forward
        x2paddle_Concat__388_0 = self.x2paddle_Concat__388_0
        x2paddle_StatefulPartitionedCall_Cast_0 = paddle.cast(x=x2paddle_input, dtype='float32')
        x2paddle_StatefulPartitionedCall_unstack_0 = paddle.split(x=x2paddle_StatefulPartitionedCall_Cast_0, num_or_sections=1)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        x2paddle_StatefulPartitionedCall_sub_0 = paddle.subtract(x=x2paddle_StatefulPartitionedCall_unstack_0, y=x2paddle_StatefulPartitionedCall_Reshape_0)
        x2paddle_StatefulPartitionedCall_truediv_1_0 = paddle.multiply(x=x2paddle_StatefulPartitionedCall_sub_0, y=x2paddle_StatefulPartitionedCall_truediv_0)

    File "/home/test/.local/lib/python3.6/site-packages/paddle/tensor/manipulation.py", line 850, in split
        input=x, num_or_sections=num_or_sections, dim=axis, name=name)
    File "/home/test/.local/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 5005, in split
        assert num_or_sections > 1, 'num_or_sections must be more than 1.'

    AssertionError: num_or_sections must be more than 1.
## 具体信息

- 转换模型后用处
    - [] 使用 Paddle 框架/ PaddleInference 推理预测
    - [*] 使用 Paddle-Lite 做移动端推理
    - [ ] 转换预训练参数，再使用 Paddle 进行模型开发
- 模型来源
Movnet: wget -q -O movenet_singlepose_thunder_4.tar.gz https://tfhub.dev/google/movenet/singlepose/thunder/4?tf-hub-format=compressed
- 应用场景
用于移动端业务下的检测业务
- 版本信息
PaddlePaddle => :2.2.2:
X2Paddle => :1.3.5:
来源框架版本(PyTorch/TF/ONNX/Caffe) => :TF:2.3.0:
- 您的联系方式(邮箱/微信/电话)
877848676@qq.com

**Comment by tomjeans** [comment]
这是模型文件 谢谢 链接: https://pan.baidu.com/s/1hIdxm0cHtO-VxUPYJot5Tg 提取码: 6wpm 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v3的分享

**Comment by wjj19950828** [comment]
@tomjeans 关于```num_or_sections=1```的bug已在这个PR修复：https://github.com/PaddlePaddle/X2Paddle/pull/763
git clone develop分支代码，输入下列命令，源码安装即可
```shell
pip uninstall x2paddle
cd X2Paddle
python setup.py install
```
然后看你部署环境是Paddle Lite，目前X2Paddle支持一键转换为Lite支持格式，命令行加入```--to_lite=True```即可，我这边验证是可以成功转换的

更多细节可参考文档：https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/inference_model_convertor/convert2lite_api.md

**Comment by tomjeans** [comment]
谢谢 现在能转换成功
