### ISSUE TITLE
ValueError: (InvalidArgument) transpose2(): argument 'X' (position 0) must be Tensor, but got Tensor (at ..\paddle/fluid/pybind/op_function.h:816)

### ISSUE THREAD

**Issue by yizhangliu** [PaddlePaddle/X2Paddle#775]
一个transformer（人体动作识别），转 onnx, 再转 paddle 都成功。运行 x2paddle_code.py时，报：
Traceback (most recent call last):
  File "x2paddle_code.py", line 390, in <module>
    out = main(in0)
  File "x2paddle_code.py", line 381, in main
    out = model(x2paddle_0)
  File "C:\Users\ThinkPad\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Users\ThinkPad\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "x2paddle_code.py", line 153, in forward
    x2paddle_77 = paddle.transpose(x=x2paddle_0, perm=[0, 4, 3, 1, 2])
  File "C:\Users\ThinkPad\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\layers\nn.py", line 5551, in transpose
    out, _ = _C_ops.transpose2(x, 'axis', perm)
ValueError: (InvalidArgument) transpose2(): argument 'X' (position 0) must be Tensor, but got Tensor (at ..\paddle/fluid/pybind/op_function.h:816)

“argument 'X' (position 0) must be Tensor, but got Tensor”， 这一句 甚是 不解？

**Comment by jiangjiajun** [comment]
传入的这个x2paddle_0 需要是一个tensor， 可以查下你是不是传入了一个numpy进去

**Comment by yizhangliu** [comment]
> 传入的这个x2paddle_0 需要是一个tensor， 可以查下你是不是传入了一个numpy进去

感谢你的回复。但我传入的是 tensor,  这样的：
        import numpy as np
        import torch
        input_data = np.random.rand(1,1,30,13,5).astype("float32")
        in0 = torch.tensor(input_data) 
        out = main(in0)
        print(out)

后来，我使用 inference_model, 可以了。(一个小模型)
在 transformer (模型结构相对复杂一些) 上，还是 无法 正确加载和推理。

**Comment by jiangjiajun** [comment]
```
out = model(x2paddle_0)
```
确认这里代码`x2paddle_0`是否是一个tensor，你可以使用`out = model(paddle.to_tensor(x2paddle_0)`

**Comment by yizhangliu** [comment]
@jiangjiajun  Thanks.
paddle.to_tensor 可以。
