### ISSUE TITLE
 Couldn't find x2paddle_52_p0 in previous layers, the layers should be make by topological sort

### ISSUE THREAD

**Issue by duorouputao** [PaddlePaddle/X2Paddle#780]
感谢您参与 X2Paddle 社区！ 问题模版为了 X2Paddle 能更好的迭代，例如新功能发布、 RoadMaps 和错误跟踪. :smile_cat:

## 问题描述

- [错误信息](url)
- 
- 错误截图
![image](https://user-images.githubusercontent.com/62918268/165433082-b357cce8-c649-41b9-89a0-758f7d02183f.png)

## 具体信息

- 转换模型后用处
    - [ ] 使用 Paddle 框架/ PaddleInference 推理预测
    - [√] 使用 Paddle-Lite 做移动端推理
    - [ ] 转换预训练参数，再使用 Paddle 进行模型开发
- 模型来源
lstm
- 应用场景
用于移动端业务下的摔倒检测
- 版本信息
PaddlePaddle => :grey_question:
X2Paddle => :grey_question:1.0.1
来源框架版本(PyTorch/TF/ONNX/Caffe) =>onnx
- 您的联系方式(邮箱/微信/电话)
740383531@qq.com

**Comment by wjj19950828** [comment]
@duorouputao 我看你X2Paddle版本信息1.0.1，建议升级到最新版本1.3.6再试试

**Comment by duorouputao** [comment]
更新了还是不行
C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\urllib3\util\selectors.py:14: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import namedtuple, Mapping
C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\urllib3\_collections.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Mapping, MutableMapping
paddle.__version__ = 2.2.2
Now translating model from onnx to paddle.
model ir_version: 6, op version: 9
shape inferencing ...
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 9, automatically treated as op_set: 9.
Total nodes: 23
Nodes converting ...
Converting node 28 ...     ['lstm0.weight_ih_l0', 'lstm0.weight_hh_l0', 'lstm0.bias_ih_l0', 'lstm0.bias_hh_l0']
Converting node 30 ...     ['lstm1.weight_ih_l0', 'lstm1.weight_hh_l0', 'lstm1.bias_ih_l0', 'lstm1.bias_hh_l0']
Converting node 37 ...
Nodes converted.
Traceback (most recent call last):
  File "d:\programdata\miniconda3\envs\py37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programdata\miniconda3\envs\py37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Miniconda3\envs\py37\Scripts\x2paddle.exe\__main__.py", line 7, in <module>
  File "D:\Gitprj\fall\X2Paddle-develop\x2paddle\convert.py", line 264, in main
    onnx2paddle(args.model, args.save_dir, args.paddle_type)
  File "D:\Gitprj\fall\X2Paddle-develop\x2paddle\convert.py", line 173, in onnx2paddle
    mapper.paddle_graph.build()
  File "D:\Gitprj\fall\X2Paddle-develop\x2paddle\core\program.py", line 181, in build
    v)
AssertionError: Couldn't find x2paddle_52_p0 in previous layers, the layers should be make by topological sort

**Comment by wjj19950828** [comment]
@duorouputao 麻烦把ONNX模型上传到百度云吧，这边排期看一下

另外这是个什么模型呢，这有一份问卷也麻烦填一下吧：https://iwenjuan.baidu.com/?code=npyd51

**Comment by duorouputao** [comment]
okok,是个带lstm的
https://pan.baidu.com/s/1igMqqxF5gDWQVFWd3emZfA 
提取码：4988 
麻烦大佬们看下
