### ISSUE TITLE
onnx 转 paddle 出错: NameError: name 'x2paddle_lambda_1' is not defined

### ISSUE THREAD

**Issue by kouhinn** [PaddlePaddle/X2Paddle#782]
## 问题描述
onnx 转 paddle 出错: NameError: name 'x2paddle_lambda_1' is not defined

- 错误信息
待转换的onnx模型和本地转换不成功结果上传到如下百度网盘：
链接：https://pan.baidu.com/s/1w7xtajs5WWB7oYMF1kLqiA 
提取码：6zp2 
--来自百度网盘超级会员V6的分享

详细信息如下：
Fail to generate inference model! Problem happend while export inference model from python code 'D:\disk_full_save_workspace\Keras-YOLOv4_helmet_retrain\fa
st_modelonnx2paddle\x2paddle_code.py';

===================Error Information===============
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\Scripts\x2paddle-script.py", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.3.5', 'console_scripts', 'x2paddle')())
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\x2paddle-1.3.5-py3.7.egg\x2paddle\convert.py", line 373, in main
    lite_model_type=args.lite_model_type)
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\x2paddle-1.3.5-py3.7.egg\x2paddle\convert.py", line 234, in onnx2paddle
    mapper.paddle_graph.gen_model(save_dir)
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\x2paddle-1.3.5-py3.7.egg\x2paddle\core\program.py", line 302, in gen_model
    raise e
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\x2paddle-1.3.5-py3.7.egg\x2paddle\core\program.py", line 296, in gen_model
    self.dygraph2static(save_dir, input_shapes, input_types)
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\x2paddle-1.3.5-py3.7.egg\x2paddle\core\program.py", line 580, in dygraph2static

    osp.join(save_dir, "inference_model/model"))
  File "<decorator-gen-101>", line 2, in save
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\paddle\fluid\dygraph\jit.py", line 744, in save
    inner_input_spec)
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 517, in con
crete_program_specify_input_spec
    *desired_input_spec)
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 427, in get
_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 723, in __g
etitem__
    self._caches[item] = self._build_once(item)
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 714, in _bu
ild_once
    **cache_key.kwargs)
  File "<decorator-gen-99>", line 2, in from_func_spec
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 668, in fro
m_func_spec
    error_data.raise_new_exception()
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 336, in raise_new_except
ion
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
NameError: In transformed code:

    File "fast_modelonnx2paddle\x2paddle_code.py", line 1103, in forward
                x2paddle_lambda_1_TopKV2_p0,x2paddle_lambda_1_TopKV2_p1 = paddle.topk(x=x2paddle_lambda_1_transpose_1_0_0_cast0, k=x2paddle_lambda_1_stride
d_slice_36_0_1_cast0, axis=-1)
                x2paddle_lambda_1_TopKV2_0_cropping0 = paddle.strided_slice(x=x2paddle_lambda_1_TopKV2_p0, axes=[0, 1], starts=[0, 0], ends=[2147483647, 10
0], strides=[1, 1])
                return x2paddle_lambda_1, x2paddle_lambda_1_1, x2paddle_lambda_1_2
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

        def main(x2paddle_input_1):


    NameError: name 'x2paddle_lambda_1' is not defined

- 错误截图

## 具体信息

- 转换模型后用处
    - [*] 使用 Paddle 框架/ PaddleInference 推理预测
    - [ ] 使用 Paddle-Lite 做移动端推理
    - [ ] 转换预训练参数，再使用 Paddle 进行模型开发
- 模型来源
      yolo4自实现

- 应用场景
用于移动端业务下的检测业务
- 版本信息
PaddlePaddle =>2.2
X2Paddle =>1.3.5
来源框架版本(PyTorch/TF/ONNX/Caffe) => Keras/TF
- 您的联系方式(邮箱/微信/电话)

**Comment by wjj19950828** [comment]
@kouhinn 感谢反馈，可以描述一下具体业务吗，然后方便留一个微信吗，想对您做一下用户调研～

**Comment by kouhinn** [comment]
> @kouhinn 感谢反馈，可以描述一下具体业务吗，然后方便留一个微信吗，想对您做一下用户调研～
具体业务：安防领域
微信号：kouhinn
