### ISSUE TITLE
TensorFlow转paddle出错：AttributeError: module 'gast' has no attribute 'Constant'

### ISSUE THREAD

**Issue by 1chang37** [PaddlePaddle/X2Paddle#798]
在进行TensorFlow 转换paddle时遇到的错误
平台信息：
paddlepaddle: 2.1.32
平台：ft2000+     昆仑k200
系统：kylin v10

指令：x2paddle --framework=tensorflow --model=vgg16.pb --save_dir=pd_model

报错:

XPURT /usr/local/lib64/python3.7/site-packages/paddle/fluid/../libs/libxpurt.so loaded

Now translating model from tensorflow to paddle.
Total nodes: 86
Nodes converting ...
Converting node 86 ...     
Nodes converted.
dygraph_conv2d_add_fuse_pass done!
dygraph_tf_batchnorm_fuse_pass done!
dygraph_prelu_fuse_pass done!
Optimize Transpose Layers...75.0%%
Transpose layers optimized, before: transpose_num=42, after: transpose_num=2
transpose_eliminate_pass done!
Exporting inference model from python code ('/workspace/X2Paddle/tf/pd_model/x2paddle_code.py')... 

/usr/local/lib64/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  return (isinstance(seq, collections.Sequence) and
Fail to generate inference model! Problem happend while export inference model from python code '/workspace/X2Paddle/tf/pd_model/x2paddle_code.py';

===================Error Information===============
Traceback (most recent call last):
  File "/usr/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.0.1', 'console_scripts', 'x2paddle')())
  File "/usr/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 256, in main
  File "/usr/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/convert.py", line 124, in tf2paddle
  File "/usr/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/core/program.py", line 248, in gen_model
  File "/usr/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/core/program.py", line 311, in gen_dygraph_model
  File "/usr/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/core/program.py", line 307, in gen_dygraph_model
  File "/usr/lib/python3.7/site-packages/x2paddle-1.0.1-py3.7.egg/x2paddle/core/program.py", line 682, in dygraph2static
  File "<decorator-gen-66>", line 2, in save
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 726, in save
    inner_input_spec)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 491, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 705, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-64>", line 2, in from_func_spec
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 623, in from_func_spec
    static_func = convert_to_static(dygraph_function)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 140, in convert_to_static
    static_func = _FUNCTION_CACHE.convert_with_cache(function)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 77, in convert_with_cache
    static_func = self._convert(func)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 115, in _convert
    root_wrapper = self._dygraph_to_static.get_static_ast(root)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 57, in get_static_ast
    self.static_analysis_visitor = StaticAnalysisVisitor(root)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/static_analysis.py", line 207, in __init__
    self.run(ast_root)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/static_analysis.py", line 215, in run
    self.dfs_visit(ast_root)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/static_analysis.py", line 241, in dfs_visit
    func_type = self.dfs_visit(child)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/static_analysis.py", line 244, in dfs_visit
    self.dfs_visit(child)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/static_analysis.py", line 244, in dfs_visit
    self.dfs_visit(child)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/static_analysis.py", line 244, in dfs_visit
    self.dfs_visit(child)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/static_analysis.py", line 247, in dfs_visit
    cur_wrapper.node_var_type = self._get_node_var_type(cur_wrapper)
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/static_analysis.py", line 286, in _get_node_var_type
    if isinstance(node, gast.Constant):
AttributeError: module 'gast' has no attribute 'Constant'

**Comment by 1chang37** [comment]
已解决
