### ISSUE TITLE
简单单层lstm onnx模型转paddle失败，用了onnx-simple也不行，使用x2paddle1.3.5

### ISSUE THREAD

**Issue by kouhinn** [PaddlePaddle/X2Paddle#804]
感谢您参与 X2Paddle 社区！ 问题模版为了 X2Paddle 能更好的迭代，例如新功能发布、 RoadMaps 和错误跟踪. :smile_cat:

## 问题描述
lstm onnx 模型转paddle失败，用了onnx-simple也不行，使用x2paddle1.3.5

- 错误信息
- 错误截图
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\x2paddle-1.3.5-py3.7.egg\x2paddle\op_mapper\onnx2paddle\opset9\opset.py", line
107, in run_mapping
    res = func(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\x2paddle-1.3.5-py3.7.egg\x2paddle\op_mapper\onnx2paddle\opset9\opset.py", line
2606, in LSTM
    'initial_states': (init_h.name, init_c.name)
UnboundLocalError: local variable 'init_h' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\Scripts\x2paddle-script.py", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.3.5', 'console_scripts', 'x2paddle')())
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\x2paddle-1.3.5-py3.7.egg\x2paddle\convert.py", line 373, in main
    lite_model_type=args.lite_model_type)
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\x2paddle-1.3.5-py3.7.egg\x2paddle\convert.py", line 227, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\x2paddle-1.3.5-py3.7.egg\x2paddle\op_mapper\onnx2paddle\onnx_op_mapper.py", lin
e 44, in __init__
    func(node)
  File "C:\Users\admin\anaconda3\envs\py37_tensorflow1_14\lib\site-packages\x2paddle-1.3.5-py3.7.egg\x2paddle\op_mapper\onnx2paddle\opset9\opset.py", line
110, in run_mapping
    node.name[9:], node.layer_type))
Exception: convert failed node:lstm_1_Y_p0, op_type is LSTM

## 具体信息
Exception: convert failed node:lstm_1_Y_p0, op_type is LSTM

- 转换模型后用处
    - [ ] 使用 Paddle 框架/ PaddleInference 推理预测
    - [*] 使用 Paddle-Lite 做移动端推理
    - [ ] 转换预训练参数，再使用 Paddle 进行模型开发
- 模型来源
来源一个简单lstm教学代码，代码上传到百度网盘
代码与模型均上传到百度网盘
链接：https://pan.baidu.com/s/1FizEveQZW-MCAy6U_XAUMQ 
提取码：6wa3 

- 应用场景
用于移动端业务下的检测业务

- 版本信息
PaddlePaddle =>paddlepaddle-gpu         2.2.2
X2Paddle => 1.3.5

来源框架版本(PyTorch/TF/ONNX/Caffe) => ONNX
- 您的联系方式(邮箱/微信/电话)
微信名kouhinn

**Comment by wjj19950828** [comment]
@kouhinn 感谢反馈～

这边有两个问题：
- 部署具体业务场景
- 转到Paddle部署的原因

这两点需要您在描述一下～

**Comment by kouhinn** [comment]
> @kouhinn 感谢反馈～
> 
> 这边有两个问题：
> 
> * 部署具体业务场景
>答：用于教育行业。
> * 转到Paddle部署的原因
> 答：支持多种硬件。
> 这两点需要您在描述一下～

**Comment by wjj19950828** [comment]
@kouhinn 您好，对于这种简单模型，建议直接paddle组网，然后再动转静

LSTM参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/LSTM_cn.html#lstm

动转静参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/jit/case_analysis_cn.html#inputspec

```python
net = LSTMNet()

x_spec = InputSpec(shape=[None, 10], name='x')  # 动态 shape
y_spec = InputSpec(shape=[3], name='y')

net = paddle.jit.to_static(net, input_spec=[x_spec, y_spec])

```

**Comment by kouhinn** [comment]
好的，谢谢。但是这个已经搞好的onnx模型应该也可以转换成paddle的吧，问题出在哪里呢？
