### ISSUE TITLE
1 OPs are not supported yet : If

### ISSUE THREAD

**Issue by AndSonder** [PaddlePaddle/X2Paddle#878]
感谢您参与 X2Paddle 社区！ 问题模版为了 X2Paddle 能更好的迭代，例如新功能发布、 RoadMaps 和错误跟踪. :smile_cat:

## 问题描述

- 错误信息

INFO:root:paddle.__version__ = 2.2.2t.
/Users/keter/opt/anaconda3/lib/python3.8/site-packages/onnx/mapping.py:27: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
INFO:root:Now translating model from onnx to paddle.
/Users/keter/opt/anaconda3/lib/python3.8/site-packages/sympy/external/importtools.py:158: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(modversion) < LooseVersion(min_module_version):
/Users/keter/opt/anaconda3/lib/python3.8/site-packages/sympy/core/cache.py:52: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if V(fastcache.__version__) < '0.4.0':
/Users/keter/opt/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/version.py:346: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
model ir_version: 6, op version: 11
shape inferencing ...
[WARNING] Incomplete symbolic shape inference
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [9],opset_verison of your onnx model is 11, automatically treated as op_set: 9.

========= 1 OPs are not supported yet ===========
========== If ============
Traceback (most recent call last):
  File "/Users/keter/opt/anaconda3/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/Users/keter/opt/anaconda3/lib/python3.8/site-packages/x2paddle/convert.py", line 475, in main
    onnx2paddle(
  File "/Users/keter/opt/anaconda3/lib/python3.8/site-packages/x2paddle/convert.py", line 290, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "/Users/keter/opt/anaconda3/lib/python3.8/site-packages/x2paddle/op_mapper/onnx2paddle/onnx_op_mapper.py", line 30, in __init__
    raise Exception("Model is not supported yet.")
Exception: Model is not supported yet.

- 错误截图

![image](https://user-images.githubusercontent.com/55493212/185793686-8c4d93d8-2ad4-4ac1-ad67-644bc2e14801.png)

## 具体信息

用MobileNetv3 做 baseline的一个关键点检测，Pytorch 模型 转换为 onnx 的代码是：

```
    input = torch.randn(1, 3, 512, 512)
    torch.onnx.export(model, input, onnx_path, export_params=True, opset_version=11, do_constant_folding=True,
                      input_names=['input1'], output_names=['output1', 'score'])
```

- 转换模型后用处
    - [x] 使用 Paddle-Lite 做移动端推理
- 应用场景
   人体关键点检测
- 版本信息
PaddlePaddle => 2.2.2
X2Paddle => 1.3.8
来源框架版本(PyTorch) => : 1.8.1
- 您的联系方式(changlu@keter.top)

我删除了模型里面所有的if语句，实在不知道哪里出错了

**Comment by wjj19950828** [comment]
@AndSonder ```If```这种控制流OP目前并不支持，再check一下是否后处理之类的逻辑放到了forward函数里面

另外，可以描述一下以下两个问题吗：
1、具体业务场景
2、为什么有转到Paddle部署的需求呢？

感谢～
