### ISSUE TITLE
Is caffe slice layer supported?

### ISSUE THREAD

**Issue by Alan-Turing-Ko** [PaddlePaddle/X2Paddle#89]
When trying to convert caffe to paddle, I got following error.

`squeeze idx:1, with kind:Convolution,name:conv1
Traceback (most recent call last):
  File "/home/turing/anaconda3/bin/x2paddle", line 10, in <module>
    sys.exit(main())
  File "/home/turing/anaconda3/lib/python3.6/site-packages/x2paddle/convert.py", line 163, in main
    args.caffe_proto)
  File "/home/turing/anaconda3/lib/python3.6/site-packages/x2paddle/convert.py", line 101, in caffe2paddle
    mapper = CaffeOpMapper(model)
  File "/home/turing/anaconda3/lib/python3.6/site-packages/x2paddle/op_mapper/caffe_op_mapper.py", line 44, in __init__
    self.set_node_shape(node)
  File "/home/turing/anaconda3/lib/python3.6/site-packages/x2paddle/op_mapper/caffe_op_mapper.py", line 80, in set_node_shape
    input_shape.append(last_node.output_shape[idx])
IndexError: list index out of range`

Hope to any suggestions.
Following is my prototxt.

name: "model"
layer {
  name: "input"
  type: "Input"
  top: "data"
  input_param {
    shape {
      dim: 1
      dim: 1
      dim: 128
      dim: 128
    }
  }
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 16
    pad: 2
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
      value: 0.1
    }
  }
}
layer {
  name: "slice1"
  type: "Slice"
  bottom: "conv1"
  top: "slice1_1"
  top: "slice1_2"
  slice_param {
    slice_dim: 1
  }
}
...

**Comment by jiangjiajun** [comment]
Hi，parameter `slice_dim` was not supported in x2paddle, because we have checked the parameter `slice_dim` is officially deprecated in caffe, see [Slice Layer of Caffe](https://caffe.berkeleyvision.org/tutorial/layers/slice.html)

But for your situation, we just updated x2paddle code(https://github.com/PaddlePaddle/X2Paddle/pull/92) to support your model conversion, use commands below :)
```
pip uninstall x2paddle
pip install git+https://github.com/PaddlePaddle/X2Paddle.git@develop
```
