### ISSUE TITLE
prim::PythonOp不支持

### ISSUE THREAD

**Issue by Sweet-BeanOnE** [PaddlePaddle/X2Paddle#891]
- 问题描述
prim::PythonOp不支持

- 错误信息
========= 1 OPs are not supported yet ===========
========== prim::PythonOp ============
Traceback (most recent call last):
  File "online_model.py", line 169, in <module>
    pytorch2paddle(module=model,
  File "/root/miniconda3/lib/python3.8/site-packages/x2paddle/convert.py", line 366, in pytorch2paddle
    mapper = PyTorchOpMapper(model)
  File "/root/miniconda3/lib/python3.8/site-packages/x2paddle/op_mapper/pytorch2paddle/pytorch_op_mapper.py", line 41, in __init__
    raise Exception("Model is not supported yet.")
Exception: Model is not supported yet.

- 转换模型后用处
PaddleInference 推理预测

- 模型来源
https://github.com/hanqer/deep-hough-transform

- 版本信息
PaddlePaddle => 默认 pip 版本
X2Paddle => 默认 pip 版本
来源框架版本PyTorch => 1.6.0

- 您的联系方式
zhongjingyu97@foxmail.com
18501900477

**Comment by wjj19950828** [comment]
@Sweet-BeanOnE 麻烦提供一下转换脚本以及模型参数，这边复现一下，也可以尝试一下先导出ONNX，再从ONNX转Paddle

另外，可以描述一下以下两个问题吗：
1、具体业务场景
2、为什么有转到Paddle部署的需求呢？

感谢～

**Comment by kidcats** [comment]
> * 问题描述
>   prim::PythonOp不支持
> * 错误信息
>   ========= 1 OPs are not supported yet ===========
>   ========== prim::PythonOp ============
>   Traceback (most recent call last):
>   File "online_model.py", line 169, in 
>   pytorch2paddle(module=model,
>   File "/root/miniconda3/lib/python3.8/site-packages/x2paddle/convert.py", line 366, in pytorch2paddle
>   mapper = PyTorchOpMapper(model)
>   File "/root/miniconda3/lib/python3.8/site-packages/x2paddle/op_mapper/pytorch2paddle/pytorch_op_mapper.py", line 41, in **init**
>   raise Exception("Model is not supported yet.")
>   Exception: Model is not supported yet.
> * 转换模型后用处
>   PaddleInference 推理预测
> * 模型来源
>   https://github.com/hanqer/deep-hough-transform
> * 版本信息
>   PaddlePaddle => 默认 pip 版本
>   X2Paddle => 默认 pip 版本
>   来源框架版本PyTorch => 1.6.0
> * 您的联系方式
>   [zhongjingyu97@foxmail.com](mailto:zhongjingyu97@foxmail.com)
>   18501900477

请问你导出到ONNX了吗，怎做到的，可以把脚本发我看看吗
