### ISSUE TITLE
tensorflow模型转换为paddlepaddle，发生读取错误

### ISSUE THREAD

**Issue by yinwangsong** [PaddlePaddle/X2Paddle#898]
## 问题描述

- 错误信息
使用命令
```
x2paddle -f tensorflow -m /Users/yws/small_bert_bert_en_uncased_L-2_H-128_A-2_2/saved_model.pb -s /Users/yws/small_bert_bert_en_uncased_L-2_H-128_A-2_2
```
进行转换时，发生了以下错误
```
INFO:root:Now translating model from TensorFlow to Paddle.
Traceback (most recent call last):
  File "/Users/yws/opt/anaconda3/envs/x2paddle/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/Users/yws/opt/anaconda3/envs/x2paddle/lib/python3.7/site-packages/x2paddle/convert.py", line 466, in main
    disable_feedback=args.disable_feedback)
  File "/Users/yws/opt/anaconda3/envs/x2paddle/lib/python3.7/site-packages/x2paddle/convert.py", line 174, in tf2paddle
    model = TFDecoder(model_path, define_input_shape=define_input_shape)
  File "/Users/yws/opt/anaconda3/envs/x2paddle/lib/python3.7/site-packages/x2paddle/decoder/tf_decoder.py", line 336, in __init__
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.GraphDef'
```

- 错误截图
<img width="1680" alt="Screen Shot 2022-09-22 at 8 51 31 PM" src="https://user-images.githubusercontent.com/48912667/191751763-dd07efe0-d945-4839-a7a5-4070070a7dfa.png">

## 具体信息

- 转换模型后用处
    使用 Paddle-Lite 做移动端推理
- 模型来源
    BERT：https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2
- 应用场景
    用于移动端业务下的检测业务
- 版本信息
    PaddlePaddle => 2.3.2
    X2Paddle => 1.3.9
    来源框架版本(PyTorch/TF/ONNX/Caffe) => tensorflow-cpu1.15.0 
- 您的联系方式(邮箱/微信/电话)
微信yinwangsong2000
邮箱yws@stu.pku.edu.cn

**Comment by wjj19950828** [comment]
@yinwangsong 可以尝试下先导出ONNX，再从ONNX2Paddle

另外，可以描述一下以下两个问题吗：
1、具体业务场景
2、为什么有转到Paddle部署的需求呢？

感谢～
