### ISSUE TITLE
PointPillars的ONNX模型，使用X2paddle工具转换，转换失败

### ISSUE THREAD

**Issue by cainiaoPCW** [PaddlePaddle/X2Paddle#907]
## 问题描述

-基于Pytorch训练的PointPillars模型，转换成ONNX模型后，将onnx模型使用X2paddle工具转换时，转换失败。
- 错误信息

> /usr/local/python3.7.5/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
INFO:root:paddle.__version__ = 2.3.2
/usr/local/python3.7.5/lib/python3.7/site-packages/onnx/mapping.py:25: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
INFO:root:Now translating model from onnx to paddle.
model ir_version: 6, op version: 11
shape inferencing ...
[WARNING] Incomplete symbolic shape inference
shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [7, 8, 9, 10, 11, 12, 13, 14, 15], opset_verison of your onnx model is 11.
Total nodes: 259
Nodes converting ...
Converting node 189 ...     Traceback (most recent call last):
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/opset_legacy.py", line 110, in run_mapping
    res = func(*args, **kwargs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/opset_legacy.py", line 1850, in Squeeze
    axes_node = self.graph.get_input_node(node, idx=1, copy=True)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py", line 353, in get_input_node
    ipt_node = super(ONNXGraph, self).get_node(node.inputs[idx], copy)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3.7.5/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/x2paddle/convert.py", line 488, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/x2paddle/convert.py", line 296, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/onnx_op_mapper.py", line 52, in __init__
    func(node)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/opset_legacy.py", line 113, in run_mapping
    node.name[9:], node.layer_type))
Exception: convert failed node:onnx__GatherND_135, op_type is Squeeze

- 转换命令
`x2paddle \
--framework=onnx \
--model=pointpillars.onnx \
--save_dir=./ \
--to_lite=True \
--lite_valid_places=x86 \
--lite_model_type=naive_buffer`

## 具体信息

- 转换模型后用处
    - [ ] 使用 Paddle-Lite 做移动端推理
- 模型来源
PointPillars：https://github.com/gakkiri/simple-pointpillar（修改了部分模型代码，字典部分改了了变量）
该代码是基于OpenPCdet (https://github.com/open-mmlab/OpenPCDet )的实现
- 应用场景
用于移动端业务下的检测业务
- 版本信息
PaddlePaddle => :最新
X2Paddle => :最新
来源框架版本(PyTorch/TF/ONNX/Caffe) => :pytorch
- 您的联系方式(邮箱/微信/电话)
806248826@qq.com

**Comment by wjj19950828** [comment]
@cainiaoPCW 您好，麻烦提供一下ONNX模型吧

另外，可以描述一下以下两个问题吗：
1、具体业务场景
2、为什么有转到Paddle部署的需求呢？

感谢～
