### ISSUE TITLE
ONNX转paddle报错 Your model ir_version is higher than the checker's.

### ISSUE THREAD

**Issue by ANDROIDTODO** [PaddlePaddle/X2Paddle#926]
感谢您参与 X2Paddle 社区！ 问题模版为了 X2Paddle 能更好的迭代，例如新功能发布、 RoadMaps 和错误跟踪. :smile_cat:

## 问题描述
ONNX转paddle报错 Your model ir_version is higher than the checker's.

- 错误信息
(x2paddle) D:\jerome\x2paddle>x2paddle --framework=onnx --model=14_recognition_model.onnx --save_dir=pd_model_dynamic
INFO:root:paddle.__version__ = 2.4.1
D:\software\anaconda3\envs\x2paddle\lib\site-packages\onnx\mapping.py:25: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
INFO:root:Now translating model from onnx to paddle.
model ir_version: 7, op version: 11
Traceback (most recent call last):
  File "D:\software\anaconda3\envs\x2paddle\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\software\anaconda3\envs\x2paddle\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\software\anaconda3\envs\x2paddle\Scripts\x2paddle.exe\__main__.py", line 7, in <module>
  File "D:\software\anaconda3\envs\x2paddle\lib\site-packages\x2paddle\convert.py", line 488, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "D:\software\anaconda3\envs\x2paddle\lib\site-packages\x2paddle\convert.py", line 295, in onnx2paddle
    model = ONNXDecoder(model_path, enable_onnx_checker)
  File "D:\software\anaconda3\envs\x2paddle\lib\site-packages\x2paddle\decoder\onnx_decoder.py", line 426, in __init__
    check_model(onnx_model)
  File "D:\software\anaconda3\envs\x2paddle\lib\site-packages\onnx\checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Your model ir_version is higher than the checker's.
- 错误截图

## 具体信息

- 转换模型后用处
    - [x] 使用 Paddle 框架/ PaddleInference 推理预测
    - [ ] 使用 Paddle-Lite 做移动端推理
    - [ ] 转换预训练参数，再使用 Paddle 进行模型开发
- 模型来源
https://drive.google.com/drive/folders/1j2a7QukI2xLVL1rsg-QEBAZPO2ruGzSJ

**Comment by ANDROIDTODO** [comment]
执行 pip install --upgrade onnx  就没问题了
