### ISSUE TITLE
onnx2paddle报错不支持conv_1

### ISSUE THREAD

**Issue by sunhanyu714** [PaddlePaddle/X2Paddle#945]
感谢您参与 X2Paddle 社区！ 问题模版为了 X2Paddle 能更好的迭代，例如新功能发布、 RoadMaps 和错误跟踪. :smile_cat:

## 问题描述
onnx2paddle报错不支持conv_1
- 错误信息
- INFO:root:paddle.__version__ = 2.4.1
INFO:root:Now translating model from onnx to paddle.
model ir_version: 6, op version: 11
Shape inferencing ...
/usr/local/lib/python3.8/site-packages/x2paddle/decoder/onnx_shape_inference.py:510: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  new_v = int(np.asscalar(v))
Shape inferenced.
/usr/local/lib/python3.8/site-packages/x2paddle/decoder/onnx_decoder.py:89: DeprecationWarning: `mapping.TENSOR_TYPE_TO_NP_TYPE` is now deprecated and will be removed in the next release or so.To silence this warning, please use `helper.{self._future_function}` instead.
  dtype = np.dtype(TENSOR_TYPE_TO_NP_TYPE[attr.t.data_type])
/usr/local/lib/python3.8/site-packages/x2paddle/decoder/onnx_decoder.py:369: DeprecationWarning: `mapping.TENSOR_TYPE_TO_NP_TYPE` is now deprecated and will be removed in the next release or so.To silence this warning, please use `helper.{self._future_function}` instead.
  TENSOR_TYPE_TO_NP_TYPE[item.type.tensor_type.elem_type],
Now, onnx2paddle support convert onnx model opset_verison [7, 8, 9, 10, 11, 12, 13, 14, 15], opset_verison of your onnx model is 11.
Total nodes: 102
Nodes converting ...
Converting node 1 ...     /usr/local/lib/python3.8/site-packages/x2paddle/decoder/onnx_decoder.py:169: DeprecationWarning: `mapping.TENSOR_TYPE_TO_NP_TYPE` is now deprecated and will be removed in the next release or so.To silence this warning, please use `helper.{self._future_function}` instead.
  return TENSOR_TYPE_TO_NP_TYPE[dtype]
Converting node 3 ...     /usr/local/lib/python3.8/site-packages/x2paddle/decoder/onnx_decoder.py:172: DeprecationWarning: `mapping.TENSOR_TYPE_TO_NP_TYPE` is now deprecated and will be removed in the next release or so.To silence this warning, please use `helper.{self._future_function}` instead.
  return TENSOR_TYPE_TO_NP_TYPE[dtype]
Converting node 90 ...     Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/x2paddle/op_mapper/onnx2paddle/opset_legacy.py", line 110, in run_mapping
    res = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/x2paddle/op_mapper/onnx2paddle/opset_legacy.py", line 2236, in Conv
    assert 2 <= convnd <= 3, 'only Conv2D and Conv3D is supported'
AssertionError: only Conv2D and Conv3D is supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/x2paddle/convert.py", line 489, in main
    onnx2paddle(
  File "/usr/local/lib/python3.8/site-packages/x2paddle/convert.py", line 304, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "/usr/local/lib/python3.8/site-packages/x2paddle/op_mapper/onnx2paddle/onnx_op_mapper.py", line 52, in __init__
    func(node)
  File "/usr/local/lib/python3.8/site-packages/x2paddle/op_mapper/onnx2paddle/opset_legacy.py", line 112, in run_mapping
    raise Exception("convert failed node:{}, op_type is {}".format(
Exception: convert failed node:188, op_type is Conv
- 错误截图

## 具体信息
- 转换模型后用处
   转换预训练参数，再使用 Paddle 进行模型开发，paddlepaddleslim量化训练
- 模型来源
openpcdet
- 应用场景
点云检测分类
- 版本信息
- 
![image](https://user-images.githubusercontent.com/65016415/220843711-0cac1dfd-e36c-4a82-936e-91a7c935a3b0.png)

来源框架版本(PyTorch) =>1.9.1
- 您的联系方式(邮箱/微信/电话)
- vx:15235358091
- 感谢回复~~

**Comment by sunhanyu714** [comment]
nn.Conv1d（）不支持吗？

**Comment by lichangW** [comment]
同问，遇到同样的问题
