### ISSUE TITLE
YOLOv8 Paddle export error: `IndexError: list assignment index out of range`

### ISSUE THREAD

**Issue by glenn-jocher** [PaddlePaddle/X2Paddle#948]
[YOLOv8](https://github.com/ultralytics/ultralytics) export to Paddle works correctly for Detection and Segmentation models, but fails on Classification models with error `IndexError: list assignment index out of range`.

Input to reproduce:
```bash
# Install ultralytics package
pip install ultralytics paddlepaddle x2paddle

# Export YOLOv8n to Paddle (works correctly)
yolo export model=yolov8n.pt format=paddle

# Export YOLOv8n-cls classification model to Paddle (ERROR)
yolo export model=yolov8n-cls.pt format=paddle
```

Output:
```
yolo export model=yolov8n-cls.pt format=paddle

Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-69a94e325a9a>", line 1, in <module>
    pytorch2paddle(module=self.model, save_dir=f, jit_type='trace', input_examples=[self.im])  # export
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.10/site-packages/x2paddle/convert.py", line 372, in pytorch2paddle
    mapper = PyTorchOpMapper(model)
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.10/site-packages/x2paddle/op_mapper/pytorch2paddle/pytorch_op_mapper.py", line 42, in __init__
    self.paddle_graph, _ = self.traverse(decoder.graph)
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.10/site-packages/x2paddle/op_mapper/pytorch2paddle/pytorch_op_mapper.py", line 121, in traverse
    inputs, outputs = func(self, graph, node)
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.10/site-packages/x2paddle/op_mapper/pytorch2paddle/aten.py", line 5067, in aten_silu
    scope_name = mapper.normalize_scope_name(node)
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.10/site-packages/x2paddle/op_mapper/pytorch2paddle/pytorch_op_mapper.py", line 314, in normalize_scope_name
    name_segments[j] = name
IndexError: list assignment index out of range
```

**Comment by wjj19950828** [comment]
@glenn-jocher Thanks for the feedback, I will check it out here～

**Comment by glenn-jocher** [comment]
@wjj19950828 hi there! Any updates? It's very strange because Paddle export works for YOLOv8 Detection and Segmentation models, but not for Classification models, which are generally much simpler.

**Comment by glenn-jocher** [comment]
@wjj19950828 closing this as original issue now appears resolved. Paddle is working for YOLOv8 Classification export :)
https://github.com/ultralytics/ultralytics/actions/runs/6038217143/job/16384116172?pr=4674

<img width="974" alt="Screenshot 2023-08-31 at 16 34 10" src="https://github.com/PaddlePaddle/X2Paddle/assets/26833433/ebb2d6d3-42f1-4780-bdb0-40d561beae58">
