### ISSUE TITLE
onnx2paddle 时decoder不支持if

### ISSUE THREAD

**Issue by Tavish77** [PaddlePaddle/X2Paddle#953]
感谢您参与 X2Paddle 社区！ 问题模版为了 X2Paddle 能更好的迭代，例如新功能发布、 RoadMaps 和错误跟踪. :smile_cat:

## 问题描述
在将onnx模型转成paddle时出错
- 错误信息
- 对asr的decoder转成paddle时出错：model ir_version: 7, op version: 13
Shape inferencing ...
[WARNING] Incomplete symbolic shape inference
Shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [7, 8, 9, 10, 11, 12, 13, 14, 15], opset_verison of your onnx model is 13.

========= 1 OPs are not supported yet ===========
========== If ============
C:\Users\test\AppData\Roaming\Python\Python39\site-packages\x2paddle\decoder\onnx_decoder.py:369: DeprecationWarning: `mapping.TENSOR_TYPE_TO_NP_TYPE` is now deprecated and will be removed in the next release or so.To silence this warning, please use `helper.{self._future_function}` instead.
  TENSOR_TYPE_TO_NP_TYPE[item.type.tensor_type.elem_type],
Traceback (most recent call last):
  File "C:\Users\test\sherpa_onnx\sherpa-onnx\sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20\onnx2paddle.py", line 2, in <module>
    onnx2paddle(model_path = "decoder-epoch-99-avg-1.onnx",save_dir = "pd_model")
  File "C:\Users\test\AppData\Roaming\Python\Python39\site-packages\x2paddle\convert.py", line 304, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "C:\Users\test\AppData\Roaming\Python\Python39\site-packages\x2paddle\op_mapper\onnx2paddle\onnx_op_mapper.py", line 38, in __init__
    raise Exception("Model is not supported yet.")
Exception: Model is not supported yet.

## 具体信息

- 转换模型后用处
    - [ ] 使用 Paddle 框架/ PaddleInference 推理预测
    - [√ ] 使用 Paddle-Lite 做移动端推理
    - [ ] 转换预训练参数，再使用 Paddle 进行模型开发
- 模型来源
YOLOX：https://github.com/Megvii-BaseDetection/YOLOX
- 应用场景
用于移动端业务下的语音识别服务
- 版本信息
PaddlePaddle => :grey_question:2.4.1
X2Paddle => :grey_question:最新版本
来源框架版本(PyTorch/TF/ONNX/Caffe) => :grey_question:1.13.0
- 您的联系方式(邮箱/微信/电话)
- 邮箱:lskhs@qq.com
- 电话：18929332593

**Comment by wjj19950828** [comment]
@Tavish77 目前ONNX2Paddle不支持控制流，建议去掉控制流再导出ONNX
