### ISSUE TITLE
pytorch模型转paddle的过程中， 1 OPs are not supported yet

### ISSUE THREAD

**Issue by pupubushilulu** [PaddlePaddle/X2Paddle#958]
你好，我在使用x2paddle把stgcn的模型转成paddle的过程中报错，报错信息如下：

========= 1 OPs are not supported yet ===========
========== aten::einsum ============
Traceback (most recent call last):
  File "stgcn2paddle.py", line 32, in <module>
    pytorch2paddle(module=model,save_dir=save_dir,jit_type=jit_type,input_examples=[data_tuple])
  File "/home/wzp/anaconda3/envs/x2paddle/lib/python3.8/site-packages/x2paddle/convert.py", line 380, in pytorch2paddle
    mapper = PyTorchOpMapper(model)
  File "/home/wzp/anaconda3/envs/x2paddle/lib/python3.8/site-packages/x2paddle/op_mapper/pytorch2paddle/pytorch_op_mapper.py", line 41, in __init__
    raise Exception("Model is not supported yet.")
Exception: Model is not supported yet.

请问以后会支持吗

**Comment by pupubushilulu** [comment]
已经解决，需要安装paddlenlp
