### ISSUE TITLE
用x2paddle转换onnx模型报错

### ISSUE THREAD

**Issue by xman1991** [PaddlePaddle/X2Paddle#969]
x2paddle  --framework onnx  --model  OSTrack_sim.onnx  --save_dir  pd_model
/home/kylin/.conda/envs/paddle_py37/lib/python3.7/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/home/kylin/.conda/envs/paddle_py37/lib/python3.7/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/kylin/.conda/envs/paddle_py37/lib/python3.7/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/kylin/.conda/envs/paddle_py37/lib/python3.7/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
INFO:root:paddle.__version__ = 0.0.0
INFO:root:[WARNING] You are use develop version of paddlepaddle
INFO:root:Now translating model from onnx to paddle.
model ir_version: 6, op version: 11
Shape inferencing ...
/home/kylin/.conda/envs/paddle_py37/lib/python3.7/site-packages/x2paddle/decoder/onnx_shape_inference.py:76: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  return np.asscalar(x)
Shape inferenced.
Now, onnx2paddle support convert onnx model opset_verison [7, 8, 9, 10, 11, 12, 13, 14, 15], opset_verison of your onnx model is 11.

========= 1 OPs are not supported yet ===========
========== ScatterElements ============
Traceback (most recent call last):
  File "/home/kylin/.conda/envs/paddle_py37/bin/x2paddle", line 33, in <module>
    sys.exit(load_entry_point('x2paddle==1.2.3', 'console_scripts', 'x2paddle')())
  File "/home/kylin/.conda/envs/paddle_py37/lib/python3.7/site-packages/x2paddle/convert.py", line 497, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/home/kylin/.conda/envs/paddle_py37/lib/python3.7/site-packages/x2paddle/convert.py", line 304, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "/home/kylin/.conda/envs/paddle_py37/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/onnx_op_mapper.py", line 38, in __init__
    raise Exception("Model is not supported yet.")
Exception: Model is not supported yet.

software: kylin v10、cuda-10.2、cudnn-8.2.1、x2paddle-1.4.1、paddle源码编译release/2.4分支
hardware:phytium d2000、gtx1060

**Comment by xman1991** [comment]
项目紧急希望尽快得到回复。
